# renewable data from REPD

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pyproj
import re
import os
os.chdir('/Users/simon/Desktop/uk-map/')
%matplotlib inline

In [2]:
# import the REPD

df = pd.read_excel('repd-q1-2019.xlsx', sheetname='Database') 

# force dates to be dates
df.convert_objects(convert_dates='coerce', convert_numeric=True)


# set column names to the 5th row
df.columns = df.iloc[4]
df.drop(df.index[0:5],inplace=True)

# drop rows without data
df.dropna(subset=['Site Name'], inplace=True)

# get rid of commas in the X-Y coordinates else it breaks the X-Y to lat-lon code

#df['X-coordinate'] = df['X-coordinate'].str.replace(',','')
#df['Y-coordinate'] = df['Y-coordinate'].str.replace(',','')

/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:6: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [3]:
# suppress errors in the "for" loops (I didn't understand them and they didn't seem to matter)
pd.options.mode.chained_assignment = None  # default='warn'

In [4]:
#df.head()

In [5]:
# drop entries without X-Y
# there aren't that many


df.dropna(subset=['X-coordinate'],inplace=True)

In [6]:

# drop non-data rows and columns

df.drop(df.index[:5], inplace=True)
df.columns.values[0] = 'blank1'
df.columns.values[1] = 'blank2'

# drop first two columns that are blank
df.drop(['blank1','blank2'], axis=1, inplace=True)

In [7]:
# fill empty x and y coords with locations as follows:
#df['X-coordinate'] = df['X-coordinate'].fillna(-477441) # somewhere west of Ireland
#df['Y-coordinate'] = df['Y-coordinate'].fillna(481803)

# there is about 45MW of no-location operational capacity
# some of it is eg Sainsburys solar rooftops across multiple sites but listed together
# might get caught by FiTs database, depending how we handle that

# correct entry with a comma in it
#df['X-coordinate'].loc[5178] = 51087

In [8]:
# convert X-Y coordinates to lat-lon

def proj_transform(df):
    bng = pyproj.Proj(init='epsg:27700')
    wgs84 = pyproj.Proj(init='epsg:4326')
    lon,lat = pyproj.transform(bng,wgs84, df['X-coordinate'], df['Y-coordinate'])    
    df['lat'] = lat
    df['lon'] = lon
    return df

df = df.apply(proj_transform, axis=1)

In [9]:
# select operational plants

operational = df.loc[df['Development Status']=='Operational']

# convert to datetime

operational['Operational'] =  pd.to_datetime(operational['Operational'])

# add year it opened

operational['Year Open'] = operational['Operational'].dt.year

In [10]:
#operational.head()

In [11]:
# select the columns we want
operational = operational[[
    'Site Name', 'Technology Type', 'Installed Capacity (MWelec)', 'Region',
    'lat', 'lon', 'Year Open','CHP Enabled','Operator (or Applicant)'
]]

In [12]:
# map the tech types into fuel/type as per conventional plants

di = {
    'Biomass (dedicated)': 'Biomass',
    'Advanced Conversion Technologies': 'Waste',
    'Anaerobic Digestion': 'Waste',
    'EfW Incineration': 'Waste',
    'Biomass (co-firing)': 'Biomass',
    'Large Hydro': 'Hydro',
    'Small Hydro': 'Hydro',
    'Landfill Gas': 'Waste',
    'Solar Photovoltaics': 'Solar',
    'Sewage Sludge Digestion' : 'Waste',
    'Tidal Barrage and Tidal Stream' : 'Wave & Tidal',
    'Shoreline Wave' : 'Wave & Tidal',
    'Wind Offshore' : 'Wind',
    'Wind Onshore' : 'Wind',
    'Pumped Storage Hydroelectricity' : 'Storage',
    'Battery' : 'Storage',
    'Flywheels' : 'Storage'
}

operational['Fuel'] = operational['Technology Type'].map(di)


di2 = {
    
    'Advanced Conversion Technologies': 'Advanced Conversion',
    'Anaerobic Digestion': 'Anaerobic Digestion',
    'EfW Incineration': 'Waste Incinerator',
    'Biomass (co-firing)': 'Co-firing',
    'Large Hydro': 'Large Hydro',
    'Small Hydro': 'Small Hydro',
    'Landfill Gas': 'Landfill Gas',
    'Sewage Sludge Digestion' : 'Sewage Sludge Digestion',
    'Tidal Barrage and Tidal Stream' : 'Tidal',
    'Shoreline Wave' : 'Wave',
    'Wind Offshore' : 'Offshore Wind',
    'Wind Onshore' : 'Onshore Wind',
    'Pumped Storage Hydroelectricity' : 'Pumped Hydro',
    'Battery' : 'Battery',
    'Flywheels' : 'Flywheeel'
}

operational['Type'] = operational['Technology Type'].map(di2)

In [13]:
# Add yearStart and yearEnd columns

# if the site opened before 2004, yearStart is 2004; otherwise opening year

operational['yearStart'] = np.where(operational['Year Open']<2004,2004,operational['Year Open'])

# sites continue to operate until 2030 unless they're wind/solar that would be >25 by then

operational['yearEnd'] = np.where(((operational['Year Open']<2005)&((operational.Fuel=='Wind')|(operational.Fuel=='Solar'))),2018,2019)

In [14]:
# drop tech type and rename other columns

operational = operational[[
    'Site Name', 'Installed Capacity (MWelec)', 'Region', 'lat', 'lon',
    'Year Open', 'CHP Enabled', 'Operator (or Applicant)', 'Fuel', 'Type',
    'yearStart', 'yearEnd'
]]

operational.columns = [
    'Site', 'Capacity (MW)', 'Region', 'Latitude', 'Longitude', 'Year Open',
    'CHP', 'Company', 'Fuel', 'Type', 'yearStart', 'yearEnd'
]

In [15]:
# group Drax units

operational.Site[operational.Site.str.contains('Drax')] = 'Drax Biomass'
operational.yearEnd[(operational.Site == 'Drax')&(operational.yearStart == 2013)] = 2013
operational.yearEnd[(operational.Site == 'Drax')&(operational.yearStart == 2014)] = 2016
operational.yearEnd[(operational.Site == 'Drax')&(operational.yearStart == 2017)] = 2017

operational['Capacity (MW)'][(operational.Site == 'Drax')&(operational.yearStart == 2014)] = 645*2
operational['Capacity (MW)'][(operational.Site == 'Drax')&(operational.yearStart == 2017)] = 645*3
operational['Capacity (MW)'][(operational.Site == 'Drax')&(operational.yearStart == 2018)] = 645*4

In [16]:
# add future 

# look at stuff under construction

building = df[df['Development Status']=='Under Construction']

# select the columns we want

building = building[[
    'Site Name', 'Technology Type', 'Installed Capacity (MWelec)', 'Region',
    'lat', 'lon', 'CHP Enabled','Operator (or Applicant)'
]]

building['yearStart'] = 2019
building['yearEnd'] = 2019

# use dicts from above to map tech types again

building['Fuel'] = building['Technology Type'].map(di)
building['Type'] = building['Technology Type'].map(di2)

# drop tech type and rename other columns

building = building[[
    'Site Name', 'Installed Capacity (MWelec)', 'Region', 'lat', 'lon',
    'CHP Enabled', 'Operator (or Applicant)', 'Fuel', 'Type',
    'yearStart', 'yearEnd'
]]

building.columns = [
    'Site', 'Capacity (MW)', 'Region', 'Latitude', 'Longitude',
    'CHP', 'Company', 'Fuel', 'Type', 'yearStart', 'yearEnd'
]

In [17]:
# add sites that already have CfDs but are not yet under construction

# sites drawn from CfD register as not terminated
# not yet operational nor under construction

di3 = {
    'BHEG Walsall': 'Yes',
    'Blackbridge TGS 1':'Yes',
    'Hornsea Project Two - Optimus and Breesea': 'Yes',
    'Fort Industrial Park (Castle Bromwich)': 'Yes',
    'MacColl Offshore Windfarm (Moray Firth)':'Yes',
    'Telford Offshore Windfarm (Moray Firth)':'Yes',
    'Stevenson Offshore Windfarm (Moray Firth)':'Yes',
    'Neart na Gaoithe':'Yes',
    'Northacre RRC':'Yes',
    'Solwaybank Wind Farm (resubmission)':'Yes',
    'Triton Knoll':'Yes',
    'Wren Power and Pulp (Rivenhall Airfield)':'Yes'
}

df['Contracted'] = df['Site Name'].map(di3)

cfd = df[df.Contracted=='Yes']

cfd['yearStart'] = 2019
cfd['yearEnd'] = 2019

# use dicts from above to map tech types again

cfd['Fuel'] = cfd['Technology Type'].map(di)
cfd['Type'] = cfd['Technology Type'].map(di2)

# drop tech type and rename other columns

cfd = cfd[[
    'Site Name', 'Installed Capacity (MWelec)', 'Region', 'lat', 'lon',
    'CHP Enabled', 'Operator (or Applicant)', 'Fuel', 'Type',
    'yearStart', 'yearEnd'
]]

cfd.columns = [
    'Site', 'Capacity (MW)', 'Region', 'Latitude', 'Longitude',
    'CHP', 'Company', 'Fuel', 'Type', 'yearStart', 'yearEnd'
]

In [18]:
# append "building" and "cfd" to the operational plants

renewable = operational.append(building)
renewable = renewable.append(cfd)

In [19]:
# remove Drax and Lynemouth from this data as fixed in conv

# make sure the index is unique before dropping rows
renewable = renewable.reset_index(drop=True)

renewable = renewable.drop(renewable[(
    (renewable.Site == 'Drax Biomass'))].index)

renewable = renewable.drop(renewable[(
    (renewable.Site == 'Lynemouth Power Station'))].index)

# remove Uskmouth co-firing

renewable = renewable.drop(renewable[(
    (renewable.Site == 'Uskmouth Power Station'))].index)

In [20]:
# correct operator for Greater Gabbard offshore windfarm

renewable['Company'] = np.where(renewable.Site.str.contains('Gabbard'),'SSE / Innogy',renewable['Company'])

In [30]:
# correct position of marine energy sites

renewable['Latitude'] = np.where(renewable.Site.str.contains('Billia Croo'),58.971711,renewable['Latitude'])
renewable['Longitude'] = np.where(renewable.Site.str.contains('Billia Croo'),-3.359961,renewable['Longitude'])

renewable['Latitude'] = np.where(renewable.Site.str.contains('MeyGen'),58.655803,renewable['Latitude'])
renewable['Longitude'] = np.where(renewable.Site.str.contains('MeyGen'),-3.130728,renewable['Longitude'])


renewable.head()

,CHP,Capacity (MW),Company,Fuel,Latitude,Longitude,Region,Site,Type,Year Open,yearEnd,yearStart
0,No,18.0,Dalkia,Biomass,54.668027,-1.566632,North East,Chilton Energy Plant,NaN,2012.0,2019,2012
1,Yes,1.5,Double H Nurseries,Biomass,50.750782,-1.678119,South East,Double H Nurseries Biomass Plant,NaN,2012.0,2019,2012
2,No,2.0,REACT Energy (Kedco),Waste,54.217507,-6.336669,Northern Ireland,Newry Biomass Phase 1 (Gasification),Advanced Conversion,2012.0,2019,2012
3,No,8.0,Balfor Beaty,Biomass,51.517777,0.093461,London,Beckton STW Biodiesel Power Plant,NaN,2010.0,2019,2010
4,No,2.0,Living Power (REG Bio-Power),Biomass,53.814327,-1.542615,Yorkshire and Humber,Buslingthorpe Power Station (Leeds North),NaN,2011.0,2019,2011

In [31]:


# get rid of rogue line breaks and carriage returns in the company names

renewable['Company'] = renewable['Company'].str.replace('\n', ' ')
renewable['Company'] = renewable['Company'].str.replace('\r', ' ')

# save the output

renewable.to_csv('renewable.csv',index=False,encoding='utf-8')

# analysis and checks

In [29]:
renewable[renewable.Site.str.contains('MeyGen')]

,CHP,Capacity (MW),Company,Fuel,Latitude,Longitude,Region,Site,Type,Year Open,yearEnd,yearStart
1299,n/a,6.0,Atlantis Resources,Wave & Tidal,58.741841,-3.11601,Offshore,Inner Sound Phase 1A (MeyGen),Tidal,2017.0,2019,2017

In [27]:
df[df['Site Name'].str.contains('Billia')]

58.971711, -3.359961

4,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Storage Type,Storage Co-location REPD Ref ID,Installed Capacity (MWelec),CHP Enabled,...,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational,lat,lon,Contracted
2006,EN00338,2452,2018-09-04,Wello,Wello Penguin Device (Billia Croo - EMEC),Shoreline Wave,NaN,NaN,1.0,n/a,...,2007-09-28 00:00:00,NaN,NaN,NaN,NaN,NaN,2008-05-27 00:00:00,58.732903,-3.324767,NaN

In [147]:
renewable[renewable.yearEnd==2018]

,CHP,Capacity (MW),Company,Fuel,Latitude,Longitude,Region,Site,Type,Year Open,yearEnd,yearStart
2019,n/a,4.000,Blyth Harbor Wind Ltd,Wind,55.136119,-1.490068,Offshore,Blyth Offshore,Offshore Wind,2000.0,2018,2004
2027,n/a,60.000,Greencoat (formerly Npower Renewables),Wind,53.417246,-3.448574,Offshore,North Hoyle,Offshore Wind,2003.0,2018,2004
2031,n/a,60.000,E.On,Wind,52.643946,1.788903,Offshore,Scroby Sands,Offshore Wind,2004.0,2018,2004
2077,n/a,1.470,Ecotricity,Wind,52.709894,1.654462,Eastern,South Beach Wind Turbine (Somerton),Onshore Wind,2000.0,2018,2004
2078,n/a,1.470,LRZ Ltd (Taken over by NOVERA),Wind,52.656729,0.683267,Eastern,Swaffham 1 - Ecotech Wind Park,Onshore Wind,1999.0,2018,2004
2079,n/a,10.200,Cynllun Trydan Gwynt,Wind,52.466297,-3.971001,Wales,Mynydd Gorddu Wind Farm,Onshore Wind,1998.0,2018,2004
2083,n/a,16.800,RWE npower,Wind,52.549433,-3.608163,Wales,Carno 'B' Wind Farm,Onshore Wind,1996.0,2018,2004
2084,n/a,16.800,RWE npower,Wind,52.542306,-3.579191,Wales,Carno 'A' Wind Farm,Onshore Wind,1996.0,2018,2004
2085,n/a,3.400,Vestas,Wind,52.657911,-3.672068,Wales,Cemmaes 'B' Wind Farm,Onshore Wind,2002.0,2018,2004
2086,n/a,5.600,RWE npower,Wind,53.374760,-4.346466,Wales,Trysglwyn Wind Farm,Onshore Wind,1996.0,2018,2004
2087,n/a,2.550,Private Developer,Wind,52.996202,-3.588257,Wales,Hafoty Ucha '2' and '3' Wind Turbine,Onshore Wind,2002.0,2018,2004
2090,n/a,3.000,Mersey Docks and Harbour Company and Windclust...,Wind,53.465214,-3.039310,North West,Royal Seaforth Dock Wind Farm,Onshore Wind,1999.0,2018,2004
2091,n/a,15.300,Vestas,Wind,52.639897,-3.674336,Wales,Cemmaes 'C' Wind Farm,Onshore Wind,2002.0,2018,2004
2096,n/a,20.400,MANWEB Generation Holdings,Wind,53.354376,-4.465566,Wales,Llanbabo Wind Farm,Onshore Wind,1997.0,2018,2004
2098,n/a,2.600,RWE npower,Wind,54.763804,-1.822800,North East,Tow Law Wind Farm,Onshore Wind,2001.0,2018,2004
2099,n/a,1.767,Border Wind Farms Ltd /AMEC,Wind,55.086539,-1.989004,North East,Kirkheaton Wind Farm,Onshore Wind,2000.0,2018,2004
2101,n/a,2.953,Border Windfarm Limited / AMEC,Wind,54.827285,-1.427158,North East,Great Eppleton Wind Farm,Onshore Wind,1997.0,2018,2004
2108,n/a,2.349,Great Orton Wind Farms (II) Ltd,Wind,54.870632,-3.072040,North West,Great Orton Wind Farm (Extension),Onshore Wind,2000.0,2018,2004
2109,n/a,2.500,The Wind Company Limited,Wind,54.204880,-3.146715,North West,Harlock Hill Wind Farm,Onshore Wind,1997.0,2018,2004
2113,n/a,4.200,Windprospect / Windcluster,Wind,54.674125,-3.542956,North West,Siddick Wind Farm,Onshore Wind,1996.0,2018,2004
2114,n/a,5.400,Windprospect / Windcluster,Wind,54.659574,-3.556357,North West,Oldside Wind Farm,Onshore Wind,1996.0,2018,2004
2115,n/a,2.372,The Wind Company,Wind,54.203954,-3.324533,North West,Haverigg Extension Wind Farm,Onshore Wind,1998.0,2018,2004
2118,n/a,3.877,WINDJEN POWER LTD,Wind,51.997111,-4.441253,Wales,Blaen Bowi Wind Farm,Onshore Wind,2002.0,2018,2004
2122,n/a,3.558,Micon Wind Turbines (UK) Limited,Wind,51.756930,-4.529708,Wales,Parc-Cynog Wind Farm,Onshore Wind,2001.0,2018,2004
2133,n/a,2.600,John Laing Environmental Assets Group,Wind,53.136342,-3.724976,Wales,Moel Maelogen A,Onshore Wind,2003.0,2018,2004
2136,n/a,8.979,Powergen Renewables Developments Ltd,Wind,53.668854,0.099446,Yorkshire and Humber,Out Newton Wind Farm,Onshore Wind,2002.0,2018,2004
2179,n/a,13.200,Scottish Power Renewables,Wind,55.362804,-4.126283,Scotland,Hare Hill (East Ayrshire),Onshore Wind,2000.0,2018,2004
2181,n/a,4.800,Npower Renewables,Wind,54.257491,-3.135725,North West,Kirkby Moor,Onshore Wind,1993.0,2018,2004
2201,n/a,1.200,Yorkshire Water,Wind,53.962432,-1.914154,Yorkshire and Humber,Chelker Reservoir (Retention of Turbines),Onshore Wind,2004.0,2018,2004
2223,n/a,9.000,Npower Renewables,Wind,51.569388,-3.464813,Wales,Taff Ely Wind Farm,Onshore Wind,1993.0,2018,2004
...,...,...,...,...,...,...,...,...,...,...,...,...
2621,n/a,3.680,Shetland Aerogenerators,Wind,60.164754,-1.236053,Scotland,Burradale Hill,Onshore Wind,2000.0,2018,2004
2674,n/a,6.500,Lambrigg Windfarm Ltd,Wind,54.336285,-2.635139,North West,Lambrigg Wind Farm,Onshore Wind,2001.0,2018,2004
2675,n/a,4.620,Windprospect / Windcluster,Wind,54.183872,-3.181378,North West,Far Old Park Farm Wind Farm,Onshore Wind,1999.0,2018,2004
2676,n/a,9.791,Natural Power,Wind,50.470291,-4.955627,South West,Bears Down Wind Farm,Onshore Wind,2001.0,2018,2004
2707,n/a,5.900,NaN,Wind,53.532199,-1.669566,Yorkshire and Humber,Royd Moor,Onshore Wind,1993.0,2018,2004
2732,n/a,2.400,Border Wind,Wind,54.763691,-1.757528,North East,Hedley Hope,Onshore Wind,2001.0,2018,2004
2733,n/a,12.750,Border Wind / Scottish and Southern (SSE),Wind,55.495291,-5.666585,Scotland,Tangy Wind Farm/Tangy 1,Onshore Wind,2002.0,2018,2004
2754,n/a,3.960,Cumbria Wind Farms,Wind,54.871489,-3.076738,North West,Great Orton,Onshore Wind,1999.0,2018,2004
2755,n/a,8.800,Cumbria Wind Farms,Wind,54.628777,-3.504059,North West,Winscales Phase I and II,Onshore Wind,2004.0,2018,2004
2757,n/a,2.750,E.On,Wind,54.847080,-1.677606,North East,Holmside Hall,Onshore Wind,2004.0,2018,2004
2758,n/a,5.500,E.On,Wind,54.693617,-1.300270,North East,High Volts Wind Farm,Onshore Wind,2003.0,2018,2004
2759,n/a,1.300,E.On,Wind,54.761581,-1.415109,North East,Hare Hill,Onshore Wind,2004.0,2018,2004
2772,n/a,6.600,Otter Power,Wind,50.645509,-4.546749,South West,Cold Northcott,Onshore Wind,2002.0,2018,2004
2787,n/a,2.700,Longearth Ltd / Farm Energy,Wind,59.097253,-2.660079,Scotland,Rothiesholm,Onshore Wind,2002.0,2018,2004
2790,n/a,50.600,Natural Power Consultants,Wind,57.537264,-3.362958,Scotland,Rothes Wind (Cairn Uish),Onshore Wind,2004.0,2018,2004
2808,n/a,2.400,Powergen,Wind,52.407581,-3.877228,Wales,Rheidol Wind Farm,Onshore Wind,1997.0,2018,2004
2810,n/a,15.750,Powergen Renewables,Wind,55.629281,-5.544010,Scotland,Deucheran Hill,Onshore Wind,2001.0,2018,2004
2817,n/a,7.260,Renewable Energy Systems (RES),Wind,54.393837,-7.148896,Northern Ireland,Lendrum's Bridge Wind Farm ( Extension 2),Onshore Wind,2002.0,2018,2004
2818,n/a,5.940,Renewable Energy Systems (RES),Wind,54.392654,-7.183398,Northern Ireland,Lendrum's Bridge Wind Farm,Onshore Wind,2000.0,2018,2004
2820,n/a,17.160,Renewable Energy Systems (RES),Wind,55.806457,-2.846032,Scotland,Dun Law,Onshore Wind,2000.0,2018,2004
2823,n/a,26.000,Renewable Energy Systems (RES) / BP Energy,Wind,54.962579,-7.034106,Northern Ireland,Altahullion,Onshore Wind,2003.0,2018,2004
2824,n/a,4.500,RES,Wind,50.288943,-5.137361,South West,Four Burrows Wind Farm,Onshore Wind,1998.0,2018,2004
2830,n/a,33.302,Scottish Power Renewables,Wind,56.039043,-5.155930,Scotland,Cruach Mhor,Onshore Wind,2004.0,2018,2004
2834,n/a,7.800,Trigen,Wind,55.555370,-3.920325,Scotland,"Hagshaw Hill (S15) Wind Farm, Lanarkshire",Onshore Wind,1995.0,2018,2004
2850,n/a,4.744,Windprospect,Wind,54.597368,-3.571011,North West,Lowca Wind Farm,Onshore Wind,2000.0,2018,2004
2853,n/a,1.150,Windprospect,Wind,54.203954,-3.324533,North West,Haverigg Repowering (Haverigg II),Onshore Wind,2004.0,2018,2004
2892,n/a,2.700,Border Wind Farms Ltd,Wind,55.125438,-1.495191,North East,Blyth Harbour Wind Farm,Onshore Wind,1992.0,2018,2004
3215,n/a,2.700,Longearth Ltd/ Farm Energy,Wind,59.097253,-2.660079,Scotland,Bu Farm,Onshore Wind,2002.0,2018,2004
3696,n/a,21.600,Fred Olsen Renewables,Wind,55.297065,-4.182939,Scotland,Brochloch Rig 1 (formerly Windy Standard),Onshore Wind,1996.0,2018,2004
5119,n/a,2.600,Renewable Energy Systems (RES),Wind,58.602359,-3.688136,Scotland,Forss Wind Farm,Onshore Wind,2003.0,2018,2004

In [127]:
renewable.Site[renewable.yearStart==2019]

92                            Port Clarence Biomass Plant
95                Merevale & Blyth Estate (Biomass Plant)
101                   Enviroparks Hirwaun Generation Site
133                           Tees Renewable Energy Plant
141           Brite Partnership Biomass Plant / Rotherham
144                            Pulse Park, Wellingborough
150                        Charlesfield Biomass CHP Plant
152                                        Discovery Park
261                 South Kirkby Business Park (Waste AD)
272     Queen Charlton Quarry Renewable Energy Facilit...
320
332                     Charlton Lane Eco Park (Waste AD)
346                                    Knostrop WWTW AD -
807         Ratty's Lane Sustainable Enery Facility (ACT)
827     Glasgow Renewable Energy and Recycling Centre ...
841                                        Beddington EfW
844                         K3 CHP Facility (Kemsley EfW)
854                                               Canford
855                                Belfast Harbour Estate
872                     Milton Keynes Waste Recovery Park
876                                         Rookery South
889               Dunbar EfW (previously Oxwellmains EfW)
895                                      Javelin Park EfW
896                          Charlton Lane Eco Park (ACT)
898                                        Parc Adfer EfW
904     Coatbridge Material Recovery and Renewable Ene...
905                  Severn Road Resource Recovery Centre
1304                                Lodge Farm Solar Farm
1981     Riverside Sewage Treatment Works Digestion Plant
2051                                             Beatrice
                              ...
4572                        Gameslack Farm (resubmission)
4598                                         Morayhill AD
4637                                         Langdon Mill
4638                                           Willand AD
4755                                  Parkhill Solar Farm
4801                    Isle of Wight Waste Recovery Park
4806                                       Bulwell Energy
4849                   Acharn Forest Killin Biomass Plant
4885                      Knostrop Sewage Treatment Works
4893                         Kincardine Offshore Windfarm
4915            Baldovie Industrial Estate (Forties Road)
4963                                       Bentley Motors
5015                        Ystradffin Hydropower Project
5027                  Swindon Energy Plant (Park Grounds)
5113                                   Cranfield Airfield
5199                              Pilsworth Landfill Site
5250                                   Blackburn Meadows
5252                Dorking Battery Energy Storage System
5309                        Trent Basin Community Battery
875              Wren Power and Pulp (Rivenhall Airfield)
884                                          BHEG Walsall
2034            Hornsea Project Two - Optimus and Breesea
2052                                     Neart na Gaoithe
2062              MacColl Offshore Windfarm (Moray Firth)
2064              Telford Offshore Windfarm (Moray Firth)
2065            Stevenson Offshore Windfarm (Moray Firth)
3631                  Solwaybank Wind Farm (resubmission)
4546                                        Northacre RRC
4792               Fort Industrial Park (Castle Bromwich)
5059                                    Blackbridge TGS 1
Name: Site, Length: 98, dtype: object

In [121]:
cfd

,Site,Capacity (MW),Region,Latitude,Longitude,CHP,Company,Fuel,Type,yearStart,yearEnd
875,Wren Power and Pulp (Rivenhall Airfield),49.75,Eastern,51.853283,0.647025,Yes,Gent Fairhead Environmental Services,Waste,Waste Incinerator,2019,2019
884,BHEG Walsall,27.00,West Midlands,52.610755,-2.009556,No,BH EnergyGap (Walsall),Waste,Advanced Conversion,2019,2019
2034,Hornsea Project Two - Optimus and Breesea,1400.00,Offshore,53.959998,1.539986,n/a,Orsted (formerly Dong Energy),Wind,Offshore Wind,2019,2019
2052,Neart na Gaoithe,450.00,Offshore,56.270000,-2.250001,n/a,EDF Renewables Power,Wind,Offshore Wind,2019,2019
2062,MacColl Offshore Windfarm (Moray Firth),317.00,Offshore,57.967325,-2.790537,n/a,Moray East (formerly MORL)/ EDPR,Wind,Offshore Wind,2019,2019
2064,Telford Offshore Windfarm (Moray Firth),317.00,Offshore,58.211232,-2.790540,n/a,Moray East (formerly MORL)/ EDPR,Wind,Offshore Wind,2019,2019
2065,Stevenson Offshore Windfarm (Moray Firth),316.00,Offshore,58.054625,-3.158579,n/a,Moray East (formerly MORL)/ EDPR,Wind,Offshore Wind,2019,2019
3631,Solwaybank Wind Farm (resubmission),30.00,Scotland,55.100174,-3.107751,n/a,The Renewables Infrastructure Group (TRIG),Wind,Onshore Wind,2019,2019
4546,Northacre RRC,22.00,South West,51.271237,-2.209908,Yes,Northacre Renewable Energy (Hills Group),Waste,Advanced Conversion,2019,2019
4792,Fort Industrial Park (Castle Bromwich),10.20,West Midlands,52.511827,-1.801317,No,Industrial Property Investment Fund,Waste,Advanced Conversion,2019,2019
5059,Blackbridge TGS 1,5.60,East Midlands,52.377865,-0.665447,yes,Think Greenenergy TOPCO (Think Environmental),Waste,Advanced Conversion,2019,2019

In [116]:
df[['Site Name', 'Installed Capacity (MWelec)',
    'Development Status (short)','Technology Type']][(df['Site Name'].str.contains('Wren'))]

4,Site Name,Installed Capacity (MWelec),Development Status (short),Technology Type
875,Wren Power and Pulp (Rivenhall Airfield),49.75,Awaiting Construction,EfW Incineration

In [78]:
#df[(df['Technology Type']=='Wind Onshore')&(df['Development Status (short)']=='Operational')].sort_values(by='Installed Capacity (MWelec)',ascending=False)

In [60]:
# pull CfD register for reference

reg = pd.read_excel('CfD Register as at 25-01-19.xlsx', sheetname='CfD Register as at 250119') 

reg.columns = [
    'Name','ID','Start','Last update','Round','Tech','CHP','Dual?','Whole MW','Capacity (MW)','a','b','c','d','Target date','Window','Expected date','Operator','Country','Address 1','Address 2','Town/City','County','Postcode','Registration','Coordinates','Agreement type','Terms','Ref no','Connection type','Connection','Licence'
,'Metering','Leasing round','Termination date','Comment']

reg = reg[['Name','Tech','CHP','Capacity (MW)','Target date','Expected date','Operator','Coordinates','Termination date']]

reg.sort_values(by='Name',inplace=True)

In [61]:
# list of sites on the CfD register

reg.Name[reg['Termination date'].isnull()].tolist()

[u'Achlachan Wind Farm',
 u'BHEG Walsall',
 u'Bad a Cheo Wind Farm',
 u'Beatrice Phase 1',
 u'Beatrice Phase 2',
 u'Blackbridge TGS 1 Limited',
 u'Brenig Wind Farm - Brenig Wind Limited',
 u'Burbo',
 u'Charity Farm',
 u'Clocaenog Forest Wind Farm',
 u'Coire Na Cloiche Windfarm',
 u'Common Barn Wind Farm',
 u'Dorenell Wind Farm',
 u'Drax 3rd Conversion Unit (Unit 1)',
 u'Dudgeon Phase 1',
 u'Dudgeon Phase 2',
 u'Dudgeon Phase 3',
 u'EA 1, Phase 1',
 u'EA 1, Phase 2',
 u'EA 1, Phase 3',
 u'Energy Works (Hull)',
 u'Enviroparks Hirwaun Generation Site',
 u'Hinkley Point C',
 u'Hornsea Phase 1',
 u'Hornsea Phase 2',
 u'Hornsea Phase 3',
 u'Hornsea Project 2 Phase 1',
 u'Hornsea Project 2 Phase 2',
 u'Hornsea Project 2 Phase 3',
 u'IPIF Fort Industrial REC',
 u'K3 CHP Facility',
 u'Kype Muir Wind Farm',
 u'Lynemouth Power Station',
 u'Middle Muir Wind Farm',
 u'Moor House Wind Farm',
 u'Moray Offshore Windfarm (East) Phase 1',
 u'Moray Offshore Windfarm (East) Phase 2',
 u'Moray Offshore Windfarm (East) Phase 3',
 u'Mynydd Y Gwair Wind Farm',
 u'Nanclach Wind Farm',
 u'Neart na Gaoithe',
 u'Northacre Renewable Energy Centre',
 u'Rebellion',
 u'Sneddon Law Community Wind Farm',
 u'Solwaybank Wind Farm',
 u'Teesside',
 u'Tralorg Wind Farm',
 u'Triangle Farm Solar Park',
 u'Triton Knoll Offshore Wind Farm Phase 1',
 u'Triton Knoll Offshore Wind Farm Phase 2',
 u'Triton Knoll Offshore Wind Farm Phase 3',
 u'Walney Phase 1',
 u'Walney Phase 2',
 u'Wren Power and Pulp']

In [58]:
df[['Site Name', 'Installed Capacity (MWelec)',
    'Development Status (short)']][(df['Site Name'].str.contains('Blackbridge'))]

4,Site Name,Installed Capacity (MWelec),Development Status (short)
4848,Milford Haven/Blackbridge Biomass,49.9,Application Refused
5059,Blackbridge TGS 1,5.6,Abandoned

In [ ]:
# append under construction sites to the existing sites

In [18]:
building

,Site,Capacity (MW),Region,Latitude,Longitude,CHP,Company,Fuel,Type,yearStart,yearEnd
92,Port Clarence Biomass Plant,40.000,North East,54.587779,-1.230733,Yes,Glennmont Partners,Biomass,NaN,2019,2019
95,Merevale & Blyth Estate (Biomass Plant),2.500,West Midlands,52.571658,-1.586704,Yes,Merevale and Blyth Estates,Biomass,NaN,2019,2019
101,Enviroparks Hirwaun Generation Site,20.000,Wales,51.750094,-3.538987,No,Enviroparks Operations,Waste,Advanced Conversion,2019,2019
133,Tees Renewable Energy Plant,299.000,North East,54.602146,-1.161282,Yes,Macquarie/ PKA/ MGT Power,Biomass,NaN,2019,2019
141,Brite Partnership Biomass Plant / Rotherham,41.000,Yorkshire and Humber,53.422585,-1.373370,Yes,Brite Partnership Copenhagen Infrastructure Pa...,Biomass,NaN,2019,2019
144,"Pulse Park, Wellingborough",5.000,East Midlands,52.334377,-0.695258,Yes,Bester Generacion,Biomass,NaN,2019,2019
150,Charlesfield Biomass CHP Plant,10.000,Scotland,55.560490,-2.653289,Yes,Charlesfield First LLP & Biogas Power,Waste,Advanced Conversion,2019,2019
152,Discovery Park,16.000,South East,51.283909,1.345666,Yes,Burmeister & Wain Scandinavian Contractor (BWSC),Biomass,NaN,2019,2019
261,South Kirkby Business Park (Waste AD),6.000,Yorkshire and Humber,53.602657,-1.340697,No,Shanks Group,Waste,Anaerobic Digestion,2019,2019
272,Queen Charlton Quarry Renewable Energy Facilit...,2.200,South West,51.390663,-2.527469,No,Resourceful Earth,Waste,Anaerobic Digestion,2019,2019
320,,1.786,Eastern,51.853283,0.647025,No,Gent Fairhead Environmental Services,Waste,Anaerobic Digestion,2019,2019
332,Charlton Lane Eco Park (Waste AD),1.700,South East,51.404483,-0.440732,No,Surrey County Council,Waste,Anaerobic Digestion,2019,2019
346,Knostrop WWTW AD -,2.400,Yorkshire and Humber,53.779790,-1.507344,No,Kelda Water Services,Waste,Anaerobic Digestion,2019,2019
807,Ratty's Lane Sustainable Enery Facility (ACT),9.600,Eastern,51.767101,0.000279,No,AssestGen Partner / Hoddesdon Energy,Waste,Advanced Conversion,2019,2019
827,Glasgow Renewable Energy and Recycling Centre ...,10.000,Scotland,55.834008,-4.244732,Yes,Viridor,Waste,Advanced Conversion,2019,2019
841,Beddington EfW,26.000,London,51.380516,-0.147205,Yes,Viridor,Waste,Waste Incinerator,2019,2019
844,K3 CHP Facility (Kemsley EfW),45.000,South East,51.366888,0.758870,Yes,E.ON / Wheelabrator Technologies,Waste,Waste Incinerator,2019,2019
854,Canford,10.000,South West,50.770073,-1.952598,No,Syngas Products/ Canford Renewable Energy Ltd,Waste,Advanced Conversion,2019,2019
855,Belfast Harbour Estate,14.850,Northern Ireland,54.619966,-5.880253,Yes,Bombardier,Waste,Waste Incinerator,2019,2019
872,Milton Keynes Waste Recovery Park,7.000,South East,52.067161,-0.814868,No,AmeyCespa,Waste,Advanced Conversion,2019,2019
876,Rookery South,65.000,Eastern,52.075889,-0.526785,No,Veolia/Covanta,Waste,Waste Incinerator,2019,2019
889,Dunbar EfW (previously Oxwellmains EfW),25.600,Scotland,55.972184,-2.465398,No,Viridor,Waste,Waste Incinerator,2019,2019
895,Javelin Park EfW,14.500,South West,51.792505,-2.290690,No,Urbaser Balfour Beatty,Waste,Waste Incinerator,2019,2019
896,Charlton Lane Eco Park (ACT),3.600,South East,51.404483,-0.440732,No,SITA UK,Waste,Advanced Conversion,2019,2019
898,Parc Adfer EfW,16.000,Wales,53.236810,-3.034322,Yes,Wheelabrator,Waste,Waste Incinerator,2019,2019
904,Coatbridge Material Recovery and Renewable Ene...,25.000,Scotland,55.840384,-4.008031,Yes,Golder Associates (UK) Ltd/ Shore Energy,Waste,Advanced Conversion,2019,2019
905,Severn Road Resource Recovery Centre,34.000,South West,51.529307,-2.666667,No,Viridor,Waste,Waste Incinerator,2019,2019
1304,Lodge Farm Solar Farm,5.000,South West,51.205024,-2.505592,n/a,Ecotricity,Solar,NaN,2019,2019
1981,Riverside Sewage Treatment Works Digestion Plant,4.000,London,51.516404,0.185458,No,Thames Water Utilities,Waste,Sewage Sludge Digestion,2019,2019
2051,Beatrice,588.000,Offshore,58.088229,-2.950157,n/a,Scottish & Southern Energy (SSE) / Repsol / CIP,Wind,Offshore Wind,2019,2019
...,...,...,...,...,...,...,...,...,...,...,...
4132,Fosseway Environment Park,1.000,South West,51.349103,-2.397762,Yes,Gazelle Properties,Waste,Anaerobic Digestion,2019,2019
4146,Thames Gateway EfW (Resubmission),19.000,London,51.522878,0.137692,Yes,Thames Gateway Waste to Energy (Chinook Urban ...,Waste,Advanced Conversion,2019,2019
4233,Millerhill EfW (resubmission),12.500,Scotland,55.923520,-3.084092,No,FCC Environment,Waste,Waste Incinerator,2019,2019
4236,West Holcombe,5.500,South West,51.019241,-3.448188,n/a,Wessex Solar Energy,Solar,NaN,2019,2019
4465,New Road Solar Farm,5.000,Eastern,52.638275,1.197538,n/a,Solar Century/ Bluefield Solar,Solar,NaN,2019,2019
4513,Carn Nicholas Farm,5.000,Wales,51.631888,-3.910868,n/a,Suncredit UK,Solar,NaN,2019,2019
4522,Long Lane Solar Farm (resubmission) / Nottingh...,17.000,East Midlands,53.016669,-1.233450,n/a,Earthworm/ EW Capital,Solar,NaN,2019,2019
4536,Carsebank Farm,5.000,Scotland,56.678495,-2.847125,n/a,Carsebank Solar,Solar,NaN,2019,2019
4542,Pogbie Wind Farm,4.800,Scotland,55.839451,-2.842101,n/a,Mongoose (formerly Energy Law Unlimited/ Pogbi...,Wind,Onshore Wind,2019,2019
4547,Arkleby Mill,1.000,North West,54.751020,-3.332545,No,Mssrs R Miller Ltd,Waste,Anaerobic Digestion,2019,2019
4554,Bromham House Farm,1.500,South West,51.391747,-2.037333,No,A J Butler & Sons Ltd,Waste,Anaerobic Digestion,2019,2019
4572,Gameslack Farm (resubmission),17.500,Yorkshire and Humber,54.026515,-0.607123,No,East Yorkshire Power,Biomass,NaN,2019,2019
4598,Morayhill AD,2.000,Scotland,57.518181,-4.088863,No,Morayhill,Waste,Anaerobic Digestion,2019,2019
4637,Langdon Mill,1.000,Wales,51.734446,-4.773523,Yes,Langdon Enterprises,Waste,Anaerobic Digestion,2019,2019
4638,Willand AD,2.000,South West,50.892268,-3.380104,Yes,Greener for Life Energy,Waste,Anaerobic Digestion,2019,2019
4755,Parkhill Solar Farm,4.990,Scotland,56.603761,-2.585954,n/a,Lark Energy,Solar,NaN,2019,2019
4801,Isle of Wight Waste Recovery Park,3.300,South East,50.704964,-1.333946,No,AmeyCespa,Waste,Advanced Conversion,2019,2019
4806,Bulwell Energy,29.500,East Midlands,53.010700,-1.214150,No,Chinook Sciences,Waste,Advanced Conversion,2019,2019
4849,Acharn Forest Killin Biomass Plant,5.600,Scotland,56.452852,-4.334229,Yes,Northern Energy Developments,Biomass,NaN,2019,2019
4885,Knostrop Sewage Treatment Works,4.000,Yorkshire and Humber,53.781457,-1.491222,Yes,Yorkshire Water,Waste,Anaerobic Digestion,2019,2019
4893,Kincardine Offshore Windfarm,50.000,Offshore,56.997280,-1.873801,n/a,Kincardine Offshore Wind,Wind,Offshore Wind,2019,2019
4915,Baldovie Industrial Estate (Forties Road),10.000,Scotland,56.484654,-2.901743,Yes,MVV Environment,Waste,Waste Incinerator,2019,2019
4963,Bentley Motors,2.900,North West,53.105897,-2.472238,n/a,Bentley Motors,Solar,NaN,2019,2019
5015,Ystradffin Hydropower Project,1.800,Wales,52.097768,-3.788271,n/a,Hydro Electric Development,Hydro,Small Hydro,2019,2019
5027,Swindon Energy Plant (Park Grounds),6.000,South West,51.554737,-1.927589,Yes,Crapper and Sons Landfill,Waste,Advanced Conversion,2019,2019
5113,Cranfield Airfield,1.000,Eastern,52.067195,-0.612024,n/a,Cranfield Univsersity,Solar,NaN,2019,2019
5199,Pilsworth Landfill Site,5.000,North West,53.577067,-2.269889,n/a,Viridor/Highview Power Storage,NaN,NaN,2019,2019
5250,Blackburn Meadows,10.000,Yorkshire and Humber,53.420135,-1.398460,n/a,E.On,Storage,Battery,2019,2019
5252,Dorking Battery Energy Storage System,6.000,South East,51.230436,-0.354811,n/a,Grid Battery Storage (GBSL),Storage,Battery,2019,2019
5309,Trent Basin Community Battery,0.500,East Midlands,52.943351,-1.122957,n/a,EvoEnergy,Storage,Battery,2019,2019

In [129]:
df[[
    'Site Name', 'Installed Capacity (MWelec)', 'Technology Type',
    'Planning Permission Granted', 'Planning Permission Expired',
    'Development Status'
]][df['Development Status (short)'] == 'Awaiting Construction'].sort_values(
    by='Installed Capacity (MWelec)', ascending=False)

4,Site Name,Installed Capacity (MWelec),Technology Type,Planning Permission Granted,Planning Permission Expired,Development Status
2069,Dogger Bank Creyke Beck A & B,2400.0,Wind Offshore,2015-02-17 00:00:00,2020-03-11 00:00:00,Planning Permission Granted
2034,Hornsea Project Two - Optimus and Breesea,1400.0,Wind Offshore,2016-08-16 00:00:00,NaN,Planning Permission Granted
2011,East Anglia 3,1200.0,Wind Offshore,2017-08-07 00:00:00,NaN,Planning Permission Granted
2048,Dogger Bank Teesside A,1200.0,Wind Offshore,2015-08-05 00:00:00,NaN,Planning Permission Granted
5095,Sofia (Dogger Bank Teesside B),1200.0,Wind Offshore,2015-08-05 00:00:00,NaN,Planning Permission Granted
2060,Triton Knoll,860.0,Wind Offshore,2013-07-11 00:00:00,NaN,Planning Permission Granted
2057,Inch Cape,784.0,Wind Offshore,2017-05-16 00:00:00,NaN,Planning Permission Granted
5225,Coire Glas - Phase I,600.0,Pumped Storage Hydroelectricity,2013-12-13 00:00:00,NaN,Planning Permission Granted
2068,Seagreen Bravo,525.0,Wind Offshore,2017-05-16 00:00:00,NaN,Planning Permission Granted
2059,Seagreen Alpha,525.0,Wind Offshore,2017-05-16 00:00:00,NaN,Planning Permission Granted
2052,Neart na Gaoithe,450.0,Wind Offshore,2017-05-16 00:00:00,NaN,Planning Permission Granted
5226,Glenmuckloch,400.0,Pumped Storage Hydroelectricity,2016-11-29 00:00:00,NaN,Planning Permission Granted
3788,Viking Wind Farm,370.0,Wind Onshore,2012-04-04 00:00:00,NaN,Planning Permission Granted
1998,Swansea Bay Tidal Lagoon,320.0,Tidal Barrage and Tidal Stream,2015-06-09 00:00:00,2020-06-09 00:00:00,Planning Permission Granted
2062,MacColl Offshore Windfarm (Moray Firth),317.0,Wind Offshore,2014-03-19 00:00:00,NaN,Planning Permission Granted
2064,Telford Offshore Windfarm (Moray Firth),317.0,Wind Offshore,2014-03-19 00:00:00,NaN,Planning Permission Granted
2065,Stevenson Offshore Windfarm (Moray Firth),316.0,Wind Offshore,2014-03-19 00:00:00,NaN,Planning Permission Granted
169,Anglesey Biomass Power Station,299.0,Biomass (dedicated),2011-09-16 00:00:00,NaN,Planning Permission Granted
5249,Culham Science Centre,250.0,Battery,2016-11-15 00:00:00,2019-11-15 00:00:00,Planning Permission Granted
3602,Stornoway Wind Farm project (was Lewis Wind Fa...,180.0,Wind Onshore,2012-09-07 00:00:00,NaN,Planning Permission Granted
3755,South Kyle Wind Farm,170.0,Wind Onshore,2017-06-30 00:00:00,2022-06-30 00:00:00,Appeal Granted
75,Rosyth,120.0,Biomass (dedicated),2014-01-24 00:00:00,2019-01-24 00:00:00,Planning Permission Granted
3692,Uisenis/Eishken (Muaitheabhal) Wind Farm,118.8,Wind Onshore,2010-01-14 00:00:00,NaN,Planning Permission Granted
3603,Strathy South,117.0,Wind Onshore,2018-04-27 00:00:00,NaN,Appeal Granted
3190,Llandinam Windfarm Repowering and Extension,102.0,Wind Onshore,2015-09-07 00:00:00,NaN,Planning Permission Granted
5355,Tilbury Energy Centre,100.0,Battery,2018-03-09 00:00:00,NaN,Planning Permission Granted
5223,Glyn Rhonwy (larger version),99.9,Pumped Storage Hydroelectricity,2017-03-08 00:00:00,NaN,Planning Permission Granted
3771,Lethans Wind Farm,88.0,Wind Onshore,2018-03-23 00:00:00,2021-03-23 00:00:00,Planning Permission Granted
76,Forth Ports Ltd 2 (Grangemouth),85.0,Biomass (dedicated),2013-06-03 00:00:00,NaN,Planning Permission Granted
4066,Inner Sound Phase 1B/1C (MeyGen),80.0,Tidal Barrage and Tidal Stream,2013-09-16 00:00:00,NaN,Planning Permission Granted
...,...,...,...,...,...,...
5298,Westfield Restoration and Regeneration Project,NaN,Battery,2018-08-15 00:00:00,NaN,Planning Permission Granted
5299,Oxford Road,NaN,Battery,2016-11-03 00:00:00,NaN,Planning Permission Granted
5305,Whitson Electricity Substation,NaN,Battery,2018-11-08 00:00:00,2021-11-08 00:00:00,Planning Permission Granted
5311,Radford Solar Farm - energy storage,NaN,Battery,2017-08-09 00:00:00,2020-08-09 00:00:00,Planning Permission Granted
5312,Netherton Electricity Storage Facility,NaN,Battery,2017-11-07 00:00:00,2022-11-07 00:00:00,Planning Permission Granted
5315,Stony Energy Storage Facility,NaN,Battery,2017-10-12 00:00:00,NaN,Planning Permission Granted
5318,Southall Lane Waste Depot,NaN,Battery,2017-10-06 00:00:00,2020-10-05 00:00:00,Planning Permission Granted
5332,Beveridge Lane Battery Storage,NaN,Battery,2018-10-16 00:00:00,2021-10-16 00:00:00,Planning Permission Granted
5334,"Charleywood Road, Knowsley Industrial Park",NaN,Battery,2017-12-21 00:00:00,NaN,Planning Permission Granted
5345,Land to the E/O Lords Cottage,NaN,Battery,2018-07-31 00:00:00,NaN,Planning Permission Granted
5349,Peel Road Energy Centre,NaN,Battery,2018-06-04 00:00:00,NaN,Appeal Granted
5354,Portadown Road,NaN,Battery,2018-09-21 00:00:00,2023-09-20 00:00:00,Planning Permission Granted
5357,Dungannon Energy Storage System,NaN,Battery,2018-10-08 00:00:00,2023-10-07 00:00:00,Planning Permission Granted
5359,Elland Storage Project,NaN,Battery,2018-06-01 00:00:00,NaN,Planning Permission Granted
5361,Meadow Lane Park and Ride,NaN,Battery,2017-07-06 00:00:00,NaN,Planning Permission Granted
5372,Gloucestershire Science and Technology Park,NaN,Battery,2018-04-03 00:00:00,NaN,Planning Permission Granted
5375,Burnley Road,NaN,Battery,2018-05-25 00:00:00,NaN,Planning Permission Granted
5376,Kilshaw Street,NaN,Battery,2018-02-09 00:00:00,NaN,Planning Permission Granted
5380,Church Farm,NaN,Battery,2018-01-08 00:00:00,NaN,Planning Permission Granted
5388,Hill Hall,NaN,Battery,2017-12-22 00:00:00,NaN,Planning Permission Granted
5392,Kiln Lane Industrial Estate,NaN,Battery,2017-12-21 00:00:00,NaN,Planning Permission Granted
5402,Sparsholt college,NaN,Battery,2017-12-08 00:00:00,NaN,Planning Permission Granted
5403,SPEN Bonnybridge substation,NaN,Battery,2017-12-08 00:00:00,NaN,Planning Permission Granted
5404,Bochum Parkway,NaN,Battery,2017-11-30 00:00:00,NaN,Planning Permission Granted
5413,Mill Cottage,NaN,Battery,2017-10-11 00:00:00,NaN,Planning Permission Granted
5417,"Land SE of, Spectrum Business Park",NaN,Battery,2017-10-04 00:00:00,NaN,Planning Permission Granted
5423,Land SW of Shilton Cottage,NaN,Battery,2018-10-25 00:00:00,NaN,Planning Permission Granted
5427,Land Adj Harmer Warren Quarry,NaN,Battery,2018-02-13 00:00:00,NaN,Planning Permission Granted
5433,North-East of Spitfire Way - GCP,NaN,Battery,2017-11-24 00:00:00,NaN,Planning Permission Granted
5434,Fideoak Mills,NaN,Battery,2017-02-23 00:00:00,NaN,Planning Permission Granted

In [132]:
df[[
    'Site Name', 'Installed Capacity (MWelec)', 'Technology Type',
    'Planning Permission Granted', 'Planning Permission Expired',
    'Development Status'
]][df['Development Status (short)'] == 'Awaiting Construction'].pivot_table(index='Technology Type',values='Installed Capacity (MWelec)',aggfunc='sum').sort_values(by='Installed Capacity (MWelec)',ascending=False)

4                                 Installed Capacity (MWelec)
Technology Type
Wind Offshore                                       11516.000
Wind Onshore                                         4040.300
Battery                                              2671.039
Solar Photovoltaics                                  1710.278
Pumped Storage Hydroelectricity                      1149.800
Biomass (dedicated)                                   771.400
EfW Incineration                                      633.350
Advanced Conversion Technologies                      598.990
Tidal Barrage and Tidal Stream                        484.700
Shoreline Wave                                         50.000
Anaerobic Digestion                                    44.450
Small Hydro                                            20.180
Hot Dry Rocks (HDR)                                     7.000
Large Hydro                                             5.000
Landfill Gas                                            3.000
Sewage Sludge Digestion                                 1.100

In [119]:
df['CfD Capacity (MW)'].replace('n/a',np.nan,inplace=True)
df['CfD Capacity (MW)'][(df['Development Status']=='Planning Permission Granted')].sum()

523.75

4223.426

In [101]:
df.columns

Index([                             u'Old Ref ID',
                                        u'Ref ID',
              u'Record Last Updated (dd/mm/yyyy)',
                       u'Operator (or Applicant)',
                                     u'Site Name',
                               u'Technology Type',
                                  u'Storage Type',
               u'Storage Co-location REPD Ref ID',
                   u'Installed Capacity (MWelec)',
                                   u'CHP Enabled',
                          u'RO Banding (ROC/MWh)',
                            u'FiT Tariff (p/kWh)',
                             u'CfD Capacity (MW)',
                         u'Turbine Capacity (MW)',
                               u'No. of Turbines',
                        u'Height of Turbines (m)',
                       u'Mounting Type for Solar',
                            u'Development Status',
                    u'Development Status (short)',
                                       u'Address',
                                        u'County',
                                        u'Region',
                                       u'Country',
                                     u'Post Code',
                                  u'X-coordinate',
                                  u'Y-coordinate',
                            u'Planning Authority',
                u'Planning Application Reference',
                              u'Appeal Reference',
                  u'Secretary of State Reference',
       u'Type of Secretary of State Intervention',
                               u'Judicial Review',
                           u'Offshore Wind Round',
                u'Planning Application Submitted',
                u'Planning Application Withdrawn',
                   u'Planning Permission Refused',
                                 u'Appeal Lodged',
                              u'Appeal Withdrawn',
                                u'Appeal Refused',
                                u'Appeal Granted',
                   u'Planning Permission Granted',
               u'Secretary of State - Intervened',
                  u'Secretary of State - Refusal',
                  u'Secretary of State - Granted',
                   u'Planning Permission Expired',
                            u'Under Construction',
                                   u'Operational',
                                           u'lat',
                                           u'lon'],
      dtype='object', name=4)

In [95]:
# 10 largest renewable power plants

operational.sort_values(by='Capacity (MW)',ascending=False).head(10)

,Site,Capacity (MW),Region,Latitude,Longitude,Year Open,CHP,Company,Fuel,Type,yearStart,yearEnd
5129,Drax Biomass,2580.0,Yorkshire and Humber,53.735589,-0.991097,2018,n/a,Drax Power,Biomass,NaN,2018,2018
154,Drax Biomass,1935.0,Yorkshire and Humber,53.735589,-0.991097,2017,No,Drax Power,Biomass,NaN,2017,2017
5195,Dinorwig,1728.0,Wales,53.118607,-4.113893,1983,n/a,First Hydro Company,Storage,Pumped Hydro,2004,2018
170,Drax Biomass,1290.0,Yorkshire and Humber,53.735589,-0.991097,2014,No,Drax Power,Biomass,NaN,2014,2016
2061,Walney 3,660.0,Offshore,54.089995,-3.740011,2018,n/a,Orsted (formerly Dong Energy),Wind,Offshore Wind,2018,2018
153,Drax Biomass,645.0,Yorkshire and Humber,53.735589,-0.991097,2013,No,Drax Power,Biomass,Co-firing,2013,2013
2042,London Array Phase 1,630.0,Offshore,51.621679,1.495832,2013,n/a,Siemens Gamesa Renewable Energy,Wind,Offshore Wind,2013,2018
2070,Gwynt y Mor,576.0,Offshore,53.454003,-3.626649,2015,n/a,RWE,Wind,Offshore Wind,2015,2018
2041,Greater Gabbard Wind Farm,504.0,Offshore,51.917645,1.928420,2012,n/a,Airtricity / Fluor Ltd,Wind,Offshore Wind,2012,2018
5197,Cruachan,440.0,Scotland,56.411152,-5.113451,1966,n/a,Scottish Power,Storage,Pumped Hydro,2004,2018

In [ ]:
# change names to match the conventional plants data
# enter yearStart and yearEnd
# do something for contracted not built capacity / under construction stuff

In [60]:
operational['Technology Type'].unique()

array([u'Biomass (dedicated)', u'Advanced Conversion Technologies',
       u'Anaerobic Digestion', u'EfW Incineration', u'Biomass (co-firing)',
       u'Large Hydro', u'Small Hydro', u'Landfill Gas',
       u'Solar Photovoltaics', u'Sewage Sludge Digestion',
       u'Tidal Barrage and Tidal Stream', u'Shoreline Wave',
       u'Wind Offshore', u'Wind Onshore',
       u'Pumped Storage Hydroelectricity', u'Battery', u'Flywheels'], dtype=object)

In [58]:
df.columns

Index([                             u'Old Ref ID',
                                        u'Ref ID',
              u'Record Last Updated (dd/mm/yyyy)',
                       u'Operator (or Applicant)',
                                     u'Site Name',
                               u'Technology Type',
                                  u'Storage Type',
               u'Storage Co-location REPD Ref ID',
                   u'Installed Capacity (MWelec)',
                                   u'CHP Enabled',
                          u'RO Banding (ROC/MWh)',
                            u'FiT Tariff (p/kWh)',
                             u'CfD Capacity (MW)',
                         u'Turbine Capacity (MW)',
                               u'No. of Turbines',
                        u'Height of Turbines (m)',
                       u'Mounting Type for Solar',
                            u'Development Status',
                    u'Development Status (short)',
                                       u'Address',
                                        u'County',
                                        u'Region',
                                       u'Country',
                                     u'Post Code',
                                  u'X-coordinate',
                                  u'Y-coordinate',
                            u'Planning Authority',
                u'Planning Application Reference',
                              u'Appeal Reference',
                  u'Secretary of State Reference',
       u'Type of Secretary of State Intervention',
                               u'Judicial Review',
                           u'Offshore Wind Round',
                u'Planning Application Submitted',
                u'Planning Application Withdrawn',
                   u'Planning Permission Refused',
                                 u'Appeal Lodged',
                              u'Appeal Withdrawn',
                                u'Appeal Refused',
                                u'Appeal Granted',
                   u'Planning Permission Granted',
               u'Secretary of State - Intervened',
                  u'Secretary of State - Refusal',
                  u'Secretary of State - Granted',
                   u'Planning Permission Expired',
                            u'Under Construction',
                                   u'Operational',
                                           u'lat',
                                           u'lon'],
      dtype='object', name=4)

In [57]:
#operational['Development Status'].unique()
operational.head()

4,Site Name,Technology Type,Installed Capacity (MWelec),Region,lat,lon,Year Open
18,Chilton Energy Plant,Biomass (dedicated),18.0,North East,54.668027,-1.566632,2012
21,Double H Nurseries Biomass Plant,Biomass (dedicated),1.5,South East,50.750782,-1.678119,2012
22,Newry Biomass Phase 1 (Gasification),Advanced Conversion Technologies,2.0,Northern Ireland,54.217507,-6.336669,2012
23,Beckton STW Biodiesel Power Plant,Biomass (dedicated),8.0,London,51.517777,0.093461,2010
24,Buslingthorpe Power Station (Leeds North),Biomass (dedicated),2.0,Yorkshire and Humber,53.814327,-1.542615,2011

In [80]:
#df['X-coordinate'] = pd.to_numeric(df['X-coordinate'],errors='coerce')
df["X-coordinate"] = df["X-coordinate"].astype(float)

In [107]:
#df["X-coordinate"].loc[df["X-coordinate"] == NaN]
df[['X-coordinate','Y-coordinate','Installed Capacity (MWelec)','Development Status','Site Name']].loc[df['X-coordinate'].isnull()]
df[['Installed Capacity (MWelec)']].loc[(df['X-coordinate'].isnull())&(df['Development Status']=='Operational')].sum()

4
Installed Capacity (MWelec)    0.0
dtype: float64

In [116]:
df[['X-coordinate','Y-coordinate','lat','lon']].loc[[1200,1201,1202,5179]]

4     X-coordinate  Y-coordinate        lat        lon
1200      464288.0      405319.0  53.540590  -1.031381
1201     -477441.0      481803.0  53.492552 -15.262149
1202      538495.0      348945.0  53.019888   0.063251
5179      147788.0      570314.0  54.963451  -5.941645

In [72]:
df[['Development Status','Site Name','Installed Capacity (MWelec)']].loc[[5176,5177,5178,5179]]

4,Development Status,Site Name,Installed Capacity (MWelec)
5176,Planning Application Submitted,Aviva Headquarters Perth,0.85
5177,Planning Application Submitted,Whapps Town Windfarm (Resubmission),9.2
5178,Appeal Lodged,Lands 260m SW of 76 Strabane Road,0.25
5179,Appeal Lodged,402 metres NE of 45 Dickeystown Road,0.25

In [24]:
df.columns.tolist()

[u'Old Ref ID',
 u'Ref ID',
 u'Record Last Updated (dd/mm/yyyy)',
 u'Operator (or Applicant)',
 u'Site Name',
 u'Technology Type',
 u'Storage Type',
 u'Storage Co-location REPD Ref ID',
 u'Installed Capacity (MWelec)',
 u'CHP Enabled',
 u'RO Banding (ROC/MWh)',
 u'FiT Tariff (p/kWh)',
 u'CfD Capacity (MW)',
 u'Turbine Capacity (MW)',
 u'No. of Turbines',
 u'Height of Turbines (m)',
 u'Mounting Type for Solar',
 u'Development Status',
 u'Development Status (short)',
 u'Address',
 u'County',
 u'Region',
 u'Country',
 u'Post Code',
 u'X-coordinate',
 u'Y-coordinate',
 u'Planning Authority',
 u'Planning Application Reference',
 u'Appeal Reference',
 u'Secretary of State Reference',
 u'Type of Secretary of State Intervention',
 u'Judicial Review',
 u'Offshore Wind Round',
 u'Planning Application Submitted',
 u'Planning Application Withdrawn',
 u'Planning Permission Refused',
 u'Appeal Lodged',
 u'Appeal Withdrawn',
 u'Appeal Refused',
 u'Appeal Granted',
 u'Planning Permission Granted',
 u'Secretary of State - Intervened',
 u'Secretary of State - Refusal',
 u'Secretary of State - Granted',
 u'Planning Permission Expired',
 u'Under Construction',
 u'Operational']

In [6]:
# df.dtypes
print df['Record Last Updated (dd/mm/yyyy)'].tail(20)

5432    2018-11-27 00:00:00
5433    2018-11-27 00:00:00
5434    2018-11-28 00:00:00
5435    2018-11-28 00:00:00
5436    2018-11-29 00:00:00
5437    2019-01-02 00:00:00
5438    2018-12-04 00:00:00
5439    2018-12-06 00:00:00
5440    2018-12-06 00:00:00
5441    2018-12-06 00:00:00
5442    2018-12-06 00:00:00
5443    2018-12-06 00:00:00
5444    2018-12-06 00:00:00
5445    2018-12-06 00:00:00
5446    2018-12-06 00:00:00
5447    2018-12-06 00:00:00
5448    2018-12-20 00:00:00
5449    2018-12-20 00:00:00
5450    2018-12-20 00:00:00
5451    2019-01-03 00:00:00
Name: Record Last Updated (dd/mm/yyyy), dtype: object

In [7]:
# drop non-data rows and columns

df.drop(df.index[:5], inplace=True)
df.columns.values[0] = 'blank1'
df.columns.values[1] = 'blank2'
# drop first two columns that are blank
df.drop(['blank1','blank2'], axis=1, inplace=True)

#df.head()

4,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Storage Type,Storage Co-location REPD Ref ID,Installed Capacity (MWelec),CHP Enabled,...,Appeal Withdrawn,Appeal Refused,Appeal Granted,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational
10,70700000,6,2004-08-13 00:00:00,Incetec / Border Biofuels,Kingmoor Marshalling Yard,Biomass (dedicated),NaN,NaN,20,No,...,NaN,NaN,NaN,2000-03-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
11,9162000,7,2004-11-29 00:00:00,NOVERA,North Wiltshire Biomass Power Plant,Biomass (dedicated),NaN,NaN,5.528,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,100640000,8,2003-12-23 00:00:00,Private Developer,Newbridge Power Station,Biomass (dedicated),NaN,NaN,15,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,11065000,9,2004-08-30 00:00:00,Agricultural Energy Company Limited,Poole Biomass Plant,Biomass (dedicated),NaN,NaN,10.93,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,12076000,10,2012-01-04 00:00:00,Yorkshire Environmental,Eggborough Biomass Power Station,Advanced Conversion Technologies,NaN,NaN,10.62,No,...,NaN,NaN,NaN,1997-01-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#print df['X-coordinate'].loc[df['X-coordinate'].isna()]
#print df.loc[1301]
df['X-coordinate'].head()

10    337200
11    411500
12    302400
13    314900
14    457200
Name: X-coordinate, dtype: object

In [56]:
# print df.loc[np.isnan(df['X-coordinate']), 'Installed Capacity (MWelec)']

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [6]:
# fill empty x and y coords with locations as follows:
df['X-coordinate'] = df['X-coordinate'].fillna(-477441)
df['Y-coordinate'] = df['Y-coordinate'].fillna(481803)
print df[['X-coordinate','Y-coordinate']].loc[[1301,1302]]

4    X-coordinate  Y-coordinate
1301       359296      288893.0
1302       182941       59990.0

In [23]:
#df[['Y-coordinate']].isnull()*53.492548

In [81]:
def proj_transform(df):
    bng = pyproj.Proj(init='epsg:27700')
    wgs84 = pyproj.Proj(init='epsg:4326')
    lon,lat = pyproj.transform(bng,wgs84, df['X-coordinate'], df['Y-coordinate'])    
    df['lat'] = lat
    df['lon'] = lon
    return df

df = df.apply(proj_transform, axis=1)
print df[['X-coordinate', 'Y-coordinate','lat','lon']].loc[[1301,1302]]

RuntimeError: ('non-convergent inverse meridional dist', u'occurred at index 1201')

In [25]:
summary = df.groupby(['Technology Type','Development Status']).sum().reset_index()
summary[['Technology Type','Development Status', 'Installed Capacity (MWelec)']].to_csv('summary.csv')
print summary[['Technology Type','Development Status', 'Installed Capacity (MWelec)']].tail(10)

4   Technology Type               Development Status  \
118    Wind Onshore                   Decommissioned
119    Wind Onshore                      Operational
120    Wind Onshore   Planning Application Submitted
121    Wind Onshore   Planning Application Withdrawn
122    Wind Onshore      Planning Permission Expired
123    Wind Onshore      Planning Permission Granted
124    Wind Onshore      Planning Permission Refused
125    Wind Onshore  Secretary of State - Intervened
126    Wind Onshore     Secretary of State - Refusal
127    Wind Onshore               Under Construction

4    Installed Capacity (MWelec)
118                      38.0500
119                   12151.4920
120                    2180.3500
121                    6269.4018
122                      73.4000
123                    2467.5500
124                    6266.0114
125                      40.0400
126                     189.4000
127                    1217.7500

In [26]:
pivot = df.pivot_table(index='Development Status', columns='Technology Type', values='Installed Capacity (MWelec)', aggfunc='sum')
print pivot

Technology Type                  Advanced Conversion Technologies  \
Development Status
Abandoned                                                  294.62
Appeal Granted                                              11.00
Appeal Lodged                                               12.00
Appeal Refused                                              16.00
Appeal Withdrawn                                            31.00
Decommissioned                                               9.20
No Application Required                                       NaN
Operational                                                 70.30
Planning Application Submitted                              81.00
Planning Application Withdrawn                             242.80
Planning Permission Expired                                  9.00
Planning Permission Granted                                645.99
Planning Permission Refused                                 74.60
Planning permission granted                                   NaN
Secretary of State - Granted                                 9.60
Secretary of State - Intervened                               NaN
Secretary of State - Refusal                                  NaN
Under Construction                                         235.50

Technology Type                  Anaerobic Digestion  Biomass (co-firing)  \
Development Status
Abandoned                                     55.950                  NaN
Appeal Granted                                 7.700                  NaN
Appeal Lodged                                  3.000                  NaN
Appeal Refused                                 5.500                  NaN
Appeal Withdrawn                               2.000                  NaN
Decommissioned                                   NaN                  NaN
No Application Required                          NaN                  NaN
Operational                                  273.524                698.0
Planning Application Submitted                 3.000                  NaN
Planning Application Withdrawn                36.400                170.0
Planning Permission Expired                   34.950                  NaN
Planning Permission Granted                   45.700                  NaN
Planning Permission Refused                   46.700                  NaN
Planning permission granted                      NaN                  NaN
Secretary of State - Granted                     NaN                  NaN
Secretary of State - Intervened                  NaN                  NaN
Secretary of State - Refusal                     NaN                  NaN
Under Construction                            32.186                  NaN

Technology Type                  Biomass (dedicated)  EfW Incineration  \
Development Status
Abandoned                                   2665.150           198.600
Appeal Granted                                44.000             5.000
Appeal Lodged                                    NaN             4.000
Appeal Refused                                80.900            35.500
Appeal Withdrawn                              40.000            54.000
Decommissioned                               740.000             2.500
No Application Required                      420.000            27.800
Operational                                 2193.399          1074.500
Planning Application Submitted                12.500           155.400
Planning Application Withdrawn               605.815           186.547
Planning Permission Expired                   73.500            38.000
Planning Permission Granted                 1012.100           669.050
Planning Permission Refused                  211.948           312.250
Planning permission granted                      NaN               NaN
Secretary of State - Granted                     NaN               NaN
Secretary of State - Intervened                  NaN               NaN
Secretary of State - Refusal                     NaN            30.000
Under Construction                           536.200           273.650

Technology Type                  Hot Dry Rocks (HDR)  Landfill Gas  \
Development Status
Abandoned                                        NaN        10.370
Appeal Granted                                   NaN           NaN
Appeal Lodged                                    NaN           NaN
Appeal Refused                                   NaN           NaN
Appeal Withdrawn                                 NaN           NaN
Decommissioned                                   NaN         2.972
No Application Required                          NaN           NaN
Operational                                      NaN       746.875
Planning Application Submitted                   NaN           NaN
Planning Application Withdrawn                   NaN         9.365
Planning Permission Expired                      NaN         1.000
Planning Permission Granted                     10.0         4.260
Planning Permission Refused                      NaN         2.000
Planning permission granted                      NaN           NaN
Secretary of State - Granted                     NaN           NaN
Secretary of State - Intervened                  NaN           NaN
Secretary of State - Refusal                     NaN           NaN
Under Construction                               NaN           NaN

Technology Type                  Large Hydro  Sewage Sludge Digestion  \
Development Status
Abandoned                               16.5                      NaN
Appeal Granted                           NaN                      NaN
Appeal Lodged                            NaN                      NaN
Appeal Refused                           NaN                      NaN
Appeal Withdrawn                         NaN                      NaN
Decommissioned                           NaN                      NaN
No Application Required                  NaN                      NaN
Operational                            369.6                    45.06
Planning Application Submitted           NaN                      NaN
Planning Application Withdrawn          15.7                      NaN
Planning Permission Expired              NaN                      NaN
Planning Permission Granted              5.0                     1.10
Planning Permission Refused              5.0                      NaN
Planning permission granted              NaN                      NaN
Secretary of State - Granted             NaN                      NaN
Secretary of State - Intervened          NaN                      NaN
Secretary of State - Refusal             NaN                      NaN
Under Construction                       NaN                     4.00

Technology Type                  Shoreline Wave  Small Hydro  \
Development Status
Abandoned                                   4.0        3.700
Appeal Granted                              NaN          NaN
Appeal Lodged                               NaN          NaN
Appeal Refused                              NaN          NaN
Appeal Withdrawn                            NaN          NaN
Decommissioned                              1.0          NaN
No Application Required                     NaN          NaN
Operational                                24.0      138.632
Planning Application Submitted              7.0        8.280
Planning Application Withdrawn              3.0       14.600
Planning Permission Expired                 NaN        2.000
Planning Permission Granted                50.0       11.500
Planning Permission Refused                 NaN       12.820
Planning permission granted                 NaN          NaN
Secretary of State - Granted                NaN          NaN
Secretary of State - Intervened             NaN          NaN
Secretary of State - Refusal                NaN          NaN
Under Construction                          NaN        5.000

Technology Type                  Solar Photovoltaics  \
Development Status
Abandoned                                    325.850
Appeal Granted                               215.880
Appeal Lodged                                 67.330
Appeal Refused                              1038.675
Appeal Withdrawn                             109.840
Decommissioned                                   NaN
No Application Required                          NaN
Operational                                 8226.217
Planning Application Submitted               226.871
Planning Application Withdrawn               984.043
Planning Permission Expired                  125.776
Planning Permission Granted                 1902.482
Planning Permission Refused                 1455.722
Planning permission granted                    8.100
Secretary of State - Granted                     NaN
Secretary of State - Intervened               11.720
Secretary of State - Refusal                  43.210
Under Construction                           100.810

Technology Type                  Tidal Barrage and Tidal Stream  \
Development Status
Abandoned                                                  10.0
Appeal Granted                                              NaN
Appeal Lodged                                               NaN
Appeal Refused                                              NaN
Appeal Withdrawn                                            NaN
Decommissioned                                              NaN
No Application Required                                     NaN
Operational                                                14.2
Planning Application Submitted                            300.0
Planning Application Withdrawn                              9.2
Planning Permission Expired                                 NaN
Planning Permission Granted                               446.2
Planning Permission Refused                                 NaN
Planning permission granted                                 NaN
Secretary of State - Granted                               30.0
Secretary of State - Intervened                             NaN
Secretary of State - Refusal                                NaN
Under Construction                                          NaN

Technology Type                  Wind Offshore  Wind Onshore
Development Status
Abandoned                                348.0      617.3120
Appeal Granted                             NaN     1135.4500
Appeal Lodged                              NaN     1665.3500
Appeal Refused                             NaN     3686.2660
Appeal Withdrawn                           NaN      640.5700
Decommissioned                             NaN       38.0500
No Application Required                    NaN           NaN
Operational                             6361.0    12151.4920
Planning Application Submitted             NaN     2180.3500
Planning Application Withdrawn          1592.0     6269.4018
Planning Permission Expired                NaN       73.4000
Planning Permission Granted            12372.4     2467.5500
Planning Permission Refused             1510.0     6266.0114
Planning permission granted                NaN           NaN
Secretary of State - Granted               NaN           NaN
Secretary of State - Intervened            NaN       40.0400
Secretary of State - Refusal               NaN      189.4000
Under Construction                      3242.5     1217.7500

In [40]:
# how many onshore windfarms submitted planning applications after July 2015?
# select onshore windfarms
onwind = df.loc[df['Technology Type'] == 'Wind Onshore']
# select apps submitted after 2015
recent_onwind = onwind.loc[onwind['Planning Application Submitted'].dt.year >= 2015]
recent_onwind = recent_onwind.loc[(recent_onwind['Planning Application Submitted'].dt.month > 7) |
                                   (recent_onwind['Planning Application Submitted'].dt.year > 2015)]
print len(recent_onwind)
print recent_onwind

# get columns headers
# onwind.columns.tolist()

# check how many null values
# print onwind['Planning Application Submitted'].isnull().sum()
# check how many rows
# print len(onwind)

123
4    Old Ref ID Ref ID Record Last Updated (dd/mm/yyyy)  \
2214      AA184   2767              2018-08-20 00:00:00
2250      B0705   2847              2018-02-28 00:00:00
2251      B0710   2848              2017-04-04 00:00:00
2255      B0782   2860              2017-07-28 00:00:00
2653      C2732   3373              2018-08-03 00:00:00
2662      B0801   3387              2018-04-03 00:00:00
2663      C0716   3388              2018-04-30 00:00:00
2695      C1798   3430              2018-06-20 00:00:00
2696      C2520   3431              2016-12-01 00:00:00
2753      AA995   3502              2017-11-30 00:00:00
2767      B0337   3516              2018-09-03 00:00:00
2856      B1321   3629              2018-06-22 00:00:00
3200     IF1375   4003              2018-07-23 00:00:00
3515      C1030   4334              2016-02-05 00:00:00
3595      B1493   4420              2018-09-04 00:00:00
3649      C1581   4487              2017-05-17 00:00:00
3743      AA491   4584              2016-11-30 00:00:00
3768      B0743   4610              2017-05-02 00:00:00
3772      B1290   4615              2018-05-30 00:00:00
3786      B1516   4631              2018-07-05 00:00:00
3787      B1517   4632              2018-02-02 00:00:00
3937        NaN   4810              2017-03-31 00:00:00
3970      B1534   4866              2017-04-27 00:00:00
4048        NaN   4964              2017-02-01 00:00:00
4137        NaN   5122              2018-06-21 00:00:00
4179        NaN   5181              2018-06-01 00:00:00
4184        NaN   5187              2017-12-21 00:00:00
4185        NaN   5188              2018-09-04 00:00:00
4187        NaN   5198              2018-09-04 00:00:00
4312        NaN   5351              2018-06-28 00:00:00
...         ...    ...                              ...
4996        NaN   6343              2018-03-28 00:00:00
4997        NaN   6347              2017-10-04 00:00:00
4998        NaN   6353              2018-08-17 00:00:00
5003        NaN   6363              2017-11-30 00:00:00
5010        NaN   6378              2018-08-29 00:00:00
5011        NaN   6384              2018-08-30 00:00:00
5016        NaN   6398              2018-08-20 00:00:00
5019        NaN   6405              2018-07-05 00:00:00
5020        NaN   6407              2018-04-30 00:00:00
5023        NaN   6414              2018-09-04 00:00:00
5026        NaN   6422              2018-03-28 00:00:00
5027        NaN   6424              2018-08-29 00:00:00
5030        NaN   6436              2017-10-04 00:00:00
5031        NaN   6439              2017-08-30 00:00:00
5033        NaN   6443              2018-04-03 00:00:00
5034        NaN   6444              2018-09-05 00:00:00
5037        NaN   6454              2018-04-27 00:00:00
5043        NaN   6464              2018-06-20 00:00:00
5062        NaN   6509              2018-07-05 00:00:00
5068        NaN   6519              2017-11-30 00:00:00
5075        NaN   6546              2018-02-01 00:00:00
5080        NaN   6562              2018-03-01 00:00:00
5082        NaN   6571              2018-03-01 00:00:00
5083        NaN   6572              2018-03-28 00:00:00
5087        NaN   6590              2018-04-03 00:00:00
5103        NaN   6645              2018-07-03 00:00:00
5104        NaN   6646              2018-07-03 00:00:00
5110        NaN   6664              2018-07-05 00:00:00
5111        NaN   6673              2018-09-03 00:00:00
5118        NaN   6703              2018-09-04 00:00:00

4                               Operator (or Applicant)  \
2214                                Corolis Energy/ ESB
2250                            Brookfield Renewable UK
2251                              Coriolis Energy / ESB
2255                               Green Cat Renewables
2653                                       Wind Harvest
2662                          Scottish Power Renewables
2663                     North British Wind / Invenergy
2695  EDF Energy Renewables (formerly Partnerships f...
2696                                         Ecotricity
2753                                    E.ON Renewables
2767                                    Peel Wind Farms
2856                                           ABO Wind
3200                                     Muirden Energy
3515                                               E.On
3595                                          Infinergy
3649                          Scottish Power Renewables
3743                                    E.ON Renewables
3768                                        PNE Wind UK
3772                              Fred Olsen Renewables
3786                              Fred Olsen Renewables
3787                                    Muirhall Energy
3937                          Scottish Power Renewables
3970                                   Energiekontor UK
4048                              EDF Energy Renewables
4137                                         Ecotricity
4179        Forsa (formerly 2020 Renewables/ Buccleuch)
4184                                The Energy Workshop
4185                                      Hoolan Energy
4187                Hoolan Energy/ Hesta Head Wind Farm
4312                     European Forest Resource Group
...                                                 ...
4996                                  Private Developer
4997                               Barrel Law Windfarm
4998                                  Private Developer
5003                                    Muirhall Energy
5010                                       Sirius Group
5011                      Peel Wind Farms (Peel Energy)
5016                               Green Cat Renewables
5019                                                ESB
5020                              Fred Olsen Renewables
5023                                             Innogy
5026                                        Cleanearth
5027                                          Rigg Wind
5030                                             Tamani
5031                                        ABO Wind NI
5033                                   EnergieKontor UK
5034                                   EnergieKontor UK
5037  Improving New Cumnock and Young Brothers/ Gree...
5043                              EDF Energy Renewables
5062                                   Clean Earth (CE)
5068                             Cardinghill Renewables
5075                                        ABO Wind NI
5080                                                RES
5082                            Sirius Renewable Energy
5083                                     Connaught Wind
5087                                      Element Power
5103                              Velocita/Forsa Energy
5104                                           MPG Wind
5110                               Green Cat Renewables
5111                                           Aquatera
5118                                                ERG

4                                             Site Name Technology Type  \
2214                                Chirmorie Wind Farm    Wind Onshore
2250                             Altercannoch Wind Farm    Wind Onshore
2251                                Lower Alt Wind Farm    Wind Onshore
2255                              Strathallan Wind Farm    Wind Onshore
2653                                  Beinn Mheadhonach    Wind Onshore
2662                    Beinn an Tuirc Windfarm Phase 3    Wind Onshore
2663                                 Balunton Wind Farm    Wind Onshore
2695                                Heathland Wind Farm    Wind Onshore
2696                                Inch Moor Wind Farm    Wind Onshore
2753                                         Enoch Hill    Wind Onshore
2767                               Beaw Field Wind Farm    Wind Onshore
2856                               Green Burn Wind Farm    Wind Onshore
3200                               Cogle Moss Wind Farm    Wind Onshore
3515                               Allt Rubha Wind Farm    Wind Onshore
3595                           Tom Nan Clach (redesign)    Wind Onshore
3649                   Wether Hill WindFarm (extension)    Wind Onshore
3743                                       Strathy Wood    Wind Onshore
3768                                Knockskae Wind Farm    Wind Onshore
3772  Windy Standard III Wind Farm (Brockloch Rig Ph...    Wind Onshore
3786                     Crystal Rig Wind Farm Phase IV    Wind Onshore
3787                                Loganhead Wind Farm    Wind Onshore
3937          Green knowes Windfarm Ext. (resubmission)    Wind Onshore
3970                         Fulbeck Airfield Wind Farm    Wind Onshore
4048                          Fallago Rig 2 (extension)    Wind Onshore
4137                           Upper Sonachan Wind Farm    Wind Onshore
4179    Lowther Hills (North Lowther Energy Initiative)    Wind Onshore
4184         Hill of Lybster (Wind Turbine - Extension)    Wind Onshore
4185                               Costa Head Wind Farm    Wind Onshore
4187                               Hesta Head Wind Farm    Wind Onshore
4312                   Druim Ba Windfarm (resubmission)    Wind Onshore
...                                                 ...             ...
4996                                 Penyrheol Las Farm    Wind Onshore
4997                               Barrel Law Wind Farm    Wind Onshore
4998                       Beltonanean 2 (resubmission)    Wind Onshore
5003                               Priestgill Wind Farm    Wind Onshore
5010                Former Nant-y-Gwyddon Landfill Site    Wind Onshore
5011                                         Mossy Hill    Wind Onshore
5016                                        North Haddo    Wind Onshore
5019                                          Blarghour    Wind Onshore
5020                                       Pauls Hill 2    Wind Onshore
5023                   Ashmark Hill Community Wind Farm    Wind Onshore
5026                                   Graig Fatha Farm    Wind Onshore
5027                                        Southrigg 2    Wind Onshore
5030                                     Greenhill Farm    Wind Onshore
5031               Carnalbanagh Windfarm (Resubmission)    Wind Onshore
5033                          Little Hartfell Wind Farm    Wind Onshore
5034                           Glenshimmeroch Wind Farm    Wind Onshore
5037                                     High Park Farm    Wind Onshore
5043                                   Airigh Wind Farm    Wind Onshore
5062                     Longlands Farm, Rush Wall Lane    Wind Onshore
5068                           Cardinghill Wind Turbine    Wind Onshore
5075                                    Armoy Wind Farm    Wind Onshore
5080                             Dunbeg South Wind Farm    Wind Onshore
5082                        Pen-Y-Fan Industrial Estate    Wind Onshore
5083                                     Connaught Road    Wind Onshore
5087       Twentyshilling Hill Wind Farm (resubmission)    Wind Onshore
5103                      Druim Leathann (resubmission)    Wind Onshore
5104                                      Cloghfin Road    Wind Onshore
5110             Binn Eco Park Wind Farm (resubmission)    Wind Onshore
5111                  Sandwick East Community Wind Farm    Wind Onshore
5118          Sandy Knowe Wind Farm (S.36 resubmission)    Wind Onshore

4    Installed Capacity (MWelec) CHP Enabled RO Banding (ROC/MWh)  \
2214                          76         n/a                  NaN
2250                        27.7         n/a                  NaN
2251                          42         n/a                  NaN
2255                        20.7         n/a                  NaN
2653                           4         n/a                  NaN
2662                          36         n/a                  NaN
2663                          27         n/a                  NaN
2695                        57.8         n/a                  NaN
2696                        51.2         n/a                  NaN
2753                        54.4         n/a                  NaN
2767                        57.8         n/a                  NaN
2856                          33         n/a                  NaN
3200                          36         n/a                  NaN
3515                          27         n/a                  NaN
3595                          39         n/a                  NaN
3649                          22         n/a                  NaN
3743                        59.4         n/a                  NaN
3768                        25.3         n/a                  NaN
3772                        67.5         n/a                  NaN
3786                          48         n/a                  NaN
3787                        25.6         n/a                  NaN
3937                          10         n/a                  0.9
3970                          25         n/a                  0.9
4048                          41         n/a                  0.9
4137                        64.6         n/a                  NaN
4179                         147         n/a                  NaN
4184                         1.5         n/a                  NaN
4185                        20.4         n/a                  NaN
4187                          20         n/a                  NaN
4312                          30         n/a                  NaN
...                          ...         ...                  ...
4996                           1         n/a                  NaN
4997                        24.5         n/a                  NaN
4998                         2.3         n/a                  NaN
5003                        22.4         n/a                  NaN
5010                         1.5         n/a                  NaN
5011                        46.8         NaN                  NaN
5016                         1.6         n/a                  NaN
5019                          60         n/a                  NaN
5020                          28         n/a                  NaN
5023                          21         NaN                  NaN
5026                         2.5         n/a                  NaN
5027                         1.5         n/a                  NaN
5030                           2         n/a                  NaN
5031                          21         n/a                  NaN
5033                          36         n/a                  NaN
5034                          36         n/a                  NaN
5037                         NaN         n/a                  NaN
5043                        58.8         n/a                  NaN
5062                         3.5         n/a                  NaN
5068                         1.5         n/a                  NaN
5075                        19.8         n/a                  NaN
5080                        29.7         n/a                  NaN
5082                        1.75         n/a                  NaN
5083                         1.6         n/a                  NaN
5087                          36         n/a                  NaN
5103                        46.2         n/a                  NaN
5104                         4.8         n/a                  NaN
5110                          10         n/a                  NaN
5111                          50         n/a                  NaN
5118                        81.6         NaN                  NaN

4    FiT Tariff (p/kWh)     ...     Appeal Withdrawn       Appeal Refused  \
2214                NaN     ...                  NaN                  NaN
2250                NaN     ...                  NaN                  NaN
2251                NaN     ...                  NaN                  NaN
2255                NaN     ...                  NaN                  NaN
2653                NaN     ...                  NaN                  NaN
2662                NaN     ...                  NaN                  NaN
2663                NaN     ...                  NaN                  NaN
2695                NaN     ...                  NaN                  NaN
2696                NaN     ...                  NaN                  NaN
2753                NaN     ...                  NaN                  NaN
2767                NaN     ...                  NaN                  NaN
2856                NaN     ...                  NaN                  NaN
3200                NaN     ...                  NaN                  NaN
3515                NaN     ...                  NaN                  NaN
3595                NaN     ...                  NaN                  NaN
3649                NaN     ...                  NaN                  NaN
3743                NaN     ...                  NaN                  NaN
3768                NaN     ...                  NaN                  NaN
3772                NaN     ...                  NaN                  NaN
3786                NaN     ...                  NaN                  NaN
3787                NaN     ...                  NaN                  NaN
3937                n/a     ...                  NaN                  NaN
3970                n/a     ...                  NaN                  NaN
4048                n/a     ...                  NaN                  NaN
4137                NaN     ...                  NaN                  NaN
4179                NaN     ...                  NaN                  NaN
4184                NaN     ...                  NaN                  NaN
4185                NaN     ...                  NaN                  NaN
4187                NaN     ...                  NaN                  NaN
4312                NaN     ...                  NaN  2018-06-28 00:00:00
...                 ...     ...                  ...                  ...
4996                NaN     ...                  NaN  2018-03-05 00:00:00
4997                NaN     ...                  NaN                  NaN
4998                NaN     ...                  NaN                  NaN
5003                NaN     ...                  NaN                  NaN
5010                NaN     ...                  NaN                  NaN
5011                NaN     ...                  NaN                  NaN
5016                NaN     ...                  NaN                  NaN
5019                NaN     ...                  NaN                  NaN
5020                NaN     ...                  NaN                  NaN
5023                NaN     ...                  NaN                  NaN
5026                NaN     ...                  NaN                  NaN
5027                NaN     ...                  NaN                  NaN
5030                NaN     ...                  NaN                  NaN
5031                NaN     ...                  NaN                  NaN
5033                NaN     ...                  NaN                  NaN
5034                NaN     ...                  NaN                  NaN
5037                NaN     ...                  NaN                  NaN
5043                NaN     ...                  NaN                  NaN
5062                NaN     ...                  NaN                  NaN
5068                NaN     ...                  NaN                  NaN
5075                NaN     ...                  NaN                  NaN
5080                NaN     ...                  NaN                  NaN
5082                NaN     ...                  NaN                  NaN
5083                NaN     ...                  NaN                  NaN
5087                NaN     ...                  NaN                  NaN
5103                NaN     ...                  NaN                  NaN
5104                NaN     ...                  NaN                  NaN
5110                NaN     ...                  NaN                  NaN

In [5]:
df['Year opened'] = df['Operational'].dt.year
print df['Year opened'].head(10)
# only keep records that are operational
operating = df.dropna(subset=['Year opened'])
print operating

10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17    2012.0
18       NaN
19       NaN
Name: Year opened, dtype: float64
4    Old Ref ID Ref ID Record Last Updated (dd/mm/yyyy)  \
17        A0331     14              2012-04-04 00:00:00
20        AA851     22              2012-08-10 00:00:00
21        B0242     23              2016-10-25 00:00:00
22        B0376     24              2012-05-29 00:00:00
23        B0461     26              2012-08-07 00:00:00
25      EN00001     28              2010-06-09 00:00:00
27      EN00121     33              2013-10-08 00:00:00
28      EN00151     34              2011-06-29 00:00:00
29      EN00156     35              2016-05-10 00:00:00
30      EN00236     37              2009-12-04 00:00:00
33      EN00569     41              2010-06-09 00:00:00
36      ENA0003     44              2006-05-23 00:00:00
37        H0064     46              2016-09-02 00:00:00
38       IF1016     47              2013-07-04 00:00:00
40      N00009M     49              2010-04-30 00:00:00
47      N00052B     57              2011-06-29 00:00:00
48      N00063B     58              2010-02-05 00:00:00
51      S0030L1     62              2011-06-29 00:00:00
52        C2329     64              2015-02-25 00:00:00
54        B1064     66              2015-06-17 00:00:00
56        AA619     68              2016-09-02 00:00:00
60       IF1368     72              2016-09-02 00:00:00
64      1045000     78              2011-06-29 00:00:00
67      1087000     82              2011-06-29 00:00:00
70        A0005     86              2016-03-18 00:00:00
71        A0063     87              2013-04-29 00:00:00
87        AA118    106              2016-04-18 00:00:00
93        AA379    113              2018-10-03 00:00:00
96        AA431    116              2015-08-13 00:00:00
97        AA725    117              2018-02-01 00:00:00
...         ...    ...                              ...
5019        NaN   6388              2017-05-04 00:00:00
5020        NaN   6390              2017-07-20 00:00:00
5024        NaN   6402              2017-06-01 00:00:00
5025        NaN   6403              2017-06-01 00:00:00
5040        NaN   6442              2017-07-28 00:00:00
5043        NaN   6450              2017-08-16 00:00:00
5048        NaN   6458              2017-09-04 00:00:00
5056        NaN   6485              2017-11-03 00:00:00
5057        NaN   6486              2017-11-03 00:00:00
5058        NaN   6488              2017-10-31 00:00:00
5059        NaN   6489              2017-10-31 00:00:00
5060        NaN   6490              2017-10-31 00:00:00
5061        NaN   6491              2017-10-31 00:00:00
5062        NaN   6492              2017-11-01 00:00:00
5063        NaN   6493              2017-11-01 00:00:00
5066        NaN   6501              2018-07-03 00:00:00
5067        NaN   6506              2017-11-27 00:00:00
5068        NaN   6507              2017-11-28 00:00:00
5069        NaN   6508              2017-11-29 00:00:00
5077        NaN   6520              2017-12-01 00:00:00
5080        NaN   6538              2018-01-03 00:00:00
5086        NaN   6558              2018-02-28 00:00:00
5092        NaN   6578              2018-03-28 00:00:00
5100        NaN   6601              2018-04-05 00:00:00
5105        NaN   6626              2018-05-30 00:00:00
5107        NaN   6636              2018-06-04 00:00:00
5109        NaN   6638              2018-07-02 00:00:00
5116        NaN   6659              2018-09-03 00:00:00
5121        NaN   6683              2018-09-01 00:00:00
5134        NaN   6731              2018-10-03 00:00:00

4                            Operator (or Applicant)  \
17                                            Dalkia
20                                Double H Nurseries
21                              REACT Energy (Kedco)
22                                      Balfor Beaty
23                      Living Power (REG Bio-Power)
25                                            Balcas
27                                     Balcas Timber
28                                  Caledonian Paper
29                                 UK Wood Recycling
30                                          Bioflame
33                                           Norbord
36                                          TPS (UK)
37                                A C Shropshire Ltd
38                  Iggesund Paperboard (Workington)
40                              Ancillary Components
47       Western Bioenergy, affiliate of Western Log
48                                 Eccleshal Biomass
51                                      EPR Scotland
52                       Plymouth Hospital NHS Trust
54                                            Cofely
56                              Oak Grove Renewables
60                                  Lockwood Estates
64                  European Development Corporation
67                      South Western Power (NOVERA)
70                         University Of East Anglia
71                              Suez Energy Services
87                          MVV Energie, Ridham Dock
93                                Glennmont Partners
96                Scottish and Southern Energy (SSE)
97                                 UYE (UK) / Veolia
...                                              ...
5019                                   CBK Galbraith
5020                        Greener For Life Energy
5024                                     Athos Solar
5025                                     Next/ Eneco
5040                           Dartmoor Bio Power 1
5043                                     Bryn Group
5048                                     AR Partners
5056                                        Kingspan
5057                                            Aldi
5058                                   ABP Ellesmere
5059                          Thames Water Utilities
5060                          Thames Water Utilities
5061                          Thames Water Utilities
5062                                  RCMA Stratford
5063                    Monmouthshire County Council
5066  Orsted (formerly Dong Energy)/ Macquarie Group
5067                                    Elgin Energy
5068                         Naturegen Energy Centre
5069                          Thames Water Utilities
5077                                 Belisama Energy
5080                      Privilege Finance/ BioWatt
5086                          Thames Water Utilities
5092                         Pretoria Energy Company
5100                                    GFG Alliance
5105                                 Broadley Energy
5107                  Renewable Energy Systems (RES)
5109                                Black Dog Biogas
5116                                      Drax Power
5121                                Pinguin Foods UK
5134                            SIMEC/ Liberty House

4                                      Site Name  \
17                          Chilton Energy Plant
20              Double H Nurseries Biomass Plant
21          Newry Biomass Phase 1 (Gasification)
22             Beckton STW Biodiesel Power Plant
23     Buslingthorpe Power Station (Leeds North)
25                       Invergordon Pellet Mill
27               Balcas Timber Biomass CHP Plant
28                          Caledonian Papermill
29                          Wilton International
30                               South View Farm
33                        Cowie Biomass Facility
36                        Thornton Power Station
37                            Green's Lodge Farm
38                 Iggesund Paperboard CHP Plant
40                Goosey Lodge Industrial Estate
47                     Western Wood Energy Plant
48                            Eccleshall Biomass
51               Westfield Biomass Power Station
52                            Derriford Hospital
54                Rampton Hospital Energy Centre
56                    Oak Grove Biomass Facility
60                           Land at Grange Farm
64             Elean Business Park Biomass Plant
67                             Eye Biomass Plant
70                 University of East Anglia CHP
71                                   King's Yard
87                              Ridham CHP Plant
93                     Margam Green Energy Plant
96                 Ferrybridge Multifuel 1 (FM1)
97    Holbrook Community Renewable Energy Centre
...                                          ...
5019                              Ferneylea Farm
5020                                Enfield Farm
5024        Haigh Hall Solar Farm (Resubmission)
5025          Next Distribution Centre Doncaster
5040                         Dartmoor Bio Power
5043                Gelliargwellt Uchaf Farm AD
5048                           Sytchwythy Fields
5056                                    Sherburn
5057                              Aldi - Cardiff
5058                      ABP Ellesmere Abbatoir
5059            Swindon Sewerage Treatment Works
5060          Rye Meads Sewerage Treatment Works
5061           Deephams Sewerage Treatment Works
5062                                      Alscot
5063                              Oak Grove Farm
5066                         Race Bank (Phase 2)
5067                       Bann Road (Rasharkin)
5068              Ipswich Hospital Energy Centre
5069               Slough Sewage Treatment Works
5077                      Stormy Down Solar Farm
5080                            Station Works AD
5086                                  Mogden STW
5092                                   Mepal CHP
5100                                    Lochaber
5105                              Broadley Copse
5107                             Forss Wind Farm
5109         Greenhill Anaerobic Digestion Plant
5116         Drax Biomass Power Station - Unit 4
5121                     Chamber 16 (Cold Store)
5134                       Liberty Steel Dalzell

4                      Technology Type Installed Capacity (MWelec)  \
17                 Biomass (dedicated)                          18
20                 Biomass (dedicated)                         1.5
21    Advanced Conversion Technologies                           2
22                 Biomass (dedicated)                           8
23                 Biomass (dedicated)                           2
25                 Biomass (dedicated)                           5
27                 Biomass (dedicated)                        2.45
28                 Biomass (dedicated)                      26.043
29                 Biomass (dedicated)                       35.22
30                 Biomass (dedicated)                           2
33                 Biomass (dedicated)                          15
36                 Biomass (dedicated)                           9
37                 Anaerobic Digestion                           2
38                 Biomass (dedicated)                          49
40                 Biomass (dedicated)                          16
47                 Biomass (dedicated)                          14
48                 Biomass (dedicated)                         2.6
51                 Biomass (dedicated)                        12.5
52                 Biomass (dedicated)                         1.5
54                 Biomass (dedicated)                         1.2
56                 Anaerobic Digestion                           2
60                 Anaerobic Digestion                       1.125
64                 Biomass (dedicated)                          40
67                 Biomass (dedicated)                      14.316
70    Advanced Conversion Technologies                         1.4
71                 Biomass (dedicated)                           3
87                 Biomass (dedicated)                          25
93                 Biomass (dedicated)                          40
96                    EfW Incineration                          68
97                 Biomass (dedicated)                         6.5
...                                ...                         ...
5019                      Wind Onshore                         1.5
5020               Anaerobic Digestion                           2
5024               Solar Photovoltaics                           5
5025               Solar Photovoltaics                         2.5
5040  Advanced Conversion Technologies                         3.9
5043               Anaerobic Digestion                         1.4
5048               Solar Photovoltaics                         1.4
5056               Solar Photovoltaics                           5
5057               Solar Photovoltaics                         1.5
5058               Biomass (dedicated)                         1.1
5059               Anaerobic Digestion                         1.2
5060               Anaerobic Digestion                         2.3
5061               Anaerobic Digestion                           3
5062               Biomass (dedicated)                         1.6
5063               Solar Photovoltaics                        5.67
5066                     Wind Offshore                       286.5
5067               Solar Photovoltaics                          18
5068               Biomass (dedicated)                         2.6
5069           Sewage Sludge Digestion                         1.2
5077               Solar Photovoltaics                         3.8
5080               Anaerobic Digestion                           1
5086           Sewage Sludge Digestion                         5.8
5092               Anaerobic Digestion                        14.4
5100                       Large Hydro                          65
5105               Anaerobic Digestion                         2.2
5107                      Wind Onshore                         2.6
5109               Anaerobic Digestion                           1
5116               Biomass (dedicated)                         645
5121               Solar Photovoltaics                         1.2
5134               Biomass (dedicated)                          17

4    CHP Enabled RO Banding (ROC/MWh) FiT Tariff (p/kWh)     ...      \
17            No                  NaN                NaN     ...
20           Yes                  NaN                NaN     ...
21            No                  NaN                NaN     ...
22            No                  NaN                NaN     ...
23            No                  NaN                NaN     ...
25            No                  NaN                NaN     ...
27           Yes                  NaN                NaN     ...
28            No                  NaN                NaN     ...
29            No                  NaN                NaN     ...
30            No                  NaN                NaN     ...
33            No                  NaN                NaN     ...
36            No                  NaN                NaN     ...
37           Yes                  NaN                NaN     ...
38           Yes                  NaN                NaN     ...
40            No                  NaN                NaN     ...
47           Yes                  NaN                NaN     ...
48            No                  NaN                NaN     ...
51            No                  NaN                NaN     ...
52           Yes                  NaN                NaN     ...
54           Yes                  NaN                NaN     ...
56           Yes                  NaN                NaN     ...
60           Yes                  NaN                NaN     ...
64            No                  NaN                NaN     ...
67            No                  NaN                NaN     ...
70           Yes                  NaN                NaN     ...
71           Yes                  NaN                NaN     ...
87           Yes                  NaN                NaN     ...
93            No                  NaN                NaN     ...
96            No                  NaN                NaN     ...
97           Yes                  NaN                NaN     ...
...          ...                  ...                ...     ...
5019         n/a                  NaN                NaN     ...
5020         yes                  NaN                NaN     ...
5024         n/a                  NaN                NaN     ...
5025         n/a                  NaN                NaN     ...
5040         yes                  NaN                NaN     ...
5043         NaN                  NaN                NaN     ...
5048         n/a                  NaN                NaN     ...
5056         n/a                  NaN                NaN     ...
5057         n/a                  NaN                NaN     ...
5058         Yes                  NaN                NaN     ...
5059         NaN                  NaN                NaN     ...
5060         NaN                  NaN                NaN     ...
5061         Yes                  NaN                NaN     ...
5062         Yes                  NaN                NaN     ...
5063         n/a                  NaN                NaN     ...
5066         n/a                  NaN                NaN     ...
5067         n/a                  NaN                NaN     ...
5068         Yes                  NaN                NaN     ...
5069         Yes                  NaN                NaN     ...
5077         n/a                  NaN                NaN     ...
5080         No                   NaN                NaN     ...
5086         Yes                  NaN                NaN     ...
5092         Yes                  NaN                NaN     ...
5100         n/a                  NaN                NaN     ...
5105         Yes                  NaN                NaN     ...
5107         n/a                  NaN                NaN     ...
5109         Yes                  NaN                NaN     ...
5116         n/a                  NaN                NaN     ...
5121         NaN                  NaN                NaN     ...
5134         NaN                  NaN                NaN     ...

4    Appeal Refused       Appeal Granted Planning Permission Granted  \
17              NaN                  NaN         2009-11-24 00:00:00
20              NaN                  NaN         2012-05-29 00:00:00
21              NaN                  NaN                         NaN
22              NaN                  NaN                         NaN
23              NaN                  NaN         2010-12-30 00:00:00
25              NaN                  NaN         2007-04-16 00:00:00
27              NaN                  NaN         2004-06-01 00:00:00
28              NaN                  NaN         2006-07-11 00:00:00
29              NaN                  NaN         2006-11-07 00:00:00
30              NaN                  NaN         2006-10-24 00:00:00
33              NaN                  NaN         2006-07-27 00:00:00
36              NaN                  NaN                         NaN
37              NaN                  NaN                         NaN
38              NaN                  NaN         2011-03-08 00:00:00
40              NaN                  NaN                         NaN
47              NaN                  NaN         2004-04-27 00:00:00
48              NaN                  NaN         2003-10-29 00:00:00
51              NaN                  NaN         1995-12-05 00:00:00
52              NaN                  NaN         2013-12-10 00:00:00
54              NaN                  NaN         2013-02-06 00:00:00
56              NaN                  NaN         2012-09-25 00:00:00
60              NaN                  NaN         2013-06-04 00:00:00
64              NaN                  NaN         1996-02-22 00:00:00
67              NaN                  NaN                         NaN
70              NaN                  NaN         2007-11-20 00:00:00

In [6]:
operating['Installed Capacity (MWelec)'].max()

740

In [11]:
wind = operating.loc[(operating['Technology Type']=='Wind Offshore')|(operating['Technology Type']=='Wind Onshore')]
wind[['Installed Capacity (MWelec)','Technology Type']].groupby('Technology Type').sum()

4                Installed Capacity (MWelec)
Technology Type
Wind Offshore                       7908.700
Wind Onshore                       12454.742

In [84]:
# list unique types
df.columns.tolist()
# add summary type column and call onwind "wind" (need to iterate this through all types)

#print df[['Technology Type', 'summary type']]

[u'Old Ref ID',
 u'Ref ID',
 u'Record Last Updated (dd/mm/yyyy)',
 u'Operator (or Applicant)',
 u'Site Name',
 u'Technology Type',
 u'Installed Capacity (MWelec)',
 u'CHP Enabled',
 u'RO Banding (ROC/MWh)',
 u'FiT Tariff (p/kWh)',
 u'CfD Capacity (MW)',
 u'Turbine Capacity (MW)',
 u'No. of Turbines',
 u'Height of Turbines (m)',
 u'Mounting Type for Solar',
 u'Development Status',
 u'Development Status (short)',
 u'Address',
 u'County',
 u'Region',
 u'Country',
 u'Post Code',
 u'X-coordinate',
 u'Y-coordinate',
 u'Planning Authority',
 u'Planning Application Reference',
 u'Appeal Reference',
 u'Secretary of State Reference',
 u'Type of Secretary of State Intervention',
 u'Judicial Review',
 u'Offshore Wind Round',
 u'Planning Application Submitted',
 u'Planning Application Withdrawn',
 u'Planning Permission Refused',
 u'Appeal Lodged',
 u'Appeal Withdrawn',
 u'Appeal Refused',
 u'Appeal Granted',
 u'Planning Permission Granted',
 u'Secretary of State - Intervened',
 u'Secretary of State - Refusal',
 u'Secretary of State - Granted',
 u'Planning Permission Expired',
 u'Under Construction',
 u'Operational',
 'Year opened',
 'summary type']

In [6]:
df.head(10)

,Date,Nuclear,Biomass,Imports,Hydro,Wind,Solar,Gas,Coal,Demand,year,month,day,total,RE,lowc,fossil,coalzerohh
0,2009-01-01,6973.0,0.0,1412.0,246.0,148.0,0,11900.0,17650.0,38329.0,2009,1,1,36917.0,394.0,7367.0,29550.0,False
1,2009-01-01,6968.0,0.0,1290.0,245.0,157.0,0,12031.0,17770.0,38461.0,2009,1,1,37171.0,402.0,7370.0,29801.0,False
2,2009-01-01,6970.0,0.0,799.0,246.0,147.0,0,11754.0,18070.0,37986.0,2009,1,1,37187.0,393.0,7363.0,29824.0,False
3,2009-01-01,6969.0,0.0,317.0,246.0,148.0,0,11162.0,18022.0,36864.0,2009,1,1,36547.0,394.0,7363.0,29184.0,False
4,2009-01-01,6960.0,0.0,4.0,246.0,160.0,0,10812.0,17998.0,36180.0,2009,1,1,36176.0,406.0,7366.0,28810.0,False
5,2009-01-01,6969.0,0.0,-116.0,236.0,151.0,0,10698.0,17935.0,35873.0,2009,1,1,35989.0,387.0,7356.0,28633.0,False
6,2009-01-01,6964.0,0.0,-907.0,226.0,124.0,0,10735.0,17564.0,34706.0,2009,1,1,35613.0,350.0,7314.0,28299.0,False
7,2009-01-01,6967.0,0.0,-1020.0,225.0,161.0,0,10481.0,16827.0,33641.0,2009,1,1,34661.0,386.0,7353.0,27308.0,False
8,2009-01-01,6963.0,0.0,-1114.0,225.0,154.0,0,9841.0,16453.0,32522.0,2009,1,1,33636.0,379.0,7342.0,26294.0,False
9,2009-01-01,6960.0,0.0,-1088.0,224.0,165.0,0,9556.0,16037.0,31854.0,2009,1,1,32942.0,389.0,7349.0,25593.0,False

In [7]:
df.set_index('Date', inplace=True)

In [8]:
results = df['Nuclear'].head(0)

df.sort_values(['Nuclear'], ascending=False, inplace=True)
results['Nuclear'] = df['Nuclear'].head(10)

df.sort_values(['Biomass'], ascending=False, inplace=True)
results['Biomass'] = df['Biomass'].head(10)

df.sort_values(['Hydro'], ascending=False, inplace=True)
results['Hydro'] = df['Hydro'].head(10)

df.sort_values(['Wind'], ascending=False, inplace=True)
results['Wind'] = df['Wind'].head(10)

df.sort_values(['Solar'], ascending=False, inplace=True)
results['Solar'] = df['Solar'].head(10)

df.sort_values(['Gas'], ascending=False, inplace=True)
results['Gas'] = df['Gas'].head(10)

df.sort_values(['Coal'], ascending=False, inplace=True)
results['Coal'] = df['Coal'].head(10)

results.to_csv('10_largest_vals_with_dates.csv')

In [9]:
df.describe()

,Nuclear,Biomass,Imports,Hydro,Wind,Solar,Gas,Coal,Demand,year,month,day,total,RE,lowc,fossil
count,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000,152925.000000
mean,7335.656204,653.908021,1205.469247,388.239655,2566.829308,474.535132,12777.886805,10210.493116,35626.276912,2012.873742,6.387778,15.696322,34407.548241,4083.512116,11419.168320,22988.379921
std,961.759615,731.201295,1636.807815,249.512969,2056.138355,1106.769477,5203.749404,6096.520493,7758.558011,2.520646,3.411183,8.792397,7659.202836,3022.037935,3253.456165,8333.597104
min,4099.000000,0.000000,-5305.000000,0.000000,8.000000,0.000000,1556.000000,0.000000,18320.000000,2009.000000,1.000000,1.000000,18090.000000,57.000000,4703.000000,3676.000000
25%,6760.000000,0.000000,144.000000,181.000000,969.000000,0.000000,8751.000000,5139.000000,29686.000000,2011.000000,3.000000,8.000000,28522.000000,1640.000000,9052.000000,16707.000000
50%,7475.000000,474.000000,1473.000000,351.000000,1952.000000,0.000000,13072.000000,10358.000000,35864.000000,2013.000000,6.000000,16.000000,34255.000000,3299.000000,10746.000000,22498.000000
75%,8047.000000,1119.000000,2512.000000,558.000000,3680.000000,261.000000,16863.000000,14798.000000,40948.000000,2015.000000,9.000000,23.000000,39686.000000,5910.000000,13353.000000,28986.000000
max,9342.000000,2441.000000,5412.000000,1403.000000,10823.000000,8910.000000,26566.000000,26044.000000,60070.000000,2017.000000,12.000000,31.000000,58578.000000,19154.000000,27318.000000,48963.000000

In [10]:
print df['Nuclear'].max()
print df['Nuclear'].idxmax()

9342.0
2013-08-19 00:00:00

In [11]:
print df.groupby(['year','month']).mean().reset_index()

     year  month      Nuclear      Biomass      Imports       Hydro  \
0    2009      1  5794.037106     0.000000  -187.636728  545.584406
1    2009      2  8063.098958     0.000000   -55.710565  403.909970
2    2009      3  8522.880777     0.000000    84.449151  579.504571
3    2009      4  8389.706796     0.000000   896.759799  388.635736
4    2009      5  6826.467742     0.000000  1351.060484  308.965726
5    2009      6  8004.785932     0.000000   643.291728  153.376877
6    2009      7  7874.081592     0.000000   645.163019  167.533570
7    2009      8  7686.621965     0.000000   188.858265  370.462405
8    2009      9  7023.880053     0.000000  -641.437564  483.439518
9    2009     10  6353.609825     0.000000 -1201.963658  437.858416
10   2009     11  7277.863940     0.000000  -799.442552  608.236202
11   2009     12  7323.837753     0.000000  -801.124074  430.944863
12   2010      1  8015.969434     0.000000 -1361.371832  258.286050
13   2010      2  7687.009673     0.000000 -1229.442708  187.035714
14   2010      3  7993.663047     0.000000  -945.259849  245.586671
15   2010      4  6688.444627     0.000000  -288.924052  280.140333
16   2010      5  5642.408470     0.000000   203.498933  154.699929
17   2010      6  5675.860032     0.000000  1106.218382  100.292005
18   2010      7  5578.577830     0.000000  1031.273233  215.313137
19   2010      8  5681.077550     0.000000  1316.027079  200.692578
20   2010      9  5473.229577     0.000000   352.885417  312.492265
21   2010     10  7308.422454     0.000000  -769.302141  364.268372
22   2010     11  6494.573266     0.000000  -105.078280  425.874953
23   2010     12  7935.814104     0.000000   -35.613847  185.740460
24   2011      1  8285.901210     0.000000   161.390457  289.060484
25   2011      2  8392.793899     0.000000   -72.808036  492.729911
26   2011      3  8648.648674     0.000000    60.290306  309.141697
27   2011      4  8454.128472     0.000000   572.113194  383.759028
28   2011      5  8123.007161     0.000000  -138.857449  336.789594
29   2011      6  8036.786608     0.000000   664.941915  315.491689
..    ...    ...          ...          ...          ...         ...
75   2015      4  7310.309722  1003.890278  2418.961111  451.755556
76   2015      5  7224.145161   945.343414  2286.013441  454.864247
77   2015      6  7193.059240   967.368329  2418.751435  369.921129
78   2015      7  7231.986405   747.813447  2562.583691  388.201595
79   2015      8  6852.038978  1522.837366  2563.094758  295.949597
80   2015      9  6993.820139  1589.104167  2555.896528  157.582639
81   2015     10  7769.940940  1866.828188  1848.838926  176.444966
82   2015     11  7690.725393  2024.733696  1876.097324  579.950059
83   2015     12  8249.216979  1925.377498  2165.191723  841.661625
84   2016      1  7617.425765  2000.819719  2300.294813  683.443100
85   2016      2  7493.629158  1950.306840  2743.653095  662.165407
86   2016      3  7099.164199  1983.992598  2747.594886  491.974428
87   2016      4  6927.287500  1901.600000  2443.054861  345.804167
88   2016      5  6994.190088  1912.914638  2432.203674  246.443175
89   2016      6  7478.738194  1498.472917  2471.535417  132.945833
90   2016      7  7981.624699  1055.307211  2267.385021  278.074358
91   2016      8  7875.741935  1009.026210  2343.147177  319.690188
92   2016      9  7961.753696  1315.497034  1466.885159  356.409599
93   2016     10  7619.260401  1146.706112   571.684259  304.988968
94   2016     11  8174.318402  1626.282749   877.564424  296.027070
95   2016     12  8026.915995  2016.558468   534.321237  508.731855
96   2017      1  7391.077099  2063.315382   140.138870  721.255812
97   2017      2  8057.089286  2073.422619  1491.872024  685.878720
98   2017      3  7458.908479  2019.020326  2608.155451  832.831090
99   2017      4  7004.251364  1647.265249  2687.562500  250.529861
100  2017      5  7622.198925  1982.647177  2398.421371  160.176075
101  2017      6  8162.652083  1195.833333  2114.679167  201.617361
102  2017      7  7344.352387  1784.545393  2647.823134  222.228648
103  2017      8  7892.489919  1816.119624  2627.176075  343.656586
104  2017      9  7931.050595   909.235119  2214.672619  410.649802

            Wind        Solar           Gas          Coal        Demand  \
0    1058.068419     0.000000  15336.991755  20746.065335  43675.672715
1     786.767113     0.000000  14616.593750  18764.712054  42721.480655
2    1191.921829     0.000000  15357.901778  13499.056129  39276.596231
3     811.989392     0.000000  15393.409860   9279.618757  35183.270139
4    1173.903226     0.000000  15573.176747   8469.797043  33729.653226
5     526.044851     0.000000  15395.266247   8612.742395  33346.752083
6     861.167211     0.000000  16224.998865   7410.931835  33191.472446
7    1062.113271     0.000000  16999.454681   6235.394765  32549.174059
8    1026.869149     0.000000  18195.118005   7938.190154  34039.678472
9     996.139580     0.000000  18267.516257  11270.869367  36155.639597
10   1520.914789     0.000000  19754.817953  10755.532202  39130.866667
11   1162.449320     0.000000  20613.220944  13411.338018  42157.179435
12   1263.421283     0.000000  19501.318629  16852.945645  44550.223790
13    834.186012     0.000000  19926.236607  16072.642113  43489.851190
14   1167.965376     0.000000  20828.399794  10902.960426  40205.070659
15    966.498445     0.199306  19064.395308   8974.801993  35688.485417
16    649.898713     0.618952  19213.375563   8180.770435  34046.711694
17    637.395499     1.424306  17319.469720   8290.092824  33132.312500
18   1173.231237     1.926075  16219.924820   8821.219847  33047.636425
19   1031.620565     2.461694  16839.341321   7173.657627  32245.308468
20   1454.180326     2.946528  16895.913489   9848.096288  34341.461111
21   1740.212513     2.328859  15615.382121  12132.740895  36417.140268
22   1695.177923     1.467361  17225.549282  15256.430213  41013.185417
23   1234.400341     1.141129  16669.206948  18951.425049  45003.020833
24   1685.839382     1.586022  16576.496640  16015.211694  43017.324597
25   1975.787946     2.738095  15234.193452  15452.294643  41487.392857
26   1135.813983     8.449529  14112.381100  15296.575442  39571.734186
27   1377.058333    16.932639  15065.320833   7970.523611  33841.635417
28   2210.531186    21.286290  14868.515505   7853.010420  33274.774866
29   1134.589654    25.879167  14206.144213   8792.211824  33177.545139
..           ...          ...           ...           ...           ...
75   2674.273611  1618.728472   8311.535417   9894.398521  33683.867361
76   3803.483199  1545.618952   8748.078629   6813.094758  31820.920699
77   2689.730076  1758.063194   9920.580902   6123.278895  31440.881250
78   2778.696648  1515.512769   9689.471383   5959.508598  30873.996640
79   2728.489247  1255.931452   9802.610887   5317.899866  30338.866935
80   2423.763194  1211.873611  11210.700694   5890.772222  32034.749306
81   2592.849664   669.314765  10535.867114   8544.720134  34005.217450
82   4991.366030   276.009722  10631.970634   7666.940354  35739.105556
83   5763.830950   205.027554   9424.004441   6258.356659  34833.524194
84   4802.756778   307.170699  13571.771292   6313.195864  37614.601149
85   4292.373386   662.323994  12995.013634   7027.025150  37835.677446
86   3052.139973   979.419246  14556.483849   5540.302153  36464.880215
87   3178.731944  1406.465972  15158.013889   2437.822222  33808.684028
88   3078.659904  1783.361559  13075.890491   1202.454211  30731.272983
89   1906.468056  1525.313889  13818.829167   1947.068750  30795.579167
90   2596.994814  1711.156586  12930.034656   1045.543941  29878.746958
91   2918.909274  1710.208333  12738.652554    689.759409  29618.131720
92   3512.887894  1223.181250  13833.197288   1388.082177  31082.125347
93   3382.726751   898.806711  16791.586777   2536.932503  33276.110603
94   4191.353776   531.820139  17690.191942   4310.126992  37714.891744
95   4889.630376   322.635081  16759.504704   4002.809140  37074.920699
96   4691.894503   397.532930  17792.911090   6353.581748  39579.307569
97   5987.148739   546.980655  13985.850446   5185.829613  38032.142043
98   5099.440556  1153.016824  14301.652759   1968.802153  35464.216603
99   4432.385320  1734.802083  13745.017369    547.990972  32072.343607
100  3762.883065  1879.297715  12774.096774    642.264113  31257.340054
101  4595.390278  1915.306944  11464.348611    598.259722  30277.167361
102  3645.236718  1868.014122  11742.393410    558.211836  29834.173504
103  3680.234543  1667.572581  10874.886425    637.644489  29540.026210
104  4820.084325  1285.336310  11839.608135   1484.728175  30895.391865

           day         total           RE          lowc        fossil  \
0    16.000000  43480.747021  1603.652825   7397.689931  36083.057091
1    14.500000  42635.081845  1190.677083   9253.776042  33381.305804
2    15.982503  39151.265084  1771.426400  10294.307177  28856.957907
3    15.500000  34263.360541  1200.625129   9590.331924  24673.028616
4    16.000000  32352.310484  1482.868952   8309.336694  24042.973790
5    15.500000  32692.216302   679.421728   8684.207660  24008.008642
6    16.000000  32538.713073  1028.700781   8902.782373  23635.930701
7    16.000000  32354.047088  1432.575676   9119.197641  23234.849446
8    15.500000  34667.496880  1510.308667   8534.188721  26133.308159
9    16.012081  37325.993446  1433.997997   7787.607822  29538.385624
10   15.500000  39917.365086  2129.150991   9407.014931  30510.350155
11   16.000000  42941.790898  1593.394183   8917.231936  34024.558962
12   16.000000  45891.941041  1521.707333   9537.676767  36354.264274
13   14.500000  44707.110119  1021.221726   8708.231399  35998.878720
14   15.983849  41138.575314  1413.552047   9407.215094  31731.360220
15   15.500000  35974.480011  1246.838084   7935.282711  28039.197301
16   16.000000  33841.772062   805.217593   6447.626063  27394.145999
17   15.500000  32024.534385   739.111810   6414.971842  25609.562543
18   16.000000  32010.192946  1390.470449   6969.048279  25041.144667
19   16.000000  30928.851335  1234.774837   6915.852387  24012.998948
20   15.500000  33986.858473  1769.619119   7242.848696  26744.009776
21   16.020134  37163.355214  2106.809744   9415.232197  27748.123017
22   15.500000  41099.072998  2122.520238   8617.093503  32481.979495
23   16.000000  44977.728031  1421.281930   9357.096034  35620.631997
24   16.000000  42854.095430  1976.485887  10262.387097  32591.708333
25   14.500000  41550.537946  2471.255952  10864.049851  30686.488095
26   15.985195  39511.010424  1453.405209  10102.053882  29408.956541
27   15.500000  33267.722917  1777.750000  10231.878472  23035.844444
28   16.000000  33413.140157  2568.607071  10691.614232  22721.525925
29   15.500000  32511.103155  1475.960510   9512.747118  22998.356037
..         ...           ...          ...           ...           ...
75   15.500000  31264.891577  5748.647917  13058.957639  18205.933938
76   16.000000  29534.628360  6749.309812  13973.454973  15561.173387
77   15.500000  29022.001766  5785.082729  12978.141969  16043.859797
78   16.000000  28311.190844  5430.224459  12662.210864  15648.979981
79   16.000000  27775.757392  5803.207661  12655.246640  15120.510753
80   15.500000  29477.616667  5382.323611  12376.143750  17101.472917
81   16.012081  32155.965772  5305.437584  13075.378523  19080.587248
82   15.500000  33861.695888  7872.059507  15562.784900  18298.910988
83   16.000000  32667.475706  8735.897627  16985.114606  15682.361100
84   16.000000  35296.583218  7794.190296  15411.616061  19884.967157
85   15.000000  35082.837570  7567.169627  15060.798785  20022.038784
86   15.985195  33703.476447  6507.526245  13606.690444  20096.786003
87   15.500000  31355.725694  6832.602083  13759.889583  17595.836111
88   16.000000  28293.914067  7021.379277  14015.569365  14278.344702
89   15.500000  28307.836806  5063.200694  12541.938889  15765.897917
90   16.000000  27598.736265  5641.532969  13623.157668  13975.578597
91   16.000000  27261.987903  5957.834005  13833.575941  13428.411962
92   15.500000  29591.008938  6407.975777  14369.729473  15221.279465
93   16.018792  32681.008223  5733.228542  13352.488944  19328.519280
94   15.500000  36820.121070  6645.483734  14819.802136  22000.318935
95   16.000000  36526.785618  7737.555780  15764.471774  20762.313844
96   16.000000  39411.568564  7873.998627  15265.075726  24146.492838
97   14.500000  36522.200079  9293.430733  17350.520019  19171.680060
98   15.986541  32833.672188  9104.308797  16563.217276  16270.454913
99   15.500000  29362.242218  8064.982513  15069.233877  14293.008341
100  16.000000  28823.563844  7785.004032  15407.202957  13416.360887
101  15.500000  28133.408333  7908.147917  16070.800000  12062.608333
102  16.002690  27164.982515  7520.024882  14864.377270  12300.605245
103  16.000000  26912.604167  7507.583333  15400.073253  11512.530914
104  11.000000  28680.692460  7425.305556  15356.356151  13324.336310

     coalzerohh
0      0.000000
1      0.000000
2      0.000000
3      0.000000
4      0.000000
5      0.000000
6      0.000000
7      0.000000
8      0.000000
9      0.000000
10     0.000000
11     0.000000
12     0.000000
13     0.000000
14     0.000000
15     0.000000
16     0.000000
17     0.000000
18     0.000000
19     0.000000
20     0.000000
21     0.000000
22     0.000000
23     0.000000
24     0.000000
25     0.000000
26     0.000000
27     0.000000
28     0.000000
29     0.000000
..          ...
75     0.000000
76     0.000000
77     0.000000
78     0.000000
79     0.000000
80     0.000000
81     0.000000
82     0.000000
83     0.000000
84     0.000000
85     0.000000
86     0.000000
87     0.000000
88     0.063844
89     0.000000
90     0.049731
91     0.090054
92     0.052778
93     0.014094
94     0.000000
95     0.000000
96     0.000000
97     0.000000
98     0.000000
99     0.188889
100    0.152554
101    0.090972
102    0.109617
103    0.044355
104    0.000000

[105 rows x 17 columns]

In [39]:
monthly = df.groupby(['year','month']).mean().reset_index()
monthly['windcoal'] = monthly['Wind'] > monthly['Coal']
monthly['solarcoal'] = monthly['Solar'] > monthly['Coal']
monthly['nuc%'] = monthly['Nuclear']/monthly['total']
monthly['bio%'] = monthly['Biomass']/monthly['total']
monthly['hyd%'] = monthly['Hydro']/monthly['total']
monthly['win%'] = monthly['Wind']/monthly['total']
monthly['sol%'] = monthly['Solar']/monthly['total']
monthly['gas%'] = monthly['Gas']/monthly['total']
monthly['coa%'] = monthly['Coal']/monthly['total']
monthly['RE%'] = monthly['RE']/monthly['total']
monthly['lowc%'] = monthly['lowc']/monthly['total']

In [40]:
monthly.to_csv('power_by_month.csv')

In [38]:
daily = df.groupby(['year','month','day']).mean().reset_index()
daily['windcoal'] = daily['Wind'] > daily['Coal']
daily['solarcoal'] = daily['Solar'] > daily['Coal']
daily['coalzeroday'] = daily['Coal'] < 0.01
daily['nuc%'] = daily['Nuclear']/daily['total']
daily['bio%'] = daily['Biomass']/daily['total']
daily['hyd%'] = daily['Hydro']/daily['total']
daily['win%'] = daily['Wind']/daily['total']
daily['sol%'] = daily['Solar']/daily['total']
daily['gas%'] = daily['Gas']/daily['total']
daily['coa%'] = daily['Coal']/daily['total']
daily['RE%'] = daily['RE']/daily['total']
daily['lowc%'] = daily['lowc']/daily['total']
daily.to_csv('power_by_day.csv')

In [28]:
dailycounts = daily.groupby(['year']).sum().reset_index()
dailycounts[['year','windcoal','solarcoal','coalzeroday']].to_csv('dailycounts.csv')

In [16]:
temp01 = df.groupby(['year','month']).sum().reset_index()
temp02 = temp01[['year','month','coalzerohh']]
temp02.to_csv('coal_free_HH.csv')

In [37]:
daily.head(10)

,year,month,day,Nuclear,Biomass,Imports,Hydro,Wind,Solar,Gas,...,Demand,total,RE,lowc,fossil,coalzerohh,windcoal,solarcoal,coalzeroday,nuc%
0,2009,1,1,6967.541667,0.0,1166.562500,309.166667,152.062500,0.0,11578.791667,...,37845.145833,36678.583333,461.229167,7428.770833,29249.812500,0.0,False,False,False,0.189962
1,2009,1,2,6398.958333,0.0,209.208333,322.270833,360.520833,0.0,14397.083333,...,40837.187500,40627.979167,682.791667,7081.750000,33546.229167,0.0,False,False,False,0.157501
2,2009,1,3,5798.312500,0.0,349.750000,356.145833,339.666667,0.0,15162.770833,...,40246.875000,39890.041667,695.812500,6494.125000,33395.916667,0.0,False,False,False,0.145357
3,2009,1,4,5468.229167,0.0,85.812500,339.270833,458.312500,0.0,16307.125000,...,40716.062500,40529.083333,797.583333,6265.812500,34263.270833,0.0,False,False,False,0.134921
4,2009,1,5,5130.208333,0.0,-636.729167,447.000000,645.312500,0.0,18964.979167,...,46577.208333,46599.458333,1092.312500,6222.520833,40376.937500,0.0,False,False,False,0.110092
5,2009,1,6,5134.083333,0.0,-1040.895833,358.833333,541.229167,0.0,19026.270833,...,48078.041667,48267.604167,900.062500,6034.145833,42233.458333,0.0,False,False,False,0.106367
6,2009,1,7,5482.416667,0.0,-458.979167,358.541667,233.000000,0.0,18628.666667,...,48130.270833,48000.958333,591.541667,6073.958333,41927.000000,0.0,False,False,False,0.114215
7,2009,1,8,5520.729167,0.0,-721.791667,337.000000,562.645833,0.0,17661.687500,...,46920.562500,47107.645833,899.645833,6420.375000,40687.270833,0.0,False,False,False,0.117194
8,2009,1,9,5230.625000,0.0,-1370.479167,389.875000,726.770833,0.0,17726.250000,...,46754.416667,47355.500000,1116.645833,6347.270833,41008.229167,0.0,False,False,False,0.110454
9,2009,1,10,5584.791667,0.0,-481.333333,431.750000,1764.833333,0.0,15408.666667,...,43283.791667,43631.166667,2196.583333,7781.375000,35849.791667,0.0,False,False,False,0.128000

In [47]:
temp01 = daily.groupby(['year']).count().reset_index()
temp02 = temp01[['year','day']]
temp02.head(10)

   year  day
0  2009  365
1  2010  365
2  2011  365
3  2012  366
4  2013  365
5  2014  365
6  2015  365
7  2016  366
8  2017  264

In [42]:
monthlycounts = monthly.groupby(['year']).sum().reset_index()
monthlycounts[['year','windcoal','solarcoal']].to_csv('monthlycounts.csv')

In [23]:
onwind = df.loc[(df['Technology Type']=='Wind Onshore') & (df['Development Status']=='Operational')]
onwind['year'] = onwind['Operational'].dt.year
onwind['month'] = onwind['Operational'].dt.month
onwind[['Installed Capacity (MWelec)','year','month']].groupby(['year','month']).sum().reset_index().to_csv('test.csv')

In [24]:
onapp = df.loc[(df['Technology Type']=='Wind Onshore')]
onapp['year'] = onapp['Planning Application Submitted'].dt.year
onapp['month'] = onapp['Planning Application Submitted'].dt.month
onapp[['Installed Capacity (MWelec)','year','month']].groupby(['year','month']).sum().reset_index().to_csv('onapp.csv')

In [25]:
onconstr = df.loc[(df['Technology Type']=='Wind Onshore')&(df['Development Status']=='Under Construction')]
onconstr['year'] = onconstr['Planning Application Submitted'].dt.year
onapp['month'] = onapp['Planning Application Submitted'].dt.month
onapp[['Installed Capacity (MWelec)','year','month']].groupby(['year','month']).sum().reset_index().to_csv('onapp.csv')

In [26]:
constr = df[['Country','Installed Capacity (MWelec)']].loc[(df['Technology Type']=='Wind Onshore')&(df['Development Status']=='Under Construction')].groupby('Country').sum().reset_index()
constr.columns = ['Country','Under construction']
print constr['Under construction'].sum()
print constr

708.5
            Country  Under construction
0           England               31.55
1  Northern Ireland               52.00
2          Scotland              482.35
3             Wales              142.60

In [27]:
df['Country'].replace('Northern Ireland ','Northern Ireland',inplace=True)
df['Country'] = df['Country'].str.strip()
onperm = df[['Country','Installed Capacity (MWelec)']].loc[(df['Development Status'].str.contains('Granted'))&(df['Technology Type']=='Wind Onshore')].groupby('Country').sum().reset_index()
onperm.columns = ['Country','Planning permission']
print onperm['Planning permission'].sum()
print onperm

4154.7
            Country  Planning permission
0           England                94.05
1  Northern Ireland               291.80
2          Scotland              3512.50
3             Wales               256.35

In [28]:
pd.options.display.float_format = '{:,.0f}'.format
table = pd.merge(constr,onperm,left_on='Country',right_on='Country')
table.loc['total'] = table.sum()
table['Country'].replace('EnglandNorthern IrelandScotlandWales','Total',inplace=True)
table

                Country  Under construction  Planning permission
0               England                  32                   94
1      Northern Ireland                  52                  292
2              Scotland                 482                3,512
3                 Wales                 143                  256
total             Total                 708                4,155

In [48]:
df[['Country','Installed Capacity (MWelec)']].loc[(df['Development Status'].str.contains('Granted'))&(df['Technology Type']=='Wind Onshore')].groupby('Country').sum().reset_index()

4            Country  Installed Capacity (MWelec)
0            England                       112.25
1   Northern Ireland                       244.80
2  Northern Ireland                          9.00
3           Scotland                      3167.30
4              Wales                       277.80

In [53]:
df['Country'].unique()

array([u'Wales', u'Scotland', u'England', u'Northern Ireland', nan,
       u'England ', u'Northern Ireland '], dtype=object)

In [29]:
onconstr[['Installed Capacity (MWelec)','year']].groupby(['year']).sum().reset_index()

4  year  Installed Capacity (MWelec)
0  2003                            4
1  2006                           25
2  2008                          177
3  2009                            9
4  2011                          135
5  2012                          176
6  2013                          106
7  2014                           32
8  2015                           44

In [30]:
onwind
onwind['app year'] = onwind['Planning Application Submitted'].dt.year
onwind['app month'] = onwind['Planning Application Submitted'].dt.month


onwind[['Installed Capacity (MWelec)','Country','Planning Application Submitted','app year','app month']].groupby(['Country','app year','app month']).agg({'Installed Capacity (MWelec)':'sum','Planning Application Submitted':'count'}).reset_index().to_csv('windapps.csv', index=False)


onwind['grant year'] = onwind['Planning Permission Granted'].dt.year
onwind['grant month'] = onwind['Planning Permission Granted'].dt.month


onwind[['Installed Capacity (MWelec)','Country','Planning Permission Granted','grant year','grant month']].groupby(['Country','grant year','grant month']).agg({'Installed Capacity (MWelec)':'sum','Planning Permission Granted':'count'}).reset_index().to_csv('windgranteds.csv', index=False)
onwind['Development Status (short)'].unique()

array([u'Operational'], dtype=object)

In [25]:
england = onwind.loc[(onwind['Planning Permission Granted'].dt.year >= 2015)&(onwind['Planning Permission Granted'].dt.month >= 5)&(onwind['Country'] == 'England')]
england.to_csv('since_reset.csv',index=False)

being_built = onwind.loc[(onwind['Development Status'] == 'Under Construction')&(onwind['Country'] == 'England')]
being_built.to_csv('being_built.csv',index=False)

In [42]:
consented = onwind.loc[(onwind['Development Status (short)']=='Awaiting Construction')]
consented['Installed Capacity (MWelec)'] = consented[['Installed Capacity (MWelec)']].apply(
    pd.to_numeric, errors='coerce')
print consented['Installed Capacity (MWelec)'].sum()
#consented.pivot_table(columns='Country',values='Installed Capacity (MWelec)',aggfunc='sum' ).reset_index()
#consented[['Country','grant year','Installed Capacity (MWelec)']].groupby(['Country','grant year']).agg({'Installed Capacity (MWelec)':['sum','mean','count']})
#table.fillna(0)

#print onwind['Installed Capacity (MWelec)'].loc[(onwind['Development Status (short)']=='Awaiting Construction')&(onwind['Country']=='Scotland')&(onwind['grant year']>=2018)].mean()
#print onwind['Installed Capacity (MWelec)'].loc[(onwind['Development Status (short)']=='Awaiting Construction')&(onwind['Country']=='England')].mean()
onwind['Development Status (short)'].unique()

3884.55

/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

array([u'Application Refused', u'Abandoned', u'Operational',
       u'Application Withdrawn', u'Awaiting Construction',
       u'Under Construction', u'Decommissioned',
       u'Planning Permission Expired', u'Application Submitted'], dtype=object)

In [43]:
consented[['Site Name','Operator (or Applicant)','Installed Capacity (MWelec)','Development Status','Development Status (short)','Planning Permission Granted','Planning Permission Expired']].loc[(consented['Country']=='England')]

4,Site Name,Operator (or Applicant),Installed Capacity (MWelec),Development Status,Development Status (short),Planning Permission Granted,Planning Permission Expired
2865,Laurels Farm - second resubmission,Stamford Renewable Power,2.00,Appeal Granted,Awaiting Construction,2014-04-02 00:00:00,NaN
2980,Gallymoor Landfill Site,FCC Environment,1.80,Planning Permission Granted,Awaiting Construction,2012-07-10 00:00:00,NaN
3338,Bullamoor,Muirhall Energy (formerly Infinis),8.00,Planning Permission Granted,Awaiting Construction,2010-12-10 00:00:00,NaN
3340,Heckington Fens,Ecotricity,54.00,Planning Permission Granted,Awaiting Construction,2013-02-08 00:00:00,NaN
3358,Carnaby,FCC Environment,6.00,Planning Permission Granted,Awaiting Construction,2012-02-20 00:00:00,NaN
3560,Hyndburn Wind Farm Extension,Energiekontor UK,8.20,Planning Permission Granted,Awaiting Construction,2015-06-26 00:00:00,NaN
3606,Withernwick extension,Energiekontor UK,8.20,Appeal Granted,Awaiting Construction,2016-12-19 00:00:00,NaN
4162,Land near Ventonteague,Cornwall Council,1.50,Planning Permission Granted,Awaiting Construction,2015-10-26 00:00:00,2018-10-26 00:00:00
4199,Smart Systems,D2Smart Projects,1.00,Planning Permission Granted,Awaiting Construction,2015-09-28 00:00:00,2018-09-28 00:00:00
4872,Checkley Wood Farm,Checkley Wood Energy,3.00,Planning Permission Granted,Awaiting Construction,2017-09-13 00:00:00,2022-09-13 00:00:00
4883,Hameldon Hill Wind Farm,FAB Energy,7.05,Planning Permission Granted,Awaiting Construction,2017-07-28 00:00:00,NaN
4976,Accolade Wines,Clean Earth Energy,1.50,Planning Permission Granted,Awaiting Construction,2017-09-01 00:00:00,2020-09-01 00:00:00

In [50]:
consented.dtypes

4
Old Ref ID                                  object
Ref ID                                      object
Record Last Updated (dd/mm/yyyy)            object
Operator (or Applicant)                     object
Site Name                                   object
Technology Type                             object
Installed Capacity (MWelec)                 object
CHP Enabled                                 object
RO Banding (ROC/MWh)                        object
FiT Tariff (p/kWh)                          object
CfD Capacity (MW)                           object
Turbine Capacity (MW)                       object
No. of Turbines                             object
Height of Turbines (m)                      object
Mounting Type for Solar                     object
Development Status                          object
Development Status (short)                  object
Address                                     object
County                                      object
Region                                      object
Country                                     object
Post Code                                   object
X-coordinate                                object
Y-coordinate                                object
Planning Authority                          object
Planning Application Reference              object
Appeal Reference                            object
Secretary of State Reference                object
Type of Secretary of State Intervention     object
Judicial Review                             object
Offshore Wind Round                         object
Planning Application Submitted              object
Planning Application Withdrawn              object
Planning Permission Refused                 object
Appeal Lodged                               object
Appeal Withdrawn                            object
Appeal Refused                              object
Appeal Granted                              object
Planning Permission Granted                 object
Secretary of State - Intervened             object
Secretary of State - Refusal                object
Secretary of State - Granted                object
Planning Permission Expired                 object
Under Construction                          object
Operational                                 object
app year                                   float64
app month                                  float64
grant year                                 float64
grant month                                float64
dtype: object

In [10]:
df.loc[df['Technology Type'].str.contains('Hydro')]

4,nan,nan,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Installed Capacity (MWelec),CHP Enabled,...,Appeal Withdrawn,Appeal Refused,Appeal Granted,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational
349,NaN,NaN,N00010H,388,2009-07-17 00:00:00,Scottish and Southern Energy (SSE),Glendoe Hydro Scheme,Large Hydro,100,n/a,...,NaN,NaN,NaN,2005-07-28 00:00:00,NaN,NaN,NaN,NaN,2006-05-01 00:00:00,2008-12-01 00:00:00
350,NaN,NaN,N00013H,389,2005-05-12 00:00:00,RWE npower,Stronelarig Hydro Scheme,Large Hydro,10.7,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,NaN,NaN,N00026H,390,2006-05-12 00:00:00,Scottish and Southern Energy (SSE),Fasnakyle Hydro Extension,Large Hydro,7.5,n/a,...,NaN,NaN,NaN,2004-04-01 00:00:00,NaN,NaN,NaN,NaN,2006-05-01 00:00:00,2006-08-01 00:00:00
352,NaN,NaN,N0021H,391,2018-04-04 00:00:00,Hydro Plan (on behalf of Alcan),Kinlochleven Hydro Power Station,Large Hydro,19.5,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909-01-01 00:00:00
353,NaN,NaN,EN00014,393,2006-04-04 00:00:00,Scottish and Southern Energy (SSE),Gaur,Large Hydro,6.4,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953-01-01 00:00:00
354,NaN,NaN,EN00016,394,2006-04-04 00:00:00,Scottish and Southern Energy (SSE),Pitlochry,Large Hydro,15,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1950-01-01 00:00:00
355,NaN,NaN,EN00049,395,2006-04-03 00:00:00,Scottish and Southern Energy (SSE),Loch Gair,Large Hydro,6,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1961-01-01 00:00:00
356,NaN,NaN,EN00051,396,2006-04-03 00:00:00,Scottish and Southern Energy (SSE),Sron Mor,Large Hydro,5,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1957-01-01 00:00:00
357,NaN,NaN,EN00052,397,2010-03-03 00:00:00,Scottish and Southern Energy (SSE),Striven,Large Hydro,8,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1951-01-01 00:00:00
358,NaN,NaN,EN00053,398,2006-04-03 00:00:00,Scottish and Southern Energy (SSE),Aigas,Large Hydro,20,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962-01-01 00:00:00
359,NaN,NaN,EN00054,399,2006-04-03 00:00:00,Scottish and Southern Energy (SSE),Kilmorack,Large Hydro,20,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962-01-01 00:00:00
360,NaN,NaN,EN00057,400,2006-04-03 00:00:00,Scottish and Southern Energy (SSE),Orrin,Large Hydro,18,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1959-01-01 00:00:00
361,NaN,NaN,EN00072,401,2006-04-03 00:00:00,Scottish and Southern Energy (SSE),Tor Achilty,Large Hydro,15,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1954-04-01 00:00:00
362,NaN,NaN,EN00074,402,2006-04-04 00:00:00,Scottish and Southern Energy (SSE),Ceannacroc,Large Hydro,20,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1956-01-01 00:00:00
363,NaN,NaN,EN00075,403,2006-04-04 00:00:00,Scottish and Southern Energy (SSE),Foyers Falls,Large Hydro,5.2,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968-01-01 00:00:00
364,NaN,NaN,EN00076,404,2006-04-04 00:00:00,Scottish and Southern Energy (SSE),Invergarry,Large Hydro,20,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1956-01-01 00:00:00
365,NaN,NaN,EN00077,405,2006-04-04 00:00:00,Scottish and Southern Energy (SSE),Livishie,Large Hydro,15,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962-01-01 00:00:00
366,NaN,NaN,EN00078,406,2009-04-22 00:00:00,Scottish and Southern Energy (SSE),Cassley,Large Hydro,10,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1959-01-01 00:00:00
367,NaN,NaN,EN00081,407,2009-04-22 00:00:00,Scottish and Southern Energy (SSE),Cashlie,Large Hydro,11,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004-09-01 00:00:00
368,NaN,NaN,AA203,408,2016-04-04 00:00:00,Scottish and Southern Energy (SSE),Kildermorie Estate,Large Hydro,7.5,n/a,...,NaN,NaN,NaN,2010-09-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
369,NaN,NaN,B0049,410,2018-04-04 00:00:00,Green Highland Renewables,Loch Eilde Mor Hydro (Kinlochleven extension),Small Hydro,2,n/a,...,NaN,NaN,NaN,2011-07-22 00:00:00,NaN,NaN,NaN,NaN,2016-02-25 00:00:00,2017-10-06 00:00:00
370,NaN,NaN,C3207,411,2016-04-04 00:00:00,RWE Innogy UK,River Pattack Hydro Scheme,Large Hydro,9,n/a,...,NaN,NaN,NaN,2015-07-28 00:00:00,NaN,NaN,NaN,2018-07-28 00:00:00,NaN,NaN
371,NaN,NaN,A0022,412,2018-07-17 00:00:00,Scottish Enterprise,Hunterston,Large Hydro,5,n/a,...,NaN,NaN,NaN,2011-03-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
372,NaN,NaN,02029H3,414,2014-12-31 00:00:00,H20 Power Limited,Beeston Weir Hydro Scheme,Small Hydro,1.66,n/a,...,NaN,NaN,NaN,1995-06-21 00:00:00,NaN,NaN,NaN,NaN,NaN,2000-02-01 00:00:00
373,NaN,NaN,10003H3,415,2009-07-15 00:00:00,Dwr Cymru Welsh Water,Llyn Brianne Dam,Small Hydro,4.35,n/a,...,NaN,NaN,NaN,1994-05-27 00:00:00,NaN,NaN,NaN,NaN,NaN,1997-02-01 00:00:00
374,NaN,NaN,10004H3,416,2010-03-08 00:00:00,Dwr Cymru Welsh Water,Elan Valley Hydro Scheme,Small Hydro,2.9,n/a,...,NaN,NaN,NaN,1996-05-30 00:00:00,NaN,NaN,NaN,NaN,NaN,1997-05-01 00:00:00
375,NaN,NaN,A0092,419,2010-04-30 00:00:00,NaN,Turret water treatment works,Small Hydro,1.9,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1952-01-01 00:00:00
376,NaN,NaN,EN00272,420,2012-12-07 00:00:00,Npower Renewables,Allt Hallater Hydro,Small Hydro,2,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,NaN,NaN,EN00285,421,2009-07-03 00:00:00,Green Power,Inverfarigaig,Small Hydro,4,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1980-01-01 00:00:00
378,NaN,NaN,N00001H,424,2006-05-10 00:00:00,Scottish and Southern Energy (SSE),Kingairloch,Small Hydro,3.5,n/a,...,NaN,NaN,NaN,2003-03-26 00:00:00,NaN,NaN,NaN,NaN,NaN,2005-05-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,NaN,NaN,N00003H,503,2007-05-09 00:00:00,INNOGY plc,Braevallich,Small Hydro,2.2,n/a,...,NaN,NaN,NaN,2003-03-26 00:00:00,NaN,NaN,NaN,NaN,NaN,2005-01-01 00:00:00
450,NaN,NaN,EN00271,504,2012-01-25 00:00:00,Keltneyburn Hydro Ltd,Keltneyburn Hydro,Small Hydro,2,n/a,...,NaN,NaN,NaN,2008-09-24 00:00:00,NaN,NaN,NaN,NaN,NaN,2010-05-01 00:00:00
3861,NaN,NaN,NaN,4707,2017-02-22 00:00:00,Green Highland Renewables,Ceannacroc,Small Hydro,1.6,n/a,...,NaN,NaN,NaN,2014-12-18 00:00:00,NaN,NaN,NaN,2017-12-18 00:00:00,2015-09-15 00:00:00,2017-01-15 00:00:00
3873,NaN,NaN,NaN,4722,2014-12-05 00:00:00,Private Developer,Blackburnhall Self Contained Hydro Generator,Small Hydro,2,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3931,NaN,NaN,NaN,4797,2018-04-25 00:00:00,Broadland Renewable Construction,Bruach Caorainn Hydro Scheme,Small Hydro,1.1,n/a,...,NaN,NaN,NaN,2015-05-14 00:00:00,NaN,NaN,NaN,2018-05-14 00:00:00,2016-06-15 00:00:00,2017-05-15 00:00:00
3943,NaN,NaN,C3412,4818,2016-05-04 00:00:00,Glen Lyn Generations,Glen Lyn Gorge,Small Hydro,1.3,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3979,NaN,NaN,NaN,4881,2014-12-19 00:00:00,RWE,Dolgarrog,Large Hydro,32,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1938-01-01 00:00:00
3980,NaN,NaN,NaN,4882,2014-12-19 00:00:00,RWE,Cwm Dyli,Large Hydro,9.9,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1906-01-01 00:00:00
3981,NaN,NaN,NaN,4883,2014-12-19 00:00:00,RWE,Kielder,Large Hydro,6.1,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1982-06-01 00:00:00
4006,NaN,NaN,NaN,4909,2015-01-05 00:00:00,Dwr Cymru Welsh Water,Llyn Celyn,Small Hydro,4.507,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994-01-01 00:00:00
4007,NaN,NaN,NaN,4910,2015-01-05 00:00:00,Dwr Cymru Welsh Water,Caban Coch,Small Hydro,1.05,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1997-05-01 00:00:00
4092,NaN,NaN,NaN,5028,2015-08-05 00:00:00,Dulas Hydrogeneration,Land East of Allt Airdeasaidh,Small Hydro,2,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4125,NaN,NaN,NaN,5094,2015-04-02 00:00:00,Drummond Estate,Allt an Dubh Choirein,Small Hydro,1.6,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4360,NaN,NaN,NaN,5418,2018-08-21 00:00:00,Green Highland Renewables,River Coiltie Hydro Scheme,Small Hydro,1.9,n/a,...,NaN,NaN,NaN,2015-09-18 00:00:00,NaN,NaN,NaN,2018-09-18 00:00:00,2016-08-15 00:00:00,2017-07-01 00:00:00
4774,NaN,NaN,NaN,5947,2015-12-17 00:00:00,Gilkes Energy,Eas a Ghaill,Small Hydro,1.5,n/a,...,NaN,NaN,NaN,2014-09-19 00:00:00,NaN,NaN,NaN,2017-09-19 00:00:00,2014-11-01 00:00:00,2015-12-01 00:00:00
4775,NaN,NaN,NaN,5948,2015-12-17 00:00:00,Gilkes Energy,Eas a Ghaill,Small Hydro,1.5,n/a,...,NaN,NaN,NaN,2013-12-20 00:00:00,NaN,NaN,NaN,2013-12-20 00:00:00,NaN,NaN
4784,NaN,NaN,NaN,5962,2018-04-04 00:00:00,RWE Npower Renewables,Glen Noe River,Small Hydro,2,n/a,...,NaN,NaN,NaN,2016-09-09 00:00:00,NaN,NaN,NaN,2019-09-09 00:00:00,NaN,NaN
4787,NaN,NaN,NaN,5965,2017-12-19 00:00:00,Gilkes Energy,River Pattack (resubmission),Small Hydro,2,n/a,...,NaN,NaN,NaN,2015-11-19 00:00:00,NaN,NaN,NaN,NaN,2016-01-15 00:00:00,2017-12-07 00:00:00
4924,NaN,NaN,NaN,6195,2016-08-31 00:00:00,Hydroplan/Three Lochs Hydro,Gaineamhach Hydro Scheme Powerhouse,Small Hydro,2,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4925,NaN,NaN,NaN,6196,2016-10-04 00:00:00,RWE Innogy,Conwy Falls,Large Hydro,5,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5004,NaN,NaN,NaN,6366,2018-07-24 00:00:00,Hydro Electric Development,Ystradffin Hydropower Project,Small Hydro,NaN,n/a,...,NaN,NaN,NaN,2017-10-09 00:00:00,NaN,NaN,NaN,2022-10-09 00:00:00,NaN,NaN
5042,NaN,NaN,NaN,6463,2018-07-03 00:00:00,Barn Energy,Cromwell Weir (Right Bank),Small Hydro,1.6,n/a,...,NaN,NaN,NaN,2018-05-23 00:00:00,NaN,NaN,NaN,2021-05-23 00:00:00,NaN,NaN
5074,NaN,NaN,NaN,6545,2018-07-25 00:00:00,Hydroplan,Allt Garaidh Ghualaich Hydro Scheme Powerhouse,Small Hydro,1.08,n/a,...,NaN,NaN,NaN,2018-05-23 00:00:00,NaN,NaN,NaN,2021-05-23 00:00:00,NaN,NaN
5081,NaN,NaN,NaN,6564,2018-03-01 00:00:00,Balmoral Estates/Cairneyhill,Birkhall Estate,Small Hydro,2,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5092,NaN,NaN,NaN,6601,2018-04-05 00:00:00,GFG Alliance,Lochaber,Large Hydro,65,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1924-01-01 00:00:00,1929-01-01 00:00:00
5108,NaN,NaN,NaN,6657,2018-09-03 00:00:00,Dickins Hydro Resources,Allt Charnan,Small Hydro,1,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5112,NaN,NaN,NaN,6675,2018-09-03 00:00:00,Dickins Hydro Resources,Glen Etive Estate Phase I (Allt na Chaorainn),Small Hydro,1.36,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5113,NaN,NaN,NaN,6676,2018-09-03 00:00:00,Dickins Hydro Resources,Glen Etive Estate Phase II (Allt Mheuran & All...,Small Hydro,1.36,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5115,NaN,NaN,NaN,6684,2018-09-01 00:00:00,Glen Hydro Development,Chailleach Hydro,Small Hydro,1.7,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5116,NaN,NaN,NaN,6687,2018-09-01 00:00:00,Simec/Green Highland Renewables,Glen Kinglass,Small Hydro,1,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.loc[df['Site Name'].str.contains('Lynemouth')]

4,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Installed Capacity (MWelec),CHP Enabled,RO Banding (ROC/MWh),FiT Tariff (p/kWh),...,Appeal Withdrawn,Appeal Refused,Appeal Granted,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational
95,AA430,115,2017-09-01 00:00:00,Energetický a prumyslový holding (EPH),Lynemouth Power Station,Biomass (dedicated),420,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2565,N00361W,3255,2010-09-24 00:00:00,Scottish Power Renewables,Lynemouth Windfarm,Wind Onshore,2.4,n/a,NaN,NaN,...,NaN,NaN,2008-02-20 00:00:00,2008-02-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2967,AA008,3752,2012-04-24 00:00:00,Scottish Power Renewables,Lynemouth Windfarm (Resubmission),Wind Onshore,26,n/a,NaN,NaN,...,NaN,NaN,2009-01-08 00:00:00,2009-01-08 00:00:00,NaN,NaN,NaN,NaN,2010-07-01 00:00:00,2012-04-12 00:00:00

In [13]:
df[['No. of Turbines','Installed Capacity (MWelec)','Turbine Capacity (MW)']].loc[df['Development Status']=='Operational']

4    No. of Turbines Installed Capacity (MWelec) Turbine Capacity (MW)
17               n/a                          18                   n/a
20               n/a                         1.5                   n/a
21               n/a                           2                   n/a
22               n/a                           8                   n/a
23               n/a                           2                   n/a
25               n/a                           5                   n/a
27               n/a                        2.45                   n/a
28               n/a                      26.043                   n/a
29               n/a                       35.22                   n/a
30               n/a                           2                   n/a
33               n/a                          15                   n/a
36               n/a                           9                   n/a
37               n/a                           2                   n/a
38               n/a                          49                   n/a
40               n/a                          16                   n/a
47               n/a                          14                   n/a
48               n/a                         2.6                   n/a
51               n/a                        12.5                   n/a
52               n/a                         1.5                   n/a
54               n/a                         1.2                   n/a
56               n/a                           2                   n/a
60               n/a                       1.125                   n/a
64               n/a                          40                   n/a
67               n/a                      14.316                   n/a
71               n/a                           3                   n/a
87               n/a                          25                   n/a
93               n/a                          40                   n/a
96               n/a                          68                   n/a
97               n/a                         6.5                   n/a
98               n/a                        10.5                   n/a
...              ...                         ...                   ...
5012               2                         1.5                  0.75
5013             n/a                           2                   n/a
5017             n/a                           5                   n/a
5018             n/a                         2.5                   n/a
5032             n/a                         3.9                   n/a
5035             n/a                         1.4                   n/a
5040             n/a                         1.4                   n/a
5048             n/a                           5                   n/a
5049             n/a                         1.5                   n/a
5050             n/a                         1.1                   n/a
5051             n/a                         1.2                   n/a
5052             n/a                         2.3                   n/a
5053             n/a                           3                   n/a
5054             n/a                         1.6                   n/a
5055             n/a                        5.67                   n/a
5058              45                       286.5                     6
5059             n/a                          18                   n/a
5060             n/a                         2.6                   n/a
5061             n/a                         1.2                   n/a
5069             n/a                         3.8                   n/a
5072             n/a                           1                   n/a
5078             n/a                         5.8                   n/a
5084             n/a                        14.4                   n/a
5092             n/a                          65                   n/a
5097             n/a                         2.2                   n/a
5099               2                         2.6                   1.3
5101             n/a                           1                   n/a
5102             n/a                           2                   n/a
5109             n/a                         645                   n/a
5114             n/a                         1.2                   n/a

[2507 rows x 3 columns]

In [24]:
df[['Site Name','Installed Capacity (MWelec)','Development Status','Development Status (short)','CfD Capacity (MW)']].loc[(df['Technology Type'].str.contains('Offshore'))&((df['Development Status']=='Planning Permission Granted')|(df['Development Status']=='Planning permission granted'))]

4,Site Name,Installed Capacity (MWelec),Development Status,Development Status (short),CfD Capacity (MW)
2007,East Anglia 3,1200,Planning Permission Granted,Awaiting Construction,NaN
2030,Hornsea Project Two - Optimus and Breesea,1400,Planning Permission Granted,Awaiting Construction,NaN
2044,Dogger Bank Teesside A,1200,Planning Permission Granted,Awaiting Construction,NaN
2048,Neart na Gaoithe,450,Planning Permission Granted,Awaiting Construction,448
2053,Inch Cape,784,Planning Permission Granted,Awaiting Construction,NaN
2055,Seagreen Alpha,525,Planning Permission Granted,Awaiting Construction,NaN
2056,Triton Knoll,860,Planning Permission Granted,Awaiting Construction,NaN
2058,MacColl Offshore Windfarm (Moray Firth),317,Planning Permission Granted,Awaiting Construction,NaN
2060,Telford Offshore Windfarm (Moray Firth),317,Planning Permission Granted,Awaiting Construction,NaN
2061,Stevenson Offshore Windfarm (Moray Firth),316,Planning Permission Granted,Awaiting Construction,NaN
2064,Seagreen Bravo,525,Planning Permission Granted,Awaiting Construction,NaN
2065,Dogger Bank Creyke Beck A & B,2400,Planning Permission Granted,Awaiting Construction,NaN
4706,Forth of Firth (Methil),12,Planning Permission Granted,Awaiting Construction,NaN
4882,Kincardine Offshore Windfarm,50,Planning Permission Granted,Awaiting Construction,NaN
4961,Dounreay Trì Floating Wind Demonstration,10,Planning Permission Granted,Awaiting Construction,NaN
5077,Sofia (Dogger Bank Teesside B),1200,Planning Permission Granted,Awaiting Construction,NaN

In [18]:
df['Development Status'].unique()

array([u'Abandoned', u'Planning Permission Refused',
       u'Planning Application Withdrawn', u'Operational',
       u'Appeal Refused', u'Appeal Withdrawn',
       u'Planning Permission Expired', u'Planning Permission Granted',
       u'Under Construction', u'No Application Required',
       u'Decommissioned', u'Appeal Granted',
       u'Planning Application Submitted', u'Secretary of State - Granted',
       u'Appeal Lodged', u'Secretary of State - Refusal',
       u'Planning permission granted'], dtype=object)

In [22]:
df.columns

Index([u'Old Ref ID', u'Ref ID', u'Record Last Updated (dd/mm/yyyy)',
       u'Operator (or Applicant)', u'Site Name', u'Technology Type',
       u'Installed Capacity (MWelec)', u'CHP Enabled', u'RO Banding (ROC/MWh)',
       u'FiT Tariff (p/kWh)', u'CfD Capacity (MW)', u'Turbine Capacity (MW)',
       u'No. of Turbines', u'Height of Turbines (m)',
       u'Mounting Type for Solar', u'Development Status',
       u'Development Status (short)', u'Address', u'County', u'Region',
       u'Country', u'Post Code', u'X-coordinate', u'Y-coordinate',
       u'Planning Authority', u'Planning Application Reference',
       u'Appeal Reference', u'Secretary of State Reference',
       u'Type of Secretary of State Intervention', u'Judicial Review',
       u'Offshore Wind Round', u'Planning Application Submitted',
       u'Planning Application Withdrawn', u'Planning Permission Refused',
       u'Appeal Lodged', u'Appeal Withdrawn', u'Appeal Refused',
       u'Appeal Granted', u'Planning Permission Granted',
       u'Secretary of State - Intervened', u'Secretary of State - Refusal',
       u'Secretary of State - Granted', u'Planning Permission Expired',
       u'Under Construction', u'Operational'],
      dtype='object', name=4)

In [9]:
df['Technology Type'].unique()

array([u'Biomass (dedicated)', u'Advanced Conversion Technologies',
       u'Anaerobic Digestion', u'EfW Incineration', u'Biomass (co-firing)',
       u'Large Hydro', u'Small Hydro', u'Landfill Gas',
       u'Solar Photovoltaics', u'Sewage Sludge Digestion',
       u'Tidal Barrage and Tidal Stream', u'Shoreline Wave',
       u'Wind Offshore', u'Wind Onshore', u'Hot Dry Rocks (HDR)',
       u'Pumped Storage Hydroelectricity', u'Liquid Air Energy Storage',
       u'Battery', u'Flywheels', u'Fuel Cell (Hydrogen)'], dtype=object)

In [20]:
waste = df.loc[(df['Technology Type']=='EfW Incineration')|(df['Technology Type']=='Advanced Conversion Technologies')]
waste['year'] = waste['Operational'].dt.year
waste['month'] = waste['Operational'].dt.month
waste['appyear'] = waste['Planning Application Submitted'].dt.year
waste['appmonth'] = waste['Planning Application Submitted'].dt.month
#onapp[['Installed Capacity (MWelec)','year','month']].groupby(['year','month']).sum().reset_index().to_csv('onapp.csv')
waste[['Installed Capacity (MWelec)','Development Status','Technology Type']].groupby(['Technology Type','Development Status']).agg({'Installed Capacity (MWelec)': ['sum','count']}).reset_index()
waste.to_csv('waste.csv',index=False, encoding='utf-8')

/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [12]:
operational.sort_values(by='Installed Capacity (MWelec)')

4,Site Name,Technology Type,Installed Capacity (MWelec),Region,lat,lon,Year Open,CHP Enabled,Operator (or Applicant),Fuel,Type
5203,Flat Holm Microgrid Project,Battery,0.005,Wales,51.378056,-3.122498,2006,n/a,Wind & Sun,Storage,Battery
5245,JB Wheaton,Battery,0.005,South West,50.840997,-2.935433,2016,n/a,E.On,Storage,Battery
5207,Horse Island Microgrid Project,Battery,0.012,Scotland,57.987532,-5.344452,2009,n/a,Wind & Sun,Storage,Battery
5204,Foula Community Electricity Scheme,Battery,0.016,Scotland,60.135006,-2.054350,2008,n/a,Foula Community Electricity Trust,Storage,Battery
5210,Isle of Rum Microgrid Project,Battery,0.045,Scotland,57.009477,-6.323878,2015,n/a,Wind & Sun,Storage,Battery
5209,Isle of Muck Microgrid System,Battery,0.045,Scotland,56.835812,-6.238438,2013,n/a,Wind & Sun,Storage,Battery
5237,The Everest System,Battery,0.050,Eastern,52.561638,1.180018,2016,n/a,Connected Energy,Storage,Battery
5208,Isle of Eigg Electrification Project,Battery,0.060,Scotland,56.899526,-6.141617,2008,n/a,Eigg Electric,Storage,Battery
5240,Western International Market (WIM) Site,Battery,0.240,London,51.496154,-0.408174,2016,n/a,London Borough of Hounslow,Storage,Battery
5234,Limberlost Solar Farm,Battery,0.250,South East,51.381113,-1.232508,2015,n/a,Anesco,Storage,Battery
5220,Falcon Project,Battery,0.250,South East,52.040624,-0.759422,2013,n/a,Western Power Distribution,Storage,Battery
5222,Slepe Farm,Battery,0.250,South West,50.739014,-2.101203,2014,n/a,Farm Power Apollo/ Anesco,Storage,Battery
5236,Higher Hill Farm Energy Storage,Battery,0.300,South West,51.079382,-2.695538,2016,n/a,British Solar Renewables / Western Power Distr...,Storage,Battery
589,Former Pluckley Landfill Site,Landfill Gas,1.000,South East,51.177223,0.755341,2002,No,Farley Engineering/ Kent Weald Properties/Clea...,Waste,Landfill Gas
220,Abbots moor Farm Anaerobic Digester (Farm AD),Anaerobic Digestion,1.000,West Midlands,52.838961,-2.930007,2012,No,Private Developer,Waste,Anaerobic Digestion
187,Carr Farm (Farm AD),Anaerobic Digestion,1.000,North West,53.748547,-2.928767,2010,No,Farmgen,Waste,Anaerobic Digestion
287,Waen Biogas (Waste AD),Anaerobic Digestion,1.000,Wales,53.263183,-3.426328,2014,Yes,Ancala Bioenergy (formerly Biogen),Waste,Anaerobic Digestion
407,Glen Fyne 'Merk' Hydro,Small Hydro,1.000,Scotland,56.238000,-5.068141,2015,n/a,Ventient (formerly Infinis),Hydro,Small Hydro
213,Spring Farm (biomass),Anaerobic Digestion,1.000,Eastern,52.701342,1.195013,2011,Yes,Private Developer,Waste,Anaerobic Digestion
1043,Rickfield Farm solar park,Solar Photovoltaics,1.000,South East,52.003491,-1.413562,2014,n/a,Western Power Distribution,Solar,NaN
586,Clifton Hall,Landfill Gas,1.000,North West,53.520745,-2.314552,2003,No,Biffa,Waste,Landfill Gas
587,Chapman's Well,Landfill Gas,1.000,North East,54.851804,-1.731972,2003,No,Natural Power,Waste,Landfill Gas
4166,Knolton Farmhouse Cheese Solar Farm,Solar Photovoltaics,1.000,Wales,52.958786,-2.955859,2016,n/a,Pegasus Group,Solar,NaN
914,Fen Farm Solar Park,Solar Photovoltaics,1.000,East Midlands,53.423280,0.069038,2011,n/a,Ecotricity,Solar,NaN
2629,New Holland,Wind Onshore,1.000,Scotland,58.913298,-2.868907,2014,n/a,Windflow UK,Wind,Onshore Wind
424,Innerwick Hydro,Small Hydro,1.000,Scotland,56.600256,-4.305176,2010,n/a,Shawater,Hydro,Small Hydro
201,Sefter Farm AD Plant (Farm AD),Anaerobic Digestion,1.000,South East,50.788971,-0.737300,2010,Yes,Barfoots of Botley,Waste,Anaerobic Digestion
397,Leacann Hydro,Small Hydro,1.000,Scotland,56.172527,-5.188283,2016,n/a,DHG Hydro,Hydro,Small Hydro
1023,Twin Elm Solar Farm,Solar Photovoltaics,1.000,South West,51.357982,-2.795874,2012,n/a,NaN,Solar,NaN
588,Mark's Quarry,Landfill Gas,1.000,North East,54.812376,-1.511392,2003,No,Ylem Energy,Waste,Landfill Gas
...,...,...,...,...,...,...,...,...,...,...,...
2071,Humber Gateway A,Wind Offshore,219.000,Offshore,53.387463,0.500643,2015,n/a,E.ON\r Humber Wind Ltd/ Balfour Beatty Investm...,Wind,Offshore Wind
3765,Stronelairg Wind Farm,Wind Onshore,228.000,Scotland,57.126925,-4.526370,2018,n/a,Scottish and Southern Energy (SSE),Wind,Onshore Wind
3763,Pen Y Cymoedd,Wind Onshore,228.000,Wales,51.655543,-3.695730,2017,n/a,Vattenfall (previously Nuon Renewables),Wind,Onshore Wind
3572,Kilgallioch wind farm,Wind Onshore,239.000,Scotland,54.988453,-4.801716,2017,n/a,Scottish Power Renewables,Wind,Onshore Wind
2067,Burbo Bank Extension (Burbo Bank 2),Wind Offshore,258.000,Offshore,53.479992,-3.270000,2017,n/a,Orsted (formerly Dong Energy),Wind,Offshore Wind
2044,Centrica (Lincs),Wind Offshore,270.000,Offshore,53.184172,0.498077,2013,n/a,GIB,Wind,Offshore Wind
5071,Race Bank (Phase 2),Wind Offshore,286.500,Offshore,53.135974,0.589174,2018,n/a,Orsted (formerly Dong Energy)/ Macquarie Group,Wind,Offshore Wind
2046,Race Bank (Phase 1),Wind Offshore,286.500,Offshore,53.135974,0.589174,2017,n/a,Orsted (formerly Dong Energy)/ Macquarie Group,Wind,Offshore Wind
5198,Foyers,Pumped Storage Hydroelectricity,300.000,Scotland,57.254357,-4.493820,1974,n/a,SSE Renewables,Storage,Pumped Hydro
2032,Thanet,Wind Offshore,300.000,Offshore,51.429932,1.633411,2010,n/a,Vattenfall,Wind,Offshore Wind
2043,Sheringham Shoal,Wind Offshore,317.000,Offshore,53.135319,1.147922,2012,n/a,Vattenfall,Wind,Offshore Wind
2752,Whitelee,Wind Onshore,322.000,Scotland,55.681207,-4.279061,2007,n/a,CRE Energy/ Scottish Power,Wind,Onshore Wind
3218,Clyde Wind Farm,Wind Onshore,350.000,Scotland,55.441634,-3.542734,2012,n/a,Scottish and Southern Energy (SSE)/ Greencoat ...,Wind,Onshore Wind
2056,Galloper Wind Farm,Wind Offshore,353.000,Offshore,51.879992,2.039993,2018,n/a,RWE Npower Renewables,Wind,Offshore Wind
5196,Ffestiniog,Pumped Storage Hydroelectricity,360.000,Wales,52.980832,-3.968890,1961,n/a,First Hydro Company,Storage,Pumped Hydro
2049,West of Duddon Sands,Wind Offshore,389.000,Offshore,53.985150,-3.462007,2014,n/a,Scottish Power Renewables & Orsted (formerly D...,Wind,Offshore Wind
5221,EFDA JJET Fusion Flywheel,Flywheels,400.000,South East,51.657948,-1.228666,2006,n/a,EFDA JET,Storage,Flywheeel
2050,Rampion Offshore Wind Farm (Hastings Zone),Wind Offshore,400.000,Offshore,50.639994,-0.180003,2017,n/a,E.ON UK,Wind,Offshore Wind
2066,Dudgeon East,Wind Offshore,402.000,Offshore,53.117460,0.613468,2017,n/a,Statoil / Statkraft,Wind,Offshore Wind
96,Lynemouth Power Station,Biomass (dedicated),420.000,North East,55.206722,-1.532504,2018,No,Lynemouth Power,Biomass,NaN
5197,Cruachan,Pumped Storage Hydroelectricity,440.000,Scotland,56.411152,-5.113451,1966,n/a,Scottish Power,Storage,Pumped Hydro
2041,Greater Gabbard Wind Farm,Wind Offshore,504.000,Offshore,51.917645,1.928420,2012,n/a,Airtricity / Fluor Ltd,Wind,Offshore Wind
2070,Gwynt y Mor,Wind Offshore,576.000,Offshore,53.454003,-3.626649,2015,n/a,RWE,Wind,Offshore Wind
2042,London Array Phase 1,Wind Offshore,630.000,Offshore,51.621679,1.495832,2013,n/a,Siemens Gamesa Renewable Energy,Wind,Offshore Wind
170,Drax Biomass Power Station - Unit 2,Biomass (dedicated),645.000,Yorkshire and Humber,53.735589,-0.991097,2014,No,Drax Power,Biomass,NaN
5129,Drax Biomass Power Station - Unit 4,Biomass (dedicated),645.000,Yorkshire and Humber,53.735589,-0.991097,2018,n/a,Drax Power,Biomass,NaN
154,Drax Biomass Power Station - Unit 3,Biomass (dedicated),645.000,Yorkshire and Humber,53.735589,-0.991097,2017,No,Drax Power,Biomass,NaN
153,Drax Biomass Power Station - Unit 1,Biomass (co-firing),645.000,Yorkshire and Humber,53.735589,-0.991097,2013,No,Drax Power,Biomass,Co-firing
2061,Walney 3,Wind Offshore,660.000,Offshore,54.089995,-3.740011,2018,n/a,Orsted (formerly Dong Energy),Wind,Offshore Wind
5195,Dinorwig,Pumped Storage Hydroelectricity,1728.000,Wales,53.118607,-4.113893,1983,n/a,First Hydro Company,Storage,Pumped Hydro

In [18]:
#df[df['Post Code'].str.contains('SN16')]
df[(df['Technology Type']=='Photovoltaic')&(df['Installed Capacity (MWelec)']<5)&(df['Operational'].dt.year==2011)]

Empty DataFrame
Columns: [Old Ref ID, Ref ID, Record Last Updated (dd/mm/yyyy), Operator (or Applicant), Site Name, Technology Type, Storage Type, Storage Co-location REPD Ref ID, Installed Capacity (MWelec), CHP Enabled, RO Banding (ROC/MWh), FiT Tariff (p/kWh), CfD Capacity (MW), Turbine Capacity (MW), No. of Turbines, Height of Turbines (m), Mounting Type for Solar, Development Status, Development Status (short), Address, County, Region, Country, Post Code, X-coordinate, Y-coordinate, Planning Authority, Planning Application Reference, Appeal Reference, Secretary of State Reference, Type of Secretary of State Intervention, Judicial Review, Offshore Wind Round, Planning Application Submitted, Planning Application Withdrawn, Planning Permission Refused, Appeal Lodged, Appeal Withdrawn, Appeal Refused, Appeal Granted, Planning Permission Granted, Secretary of State - Intervened, Secretary of State - Refusal, Secretary of State - Granted, Planning Permission Expired, Under Construction, Operational, lat, lon]
Index: []

[0 rows x 49 columns]

In [27]:
df[['Site Name','Post Code','Installed Capacity (MWelec)','County','X-coordinate','Operational']][(df['County']=='Wiltshire')&(df.Operational.dt.year==2011)]

4,Site Name,Post Code,Installed Capacity (MWelec),County,X-coordinate,Operational
968,Malmesbury Solar,SN16 9SR,5.0,Wiltshire,392558.0,2011-07-25 00:00:00
1002,Kingston Farm,BA15 1AH,5.0,Wiltshire,383092.0,2011-10-01 00:00:00
1134,Lake Farm,SN15 4SQ,5.0,Wiltshire,393800.0,2011-07-01 00:00:00

In [22]:
df.columns

Index([                             u'Old Ref ID',
                                        u'Ref ID',
              u'Record Last Updated (dd/mm/yyyy)',
                       u'Operator (or Applicant)',
                                     u'Site Name',
                               u'Technology Type',
                                  u'Storage Type',
               u'Storage Co-location REPD Ref ID',
                   u'Installed Capacity (MWelec)',
                                   u'CHP Enabled',
                          u'RO Banding (ROC/MWh)',
                            u'FiT Tariff (p/kWh)',
                             u'CfD Capacity (MW)',
                         u'Turbine Capacity (MW)',
                               u'No. of Turbines',
                        u'Height of Turbines (m)',
                       u'Mounting Type for Solar',
                            u'Development Status',
                    u'Development Status (short)',
                                       u'Address',
                                        u'County',
                                        u'Region',
                                       u'Country',
                                     u'Post Code',
                                  u'X-coordinate',
                                  u'Y-coordinate',
                            u'Planning Authority',
                u'Planning Application Reference',
                              u'Appeal Reference',
                  u'Secretary of State Reference',
       u'Type of Secretary of State Intervention',
                               u'Judicial Review',
                           u'Offshore Wind Round',
                u'Planning Application Submitted',
                u'Planning Application Withdrawn',
                   u'Planning Permission Refused',
                                 u'Appeal Lodged',
                              u'Appeal Withdrawn',
                                u'Appeal Refused',
                                u'Appeal Granted',
                   u'Planning Permission Granted',
               u'Secretary of State - Intervened',
                  u'Secretary of State - Refusal',
                  u'Secretary of State - Granted',
                   u'Planning Permission Expired',
                            u'Under Construction',
                                   u'Operational',
                                           u'lat',
                                           u'lon'],
      dtype='object', name=4)

In [28]:
df['Installed Capacity (MWelec)'][(df['Technology Type']=='Wind Onshore')&(df['Development Status']=='Operational')].sum()

12817.891999999994

In [30]:
df[(df['Technology Type']=='Wind Onshore')&(df['Development Status']=='Operational')].sort_values(by='Installed Capacity (MWelec)')

4,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Storage Type,Storage Co-location REPD Ref ID,Installed Capacity (MWelec),CHP Enabled,...,Appeal Granted,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational,lat,lon
2952,A0355,3723,2015-01-07,Green Cat Renewables,Yonderton Farm,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2010-07-23 00:00:00,NaN,NaN,NaN,NaN,2014-08-01 00:00:00,2014-12-01 00:00:00,57.430837,-1.941896
3317,EN00443,4113,2014-12-02,Wind Direct,East Midlands Airport,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2008-03-28 00:00:00,NaN,NaN,NaN,NaN,2011-04-16 00:00:00,2011-05-10 00:00:00,52.826198,-1.342652
3132,C1356,3924,2015-11-25,The Farm Energy Partnership LLP,Bloodhills - repowering,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2013-05-14 00:00:00,NaN,NaN,NaN,NaN,2014-07-15 00:00:00,2015-06-15 00:00:00,52.706978,1.664421
3126,C0862,3918,2016-04-22,George Richards Farms Partnership,Goonabarn Farm Wind Turbines,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2013-07-04 00:00:00,NaN,NaN,NaN,NaN,2016-01-01 00:00:00,2016-04-01 00:00:00,50.349671,-4.960596
2909,A0109,3678,2016-07-28,Tobermore Concrete Products,Magherafelt,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2010-11-11 00:00:00,NaN,NaN,NaN,2015-11-11 00:00:00,2015-11-01 00:00:00,2015-06-12 00:00:00,54.769045,-6.647716
3683,H0047,4514,2016-10-26,Sunnyside Wind Farm,Sunnyside wind cluster,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2013-12-19 00:00:00,NaN,NaN,NaN,NaN,2015-06-15 00:00:00,2015-11-15 00:00:00,55.379019,-3.948910
2704,C1658,3429,2018-11-19,Urban Wind,Moorhouse Farm,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2014-09-11 00:00:00,NaN,NaN,NaN,2017-09-11 00:00:00,2016-08-15 00:00:00,2018-05-15 00:00:00,55.903903,-2.250838
2653,C1509,3361,2017-02-23,Private Developer,PROMISED LAND FARM,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2013-10-15 00:00:00,NaN,NaN,NaN,NaN,2014-09-22 00:00:00,2014-10-22 00:00:00,53.511331,-2.737805
2629,C1708,3321,2015-01-05,Windflow UK,New Holland,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2013-11-06 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-10-20 00:00:00,58.913298,-2.868907
2588,N00422W,3272,2010-03-03,Private Developer,Lodge Farm 1,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2005-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2006-08-01 00:00:00,51.726298,-5.060933
2711,C2320,3437,2017-01-16,Constantine Wind Energy,Little Belhus Restoration Site,Wind Onshore,NaN,NaN,1.00,n/a,...,NaN,2015-05-14 00:00:00,NaN,NaN,NaN,2018-05-14 00:00:00,2016-07-04 00:00:00,2016-09-23 00:00:00,51.522483,0.277635
2853,N00001W,3614,2011-04-11,Windprospect,Haverigg Repowering (Haverigg II),Wind Onshore,NaN,NaN,1.15,n/a,...,NaN,2002-08-15 00:00:00,NaN,NaN,NaN,NaN,NaN,2004-05-01 00:00:00,54.203954,-3.324533
2201,AA015,2747,2011-12-02,Yorkshire Water,Chelker Reservoir (Retention of Turbines),Wind Onshore,NaN,NaN,1.20,n/a,...,NaN,2001-05-30 00:00:00,NaN,NaN,NaN,NaN,NaN,2004-05-01 00:00:00,53.962432,-1.914154
2506,N00163W,3179,2005-09-26,Private Developer,The Haven,Wind Onshore,NaN,NaN,1.20,n/a,...,NaN,2003-02-20 00:00:00,NaN,NaN,NaN,NaN,NaN,2003-11-05 00:00:00,52.128976,-2.318412
2759,06012W5,3496,2009-05-08,E.On,Hare Hill,Wind Onshore,NaN,NaN,1.30,n/a,...,NaN,2000-05-25 00:00:00,NaN,NaN,NaN,NaN,NaN,2004-07-01 00:00:00,54.761581,-1.415109
3668,C3307,4497,2016-06-13,REsense c/o CO2Sense,Norton Fields Farm,Wind Onshore,NaN,NaN,1.30,n/a,...,NaN,2014-12-03 00:00:00,NaN,NaN,NaN,2017-12-03 00:00:00,2015-06-15 00:00:00,2015-09-15 00:00:00,52.164311,-2.142731
2308,EN00166,2943,2017-08-23,Yorkshire Water,Loftsome Bridge,Wind Onshore,NaN,NaN,1.30,n/a,...,NaN,2007-01-31 00:00:00,NaN,NaN,NaN,NaN,NaN,2008-02-01 00:00:00,53.756789,-0.937654
2307,EN00165,2942,2010-06-09,Yorkshire Water,Saltend Wind Turbine,Wind Onshore,NaN,NaN,1.30,n/a,...,NaN,2006-03-06 00:00:00,NaN,NaN,NaN,NaN,NaN,2007-11-01 00:00:00,53.744390,-0.236486
2289,EN00102,2921,2009-07-06,Yorkshire Water,Chelker Reservoir,Wind Onshore,NaN,NaN,1.30,n/a,...,NaN,1991-07-12 00:00:00,NaN,NaN,NaN,NaN,NaN,1992-06-01 00:00:00,53.962432,-1.914154
2077,01023W5,2555,2013-05-09,Ecotricity,South Beach Wind Turbine (Somerton),Wind Onshore,NaN,NaN,1.47,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-07-22 00:00:00,52.709894,1.654462
2078,01038W4,2556,2008-12-04,LRZ Ltd (Taken over by NOVERA),Swaffham 1 - Ecotech Wind Park,Wind Onshore,NaN,NaN,1.47,n/a,...,NaN,1999-02-19 00:00:00,NaN,NaN,NaN,NaN,NaN,1999-08-16 00:00:00,52.656729,0.683267
3105,B0682,3897,2015-12-17,Severn Trent Water,Severn Trent Water - Stoke Bardolph Wind Turbine,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2013-09-19 00:00:00,NaN,NaN,NaN,NaN,2015-03-15 00:00:00,2015-12-15 00:00:00,52.975779,-1.043966
5024,NaN,6388,2017-05-04,CBK Galbraith,Ferneylea Farm,Wind Onshore,NaN,NaN,1.50,n/a,...,2012-09-26 00:00:00,2012-09-26 00:00:00,NaN,NaN,NaN,NaN,2014-12-01 00:00:00,2015-01-01 00:00:00,55.914843,-2.417819
3795,B1514,4629,2015-03-17,North Harris Trust,Monan Hill Wind Turbines,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2008-02-14 00:00:00,NaN,NaN,NaN,NaN,2014-07-01 00:00:00,2015-03-19 00:00:00,57.941675,-6.831798
3061,AA642,3842,2014-02-26,KL Technology Limited,K L Technologies Wind Turbine,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2012-09-05 00:00:00,NaN,NaN,NaN,NaN,NaN,2013-10-30 00:00:00,52.771175,0.385746
3013,AA216,3792,2016-02-16,Blue Energy,Fanny House Farm/Heysham Moss,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2012-10-16 00:00:00,NaN,NaN,NaN,NaN,2014-01-01 00:00:00,2015-02-01 00:00:00,54.037924,-2.871899
3099,B0554,3890,2015-01-20,Blue Energy,Marston Vale Country Park Wind Turbine,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2012-02-01 00:00:00,NaN,NaN,NaN,NaN,2013-10-23 00:00:00,2014-05-01 00:00:00,52.064658,-0.535397
3063,AA670,3845,2017-07-14,RM Brown & Son Ltd,Skeddoway Farm Wind Turbine,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2013-02-01 00:00:00,NaN,NaN,NaN,NaN,2014-09-01 00:00:00,2014-12-01 00:00:00,56.166507,-3.159339
3398,B0535,4196,2015-05-29,Renewable Energy Systems Ltd (RES),Longlands Lane,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2013-11-06 00:00:00,NaN,NaN,NaN,NaN,2014-09-30 00:00:00,2014-12-01 00:00:00,51.563309,-3.747885
3488,B1416,4295,2017-02-02,Arnold White Estates (AWE Renewables),Double Arches Quarry Wind Turbine,Wind Onshore,NaN,NaN,1.50,n/a,...,NaN,2011-08-02 00:00:00,NaN,NaN,NaN,NaN,2014-12-01 00:00:00,2014-12-18 00:00:00,51.951908,-0.634328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2504,N00159W,3177,2018-02-27,Munich Re (previously Peel),Scout Moor Windfarm,Wind Onshore,NaN,NaN,65.00,n/a,...,NaN,2005-05-25 00:00:00,NaN,NaN,NaN,NaN,2007-09-01 00:00:00,2008-06-01 00:00:00,53.668977,-2.267859
3240,N00293W,4033,2013-04-19,Devon Wind Power Ltd,Fullabrook Down Wind Farm,Wind Onshore,NaN,NaN,66.00,n/a,...,NaN,2007-10-10 00:00:00,NaN,NaN,NaN,NaN,2008-07-01 00:00:00,2012-01-24 00:00:00,51.156946,-4.102656
3556,A0348,4368,2017-03-24,Ventient (formerly Infinis),Galawhistle,Wind Onshore,NaN,NaN,66.00,n/a,...,NaN,2012-08-08 00:00:00,NaN,NaN,NaN,2017-08-08 00:00:00,2015-06-18 00:00:00,2017-02-15 00:00:00,55.539575,-3.975422
2884,B0713,3647,2016-05-26,Eneco,Moy Wind Farm (2nd Application),Wind Onshore,NaN,NaN,66.00,n/a,...,NaN,2014-01-24 00:00:00,NaN,NaN,NaN,NaN,2014-04-22 00:00:00,2016-05-12 00:00:00,57.388834,-4.048801
3458,N00229W,4261,2014-07-21,Statkraft,Berry Burn,Wind Onshore,NaN,NaN,66.70,n/a,...,NaN,2009-08-10 00:00:00,NaN,NaN,NaN,NaN,2012-12-05 00:00:00,2014-05-30 00:00:00,57.446611,-3.475393
3791,N000231W,4625,2016-01-04,Scottish and Southern Energy (SSE),Strathy North,Wind Onshore,NaN,NaN,67.65,n/a,...,NaN,2011-11-22 00:00:00,NaN,NaN,NaN,NaN,2014-01-31 00:00:00,2015-12-01 00:00:00,58.490004,-4.033588
3457,N00165W,4260,2015-02-27,Scottish and Southern Energy (SSE),Keadby Wind Farm,Wind Onshore,NaN,NaN,68.00,n/a,...,NaN,2008-02-28 00:00:00,NaN,NaN,NaN,NaN,2013-03-01 00:00:00,2015-02-26 00:00:00,53.611796,-0.763685
3466,N00552W,4269,2016-12-12,Scottish Power Renewables,Dersalloch,Wind Onshore,NaN,NaN,69.00,n/a,...,NaN,2014-07-23 00:00:00,NaN,NaN,NaN,NaN,2015-09-24 00:00:00,2016-08-15 00:00:00,55.304257,-4.488218
3829,EN00095,4664,2017-08-29,Greencoat Capital,Corriegarth,Wind Onshore,NaN,NaN,69.50,n/a,...,NaN,2015-04-02 00:00:00,NaN,NaN,NaN,NaN,2015-05-08 00:00:00,2016-09-30 00:00:00,57.190085,-4.359638
2894,13004W5,3662,2012-07-04,Scottish and Southern Energy (SSE),Gordonbush,Wind Onshore,NaN,NaN,70.00,n/a,...,NaN,2008-04-09 00:00:00,NaN,NaN,NaN,NaN,2010-07-01 00:00:00,2012-06-12 00:00:00,58.059495,-3.959051
2451,N00060W,3119,2015-01-05,Greencoat UK Wind,Braes O'Doune,Wind Onshore,NaN,NaN,72.00,n/a,...,NaN,2004-10-05 00:00:00,NaN,NaN,NaN,NaN,2006-05-01 00:00:00,2006-09-01 00:00:00,56.269829,-4.058937
3008,AA182,3787,2017-07-31,Octopus Investments/Blue Energy,Beinneun,Wind Onshore,NaN,NaN,85.00,n/a,...,NaN,2012-11-04 00:00:00,NaN,NaN,NaN,NaN,2015-07-15 00:00:00,2017-02-16 00:00:00,57.095606,-4.965481
3841,N00032W,4676,2017-05-18,Innogy (formerly RWE npower),Farr Wind Farm,Wind Onshore,NaN,NaN,92.00,n/a,...,NaN,2004-10-05 00:00:00,NaN,NaN,NaN,NaN,2005-04-01 00:00:00,2005-10-01 00:00:00,57.333921,-4.103013
3322,N00033W,4118,2017-11-27,Scottish and Southern Energy (SSE),Dunmaglass Wind Farm,Wind Onshore,NaN,NaN,94.00,n/a,...,NaN,2010-12-29 00:00:00,NaN,NaN,NaN,NaN,2014-06-01 00:00:00,2016-09-13 00:00:00,57.251480,-4.255802
3188,EN00541,3981,2013-04-22,Scottish Power Renewables,Whitelee Windfarm Extension Phase 1,Wind Onshore,NaN,NaN,108.00,n/a,...,NaN,2009-05-20 00:00:00,NaN,NaN,NaN,NaN,2010-12-01 00:00:00,2012-10-31 00:00:00,55.677154,-4.286778
2208,AA059,2757,2013-04-19,NaN,Whitelee Windfarm Extension phase 2,Wind Onshore,NaN,NaN,109.00,n/a,...,NaN,2009-12-12 00:00:00,NaN,NaN,NaN,NaN,2010-12-01 00:00:00,2013-01-15 00:00:00,55.639428,-4.317630
3805,AA202,4640,2018-04-03,Scottish and Southern Energy (SSE),Bhlaraidh (previously Balmacaan),Wind Onshore,NaN,NaN,110.00,n/a,...,NaN,2014-01-17 00:00:00,NaN,NaN,NaN,NaN,2016-03-01 00:00:00,2017-09-15 00:00:00,57.219147,-4.581905
2441,N00045W,3109,2009-05-06,Scottish and Southern Energy (SSE),Hadyard Hill,Wind Onshore,NaN,NaN,120.00,n/a,...,NaN,2003-12-29 00:00:00,NaN,NaN,NaN,NaN,2006-05-01 00:00:00,2006-05-08 00:00:00,55.256823,-4.731907
2577,N00366W,3258,2011-10-25,Scottish Power Renewables,Arecleoch Windfarm,Wind Onshore,NaN,NaN,120.00,n/a,...,NaN,2008-06-01 00:00:00,NaN,NaN,NaN,NaN,2009-09-01 00:00:00,2011-06-14 00:00:00,55.068785,-4.797054
2448,N00056W,3116,2011-12-14,Scottish Power Renewables,Black Law,Wind Onshore,NaN,NaN,124.00,n/a,...,NaN,2004-02-13 00:00:00,NaN,NaN,NaN,NaN,NaN,2004-05-31 00:00:00,55.762189,-3.762567
3323,N00099W,4119,2014-07-02,Scottish Power Renewables,Harestanes,Wind Onshore,NaN,NaN,136.00,n/a,...,2007-09-10 00:00:00,2007-09-10 00:00:00,NaN,NaN,NaN,NaN,2012-10-18 00:00:00,2014-07-01 00:00:00,55.239029,-3.574198
2712,EN00297,3440,2010-10-28,Fred Olsen Renewables,Crystal Rig Wind Farm Phase 2a,Wind Onshore,NaN,NaN,138.00,n/a,...,NaN,2008-07-30 00:00:00,NaN,NaN,NaN,NaN,2010-03-01 00:00:00,2010-10-25 00:00:00,55.899481,-2.529311
3265,N00549W,4059,2016-02-15,EDF Energy Renewables,Fallago Rig,Wind Onshore,NaN,NaN,144.00,n/a,...,2010-11-09 00:00:00,2010-11-09 00:00:00,NaN,NaN,NaN,NaN,2011-03-01 00:00:00,2013-03-31 00:00:00,55.831308,-2.688028
3235,N00272W,4028,2012-02-29,Greenpower (Griffin) Ltd,Griffin Wind farm,Wind Onshore,NaN,NaN,156.00,n/a,...,NaN,2008-01-31 00:00:00,NaN,NaN,NaN,NaN,2010-07-01 00:00:00,2012-02-28 00:00:00,56.581223,-3.733752
3380,AA509,4178,2018-06-01,Scottish and Southern Energy (SSE)/ GIB,Clyde Wind Farm Extension (Clyde 2),Wind Onshore,NaN,NaN,172.80,n/a,...,NaN,2014-07-23 00:00:00,NaN,NaN,NaN,NaN,2015-07-20 00:00:00,2017-08-15 00:00:00,55.504143,-3.547902
3765,AA513,4597,2019-01-02,Scottish and Southern Energy (SSE),Stronelairg Wind Farm,Wind Onshore,NaN,NaN,228.00,n/a,...,NaN,2014-06-06 00:00:00,NaN,NaN,NaN,NaN,2017-04-20 00:00:00,2018-12-11 00:00:00,57.126925,-4.526370
3763,A0232,4595,2018-06-04,Vattenfall (previously Nuon Renewables),Pen Y Cymoedd,Wind Onshore,NaN,NaN,228.00,n/a,...,NaN,2012-05-08 00:00:00,NaN,NaN,NaN,NaN,2014-02-06 00:00:00,2017-05-19 00:00:00,51.655543,-3.695730
3572,A0334,4386,2018-02-22,Scottish Power Renewables,Kilgallioch wind farm,Wind Onshore,NaN,NaN,239.00,n/a,...,NaN,2013-02-21 00:00:00,NaN,NaN,NaN,NaN,2015-07-28 00:00:00,2017-12-15 00:00:00,54.988453,-4.801716
2752,N00055W,3489,2010-05-20,CRE Energy/ Scottish Power,Whitelee,Wind Onshore,NaN,NaN,322.00,n/a,...,NaN,2006-04-01 00:00:00,NaN,NaN,NaN,NaN,2006-12-01 00:00:00,2007-12-14 00:00:00,55.681207,-4.279061
3218,N00139W,4011,2018-06-01,Scottish and Southern Energy (SSE)/ Greencoat ...,Clyde Wind Farm,Wind Onshore,NaN,NaN,350.00,n/a,...,NaN,2008-07-21 00:00:00,NaN,NaN,NaN,NaN,NaN,2012-10-01 00:00:00,55.441634,-3.542734

In [33]:
df['Installed Capacity (MWelec)'][(df['Technology Type']=='Solar Photovoltaics')&(df['Development Status']=='Operational')].sum()b

8380.88999999999

In [32]:
df['Technology Type'].unique()

array([u'Biomass (dedicated)', u'Advanced Conversion Technologies',
       u'Anaerobic Digestion', u'EfW Incineration', u'Biomass (co-firing)',
       u'Large Hydro', u'Small Hydro', u'Landfill Gas',
       u'Solar Photovoltaics', u'Sewage Sludge Digestion',
       u'Tidal Barrage and Tidal Stream', u'Shoreline Wave',
       u'Wind Offshore', u'Wind Onshore', u'Hot Dry Rocks (HDR)',
       u'Pumped Storage Hydroelectricity', u'Liquid Air Energy Storage',
       u'Battery', u'Flywheels', u'Fuel Cell (Hydrogen)'], dtype=object)

In [38]:
df[(df['Technology Type']=='Battery')&(df['Site Name'].str.contains('Fair'))]

4,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Storage Type,Storage Co-location REPD Ref ID,Installed Capacity (MWelec),CHP Enabled,...,Appeal Granted,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational,lat,lon
5393,NaN,7091,2018-10-19,Renewable Energy Systems,Fair Oak Lane,Battery,Stand-alone Storage,n/a,49.9,n/a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.341536,-0.320369

In [114]:
renewable[renewable.Fuel=='Biomass'].sort_values(['Capacity (MW)'],ascending=False)

,CHP,Capacity (MW),Company,Fuel,Latitude,Longitude,Region,Site,Type,Year Open,yearEnd,yearStart
170,No,645.000,Drax Power,Biomass,53.735589,-0.991097,Yorkshire and Humber,Drax Biomass,NaN,2014.0,2019,2014
5134,n/a,645.000,Drax Power,Biomass,53.735589,-0.991097,Yorkshire and Humber,Drax Biomass,NaN,2018.0,2019,2018
154,No,645.000,Drax Power,Biomass,53.735589,-0.991097,Yorkshire and Humber,Drax Biomass,NaN,2017.0,2019,2017
153,No,645.000,Drax Power,Biomass,53.735589,-0.991097,Yorkshire and Humber,Drax Biomass,Co-firing,2013.0,2019,2013
96,No,420.000,Lynemouth Power,Biomass,55.206722,-1.532504,North East,Lynemouth Power Station,NaN,2018.0,2019,2018
133,Yes,299.000,Macquarie/ PKA/ MGT Power,Biomass,54.602146,-1.161282,North East,Tees Renewable Energy Plant,NaN,NaN,2019,2019
135,Yes,65.000,RWE,Biomass,56.201180,-3.162255,Scotland,Markinch Biomass CHP Plant,NaN,2014.0,2019,2014
174,No,50.400,E.ON (formerly Powergen). Agent Environmental...,Biomass,55.152401,-3.380891,Scotland,Stevens Croft,NaN,2007.0,2019,2007
39,Yes,49.000,Iggesund Paperboard (Workington),Biomass,54.663976,-3.547331,North West,Iggesund Paperboard CHP Plant,NaN,2013.0,2019,2013
163,No,44.200,Burmeister & Wain Scandinavian Contractor A/S ...,Biomass,52.479148,0.954434,Eastern,Snetterton Biomass Plant,NaN,2016.0,2019,2016
132,Yes,43.000,Tilbury Green Power,Biomass,51.460403,0.349677,Eastern,Tilbury Green Power,NaN,2017.0,2019,2017
141,Yes,42.000,Brite Partnership Copenhagen Infrastructure Pa...,Biomass,53.422585,-1.373370,Yorkshire and Humber,Templeborough Biomass Power Plant- Rotherham,NaN,2019.0,2019,2019
112,Yes,41.600,GDF SUEZ ENERGY UK,Biomass,53.425108,-2.419517,North West,SAICA Paper Mill,NaN,2012.0,2019,2012
130,No,40.000,Eco2,Biomass,53.542328,-0.509609,Yorkshire and Humber,Brigg Renewable Energy Plant (Re-submission),NaN,2016.0,2019,2016
92,Yes,40.000,Glennmont Partners,Biomass,54.587779,-1.230733,North East,Port Clarence Biomass Plant,NaN,NaN,2019,2019
94,No,40.000,Glennmont Partners,Biomass,51.563309,-3.747885,Wales,Margam Green Energy Plant,NaN,2017.0,2019,2017
183,Yes,40.000,Glenmont,Biomass,52.999010,-0.382723,East Midlands,Sleaford Renewable Energy Plant,NaN,2014.0,2019,2014
65,No,40.000,European Development Corporation,Biomass,52.397915,0.129730,Eastern,Elean Business Park Biomass Plant,NaN,2000.0,2019,2004
30,No,35.220,UK Wood Recycling,Biomass,54.567351,-1.096726,North East,Wilton International,NaN,2007.0,2019,2007
146,Yes,30.000,E.On,Biomass,53.420135,-1.398460,Yorkshire and Humber,Blackburn Meadows Biomass Plant,NaN,2014.0,2019,2014
102,Yes,27.700,Estover Energy,Biomass,55.096940,-1.620629,North East,Cramlington CHP,NaN,2018.0,2019,2018
29,No,26.043,Caledonian Paper,Biomass,55.579645,-4.639539,Scotland,Caledonian Papermill,NaN,2009.0,2019,2009
88,Yes,25.000,"MVV Energie, Ridham Dock",Biomass,51.382331,0.758822,South East,Ridham CHP Plant,NaN,2016.0,2019,2016
4866,Yes,22.000,Solar 21,Biomass,53.819046,-0.146472,North East,Hull Biomass Plant (Tansterne power station),NaN,2018.0,2019,2018
4912,No,20.300,SPEP,Biomass,53.047956,-0.810699,East Midlands,Balderton,NaN,2015.0,2019,2015
168,Yes,20.000,Burmeister & Wain Scandinavian (BWSC)/ Bioener...,Biomass,53.354564,-2.751290,North West,Widnes 3MG Biomass/Mersey Bioenergy (CHP) Plant,NaN,2017.0,2019,2017
123,Yes,19.000,"Icon, EEA Holdings & 2OC consortium",Biomass,51.518207,0.088508,London,Beckton Gas Pressure Reduction Station,NaN,2015.0,2019,2015
4086,No,18.000,REG Bio-Power,Biomass,53.814634,-0.992237,Yorkshire and Humber,Whitemoor,NaN,2014.0,2019,2014
4867,Yes,18.000,SIMEC Group,Biomass,51.548527,-2.949183,Wales,Uskmouth Power Station,Co-firing,2015.0,2019,2015
18,No,18.000,Dalkia,Biomass,54.668027,-1.566632,North East,Chilton Energy Plant,NaN,2012.0,2019,2012
...,...,...,...,...,...,...,...,...,...,...,...,...
4644,Yes,6.800,Veolia Energy Services,Biomass,52.840430,-1.033846,East Midlands,The Sawmill,NaN,2017.0,2019,2017
98,Yes,6.500,UYE (UK) / Veolia,Biomass,53.330812,-1.332311,Yorkshire and Humber,Holbrook Community Renewable Energy Centre,NaN,2017.0,2019,2017
4851,Yes,5.600,Northern Energy Developments,Biomass,56.452852,-4.334229,Scotland,Acharn Forest Killin Biomass Plant,NaN,2017.0,2019,2017
151,No,5.500,Diageo,Biomass,56.189699,-3.055896,Scotland,Diageo Biomass Energy Project,NaN,2013.0,2019,2013
144,Yes,5.000,Bester Generacion,Biomass,52.334377,-0.695258,East Midlands,"Pulse Park, Wellingborough",NaN,NaN,2019,2019
26,No,5.000,Balcas,Biomass,57.705392,-4.159927,Scotland,Invergordon Pellet Mill,NaN,2009.0,2019,2009
111,Yes,4.600,REG Bio-Power,Biomass,52.129943,1.430346,Eastern,Bentwaters CHP,NaN,2010.0,2019,2010
4868,Yes,3.500,GIB and Equitix,Biomass,58.434738,-3.085531,Scotland,Pulteney Distillery,NaN,2012.0,2019,2012
119,Yes,3.200,Eco Sustainable Solutions,Biomass,50.785975,-1.856900,South West,Eco Composting,NaN,2017.0,2019,2017
4827,Yes,3.200,Volac,Biomass,52.197223,-4.168906,Wales,Felinfach,NaN,2016.0,2019,2016
4958,Yes,3.000,Newbridge Energy,Biomass,53.121252,-3.323012,Wales,Blazer Fuels,NaN,2017.0,2019,2017
72,Yes,3.000,Suez Energy Services,Biomass,51.535860,-0.005579,London,King's Yard,NaN,2012.0,2019,2012
5079,Yes,2.600,Naturegen Energy Centre,Biomass,52.056849,1.197915,Eastern,Ipswich Hospital Energy Centre,NaN,2017.0,2019,2017
49,No,2.600,Eccleshal Biomass,Biomass,52.874648,-2.246725,West Midlands,Eccleshall Biomass,NaN,2007.0,2019,2007
4897,Yes,2.550,Glennon Brothers Troon,Biomass,55.547139,-4.681435,Scotland,Harbour Road,NaN,2017.0,2019,2017
95,Yes,2.500,Merevale and Blyth Estates,Biomass,52.571658,-1.586704,West Midlands,Merevale & Blyth Estate (Biomass Plant),NaN,NaN,2019,2019
28,Yes,2.450,Balcas Timber,Biomass,54.307328,-7.663943,Northern Ireland,Balcas Timber Biomass CHP Plant,NaN,2005.0,2019,2005
108,No,2.100,Markley Group,Biomass,51.810148,-2.282043,South West,Markley Group (Premiere Kitckens) Biomass,NaN,2012.0,2019,2012
103,No,2.100,Private Developer,Biomass,54.852086,-7.406464,Northern Ireland,Tyrone Energy 1,NaN,2012.0,2019,2012
24,No,2.000,Living Power (REG Bio-Power),Biomass,53.814327,-1.542615,Yorkshire and Humber,Buslingthorpe Power Station (Leeds North),NaN,2011.0,2019,2011
31,No,2.000,Bioflame,Biomass,54.270322,-0.758573,Yorkshire and Humber,South View Farm,NaN,2007.0,2019,2007
160,Yes,1.900,Northampton General Hospital,Biomass,52.236485,-0.881930,East Midlands,Northampton General Hospital,NaN,2016.0,2019,2016
110,Yes,1.800,Heathrow Airport,Biomass,51.459215,-0.459480,London,Heathrow Airport Biomass CHP,NaN,2013.0,2019,2013
5071,Yes,1.600,RCMA Stratford,Biomass,52.175002,-1.679005,West Midlands,Alscot,NaN,2017.0,2019,2017
21,Yes,1.500,Double H Nurseries,Biomass,50.750782,-1.678119,South East,Double H Nurseries Biomass Plant,NaN,2012.0,2019,2012
53,Yes,1.500,Plymouth Hospital NHS Trust,Biomass,50.416720,-4.113685,South West,Derriford Hospital,NaN,2014.0,2019,2014
55,Yes,1.200,Cofely,Biomass,53.290385,-0.838213,East Midlands,Rampton Hospital Energy Centre,NaN,2015.0,2019,2015
182,No,1.200,NaN,Biomass,56.915219,-2.387581,Scotland,Macphie of Glenbervie,NaN,2008.0,2019,2008
5067,Yes,1.100,ABP Ellesmere,Biomass,52.854279,-2.898627,West Midlands,ABP Ellesmere Abbatoir,NaN,2015.0,2019,2015
4545,Yes,1.000,Earthworm,Biomass,52.256278,-1.186996,East Midlands,Daventry,NaN,2018.0,2019,2018

In [26]:
renewable[renewable.Site.str.contains('Gabbard')]

,CHP,Capacity (MW),Company,Fuel,Latitude,Longitude,Region,Site,Type,Year Open,yearEnd,yearStart
1323,n/a,504.0,SSE / Innogy,Wind,51.917645,1.92842,Offshore,Greater Gabbard Wind Farm,Offshore Wind,2012.0,2019,2012

In [24]:
df[df['Site Name'].str.contains('Gabbard')]
#df.head()

4,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Storage Type,Storage Co-location REPD Ref ID,Installed Capacity (MWelec),CHP Enabled,...,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational,lat,lon,Contracted
2041,N00443W,2510,2018-11-08,Airtricity / Fluor Ltd,Greater Gabbard Wind Farm,Wind Offshore,NaN,NaN,504.0,n/a,...,2007-02-20 00:00:00,NaN,NaN,NaN,NaN,2009-07-01 00:00:00,2012-09-07 00:00:00,51.917645,1.92842,NaN

In [39]:
onwind.pivot_table(index=('year','month'),columns='Country',values='Installed Capacity (MWelec)',aggfunc='sum').reset_index().to_csv('new_onshore.csv',index=False)